### ISSUE TITLE
.class files are generated in the SRC file

### ISSUE THREAD

**Issue by hedefalk** [ensime/ensime-server#1018]
_From @omidb on June 26, 2015 17:59_

my .ensime file:
```scala
(
 :root-dir "E:\\workspace\\tut\\testEnsime"
 :cache-dir "E:\\workspace\\tut\\testEnsime\\.ensime_cache"
 :name "testensime"
 :java-home "C:\\Program Files\\Java\\jdk1.8.0_25"
 :java-flags ("-Xmx1G" "-XX:MaxPermSize=256m" "-XX:ReservedCodeCacheSize=128m" "-Dsbt.log.format=true")
 :reference-source-roots ("C:\\Program Files\\Java\\jdk1.8.0_25\\src.zip")
 :scala-version "2.11.4"
 :compiler-args nil
 
 :subprojects ((
   :name "testensime"
   :module-name "testensime"
   :source-roots ("E:\\workspace\\tut\\testEnsime\\src\\main\\scala")
   :target "E:\\workspace\\tut\\testEnsime\\target\\scala-2.11\\classes"
   :test-targets ("E:\\workspace\\tut\\testEnsime\\target\\scala-2.11\\test-classes")
   :depends-on-modules nil
   :compile-deps ("C:\\Users\\Omid\\.ivy2\\cache\\org.scala-lang\\scala-library\\jars\\scala-library-2.11.4.jar")
   :runtime-deps nil
   :test-deps nil
   :doc-jars ("C:\\Users\\Omid\\.ivy2\\cache\\org.scala-lang\\scala-library\\docs\\scala-library-2.11.4-javadoc.jar" "E:\\workspace\\tut\\testEnsime\\target\\scala-2.11\\hello_2.11-1.0-javadoc.jar")
   :reference-source-roots ("C:\\Users\\Omid\\.ivy2\\cache\\org.scala-lang\\scala-library\\srcs\\scala-library-2.11.4-sources.jar")))
 
)
```

but `.class` files are in src folder, what is wrong?

_Copied from original issue: ensime/ensime-atom#33_

**Comment by hedefalk** [comment]
Sorry, absolutely no idea. Is the .ensime generated by gen-ensime or hand-written? I'll move this issue to ensime-server, since it most likely isn't atom related.

**Comment by omidb** [comment]
Here is an screenshot of what I'm getting now:
![image](https://cloud.githubusercontent.com/assets/4734340/8387489/b28bd66c-1c0d-11e5-8460-0d99a8e4bcbc.png)

**Comment by hedefalk** [comment]
Weird. Are you hacking on this plugin or do you have other scala plugins installed? Those error markers I don't recognize?

**Comment by omidb** [comment]
Here is what I get in my packages: 
![image](https://cloud.githubusercontent.com/assets/4734340/8387784/49656ee8-1c10-11e5-8961-06a2f98ce485.png)

**Comment by hedefalk** [comment]
Ok, those red markings you have are probably from scala-linter. I only tried it briefly so I don't know much about it, but for the sake of this report, could you deactivate scala-linter, clean off those .class files and make sure it's ensime that's to blame.

**Comment by omidb** [comment]
@hedefalk I already did, I think Ensime is not starting at all. Because when I turned off the linter and deleted those files, and get back to the Atom and `Ensime:start' then I don't get any type checking or anything!
The reason that I thought that those are Ensime related errors was I never saw any screenshot from Ensime output :)

**Comment by omidb** [comment]
@hedefalk I completely uninstall (also deleted my `.atom` folder), then install Atom, and just `Ensime` and when I do `Ensime:start` for the first time it get updated (run the sbt command) and then I cannot see anything that shows it's working. Instead of a box on bottom of screen:
![image](https://cloud.githubusercontent.com/assets/4734340/8388225/9499d1e8-1c14-11e5-98be-5297ae02e0bd.png)

**Comment by hedefalk** [comment]
That doesn't seem nice at all… There should pop up a few messages there at the botton when server is connected. How does the output from the sbt command that does the server update look? In that other window?

By the way, I'm so sorry, but I got to hit the sack like right now (GMT+2) so won't be responsive for some hours.

**Comment by omidb** [comment]
```scala
[info] Loading global plugins from C:\Users\Omid\.sbt\0.13\plugins
[info] Loading project definition from C:\Users\Omid\.atom\packages\Ensime\ensime_update_\project
[info] Updating {file:/C:/Users/Omid/.atom/packages/Ensime/ensime_update_/project/}ensime_update_-build...
[info] Resolving org.scala-sbt#global-plugins;0.0 ...
[info] Resolving org.ensime#ensime-sbt;0.1.7 ...
[info] Resolving org.scalariform#sbt-scalariform;1.4.0 ...
[info] Resolving org.scalariform#scalariform_2.10;0.1.6 ...
[info] Resolving org.scala-lang#scala-library;2.10.4 ...
[info] Resolving org.scala-sbt#sbt;0.13.8 ...
[info] Resolving org.scala-sbt#main;0.13.8 ...
[info] Resolving org.scala-sbt#actions;0.13.8 ...
[info] Resolving org.scala-sbt#classpath;0.13.8 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.4 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.4 ...
[info] Resolving org.scala-sbt#launcher-interface;0.13.8 ...
[info] Resolving org.scala-sbt#interface;0.13.8 ...
[info] Resolving org.scala-sbt#io;0.13.8 ...
[info] Resolving org.scala-sbt#control;0.13.8 ...
[info] Resolving org.scala-sbt#completion;0.13.8 ...
[info] Resolving org.scala-sbt#collections;0.13.8 ...
[info] Resolving jline#jline;2.11 ...
[info] Resolving org.scala-sbt#api;0.13.8 ...
[info] Resolving org.scala-sbt#compiler-integration;0.13.8 ...
[info] Resolving org.scala-sbt#incremental-compiler;0.13.8 ...
[info] Resolving org.scala-sbt#logging;0.13.8 ...
[info] Resolving org.scala-sbt#process;0.13.8 ...
[info] Resolving org.scala-sbt#relation;0.13.8 ...
[info] Resolving org.scala-sbt#compile;0.13.8 ...
[info] Resolving org.scala-sbt#classfile;0.13.8 ...
[info] Resolving org.scala-sbt#persist;0.13.8 ...
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.8 ...
[info] Resolving org.scala-sbt#ivy;0.13.8 ...
[info] Resolving org.scala-sbt#cross;0.13.8 ...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-fccfbd44c9f64523b61398a0155784dcbaeae28f ...
[info] Resolving com.jcraft#jsch;0.1.46 ...
[info] Resolving org.scala-sbt#serialization_2.10;0.1.1 ...
[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.0 ...
[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving org.scala-sbt#run;0.13.8 ...
[info] Resolving org.scala-sbt#task-system;0.13.8 ...
[info] Resolving org.scala-sbt#tasks;0.13.8 ...
[info] Resolving org.scala-sbt#tracking;0.13.8 ...
[info] Resolving org.scala-sbt#cache;0.13.8 ...
[info] Resolving org.scala-sbt#testing;0.13.8 ...
[info] Resolving org.scala-sbt#test-agent;0.13.8 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving org.scala-sbt#main-settings;0.13.8 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.8 ...
[info] Resolving org.scala-sbt#command;0.13.8 ...
[info] Resolving org.scala-sbt#logic;0.13.8 ...
[info] Resolving org.scala-sbt#compiler-interface;0.13.8 ...
[info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.8 ...
[info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.8 ...
[info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.8 ...
[info] Resolving org.scala-lang#jline;2.10.4 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to ensime_update_ (in build file:/C:/Users/Omid/.atom/packages/Ensime/ensime_update_/)
[info] Updating {file:/C:/Users/Omid/.atom/packages/Ensime/ensime_update_/}ensime_update_...
[info] Resolving org.scala-lang#scala-compiler;2.11.4 ...
[info] Resolving org.scala-lang#scala-library;2.11.4 ...
[info] Resolving org.scala-lang#scala-reflect;2.11.4 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.2 ...
[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.11;1.0.2 ...
[info] Resolving org.ensime#ensime_2.11;0.9.10-SNAPSHOT ...
[info] Resolving org.ensime#ensime_2.11;0.9.10-SNAPSHOT ...
[info] Resolving org.ensime#server_2.11;0.9.10-SNAPSHOT ... [info] Resolving org.ensime#server_2.11;0.9.10-SNAPSHOT ...
[info] Resolving org.ensime#core_2.11;0.9.10-SNAPSHOT ...
[info] Resolving org.ensime#core_2.11;0.9.10-SNAPSHOT ...
[info] Resolving org.ensime#api_2.11;0.9.10-SNAPSHOT ... [info] Resolving org.ensime#api_2.11;0.9.10-SNAPSHOT ...
[info] Resolving org.scalariform#scalariform_2.11;0.1.6 ...
[info] Resolving com.github.stacycurl#pimpathon-core_2.11;1.5.0 ...
[info] Resolving org.ensime#sexpress_2.11;0.9.10-SNAPSHOT ... [info] Resolving org.ensime#sexpress_2.11;0.9.10-SNAPSHOT ...
[info] Resolving com.chuusai#shapeless_2.11;2.2.3 ...
[info] Resolving org.parboiled#parboiled-scala_2.11;1.1.7 ...
[info] Resolving org.parboiled#parboiled-core;1.1.7 ...
[info] Resolving com.h2database#h2;1.4.187 ...
[info] Resolving com.typesafe.slick#slick_2.11;2.1.0 ...
[info] Resolving org.slf4j#slf4j-api;1.6.4 ...
[info] Resolving com.typesafe#config;1.2.1 ...
[info] Resolving com.jolbox#bonecp;0.8.0.RELEASE ...
[info] Resolving com.google.guava#guava;15.0 ...
[info] Resolving org.slf4j#slf4j-api;1.7.2 ...
[info] Resolving com.google.guava#guava;18.0 ...
[info] Resolving org.apache.commons#commons-vfs2;2.0 ...
[info] Resolving commons-logging#commons-logging;1.1.1 ...
[info] Resolving org.apache.maven.scm#maven-scm-api;1.4 ...
[info] Resolving org.codehaus.plexus#plexus-utils;1.5.6 ...
[info] Resolving org.apache.maven.scm#maven-scm-provider-svnexe;1.4 ...
[info] Resolving org.apache.maven.scm#maven-scm-provider-svn-commons;1.4 ...
[info] Resolving regexp#regexp;1.3 ...
[info] Resolving org.apache.lucene#lucene-core;4.7.2 ...
[info] Resolving org.apache.lucene#lucene-analyzers-common;4.7.2 ...
[info] Resolving org.ow2.asm#asm-commons;5.0.4 ...
[info] Resolving org.ow2.asm#asm-tree;5.0.4 ...
[info] Resolving org.ow2.asm#asm;5.0.4 ...
[info] Resolving org.ow2.asm#asm-util;5.0.4 ...
[info] Resolving com.typesafe.akka#akka-actor_2.11;2.3.11 ...
[info] Resolving com.typesafe.akka#akka-slf4j_2.11;2.3.11 ...
[info] Resolving org.slf4j#slf4j-api;1.7.5 ...
[info] Resolving org.scala-refactoring#org.scala-refactoring.library_2.11;0.6.2 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.4 ...
[info] Resolving commons-lang#commons-lang;2.6 ...
[info] Resolving ch.qos.logback#logback-classic;1.1.3 ...
[info] Resolving ch.qos.logback#logback-core;1.1.3 ...
[info] Resolving org.slf4j#slf4j-api;1.7.7 ...
[info] Resolving org.slf4j#jul-to-slf4j;1.7.12 ...
[info] Resolving org.slf4j#slf4j-api;1.7.12 ...
[info] Resolving org.slf4j#jcl-over-slf4j;1.7.12 ...
[info] Resolving org.ensime#swank_2.11;0.9.10-SNAPSHOT ...
[info] Resolving org.ensime#swank_2.11;0.9.10-SNAPSHOT ...
[info] Resolving org.ensime#jerk_2.11;0.9.10-SNAPSHOT ...
[info] Resolving org.ensime#jerk_2.11;0.9.10-SNAPSHOT ...
[info] Resolving org.ensime#spray-json-shapeless_2.11;0.9.10-SNAPSHOT ...
[info] Resolving org.ensime#spray-json-shapeless_2.11;0.9.10-SNAPSHOT ...
[info] Resolving io.spray#spray-json_2.11;1.3.2 ...
[info] Resolving io.spray#spray-can_2.11;1.3.3 ...
[info] Resolving io.spray#spray-io_2.11;1.3.3 ...
[info] Resolving io.spray#spray-util_2.11;1.3.3 ...
[info] Resolving io.spray#spray-http_2.11;1.3.3 ...
[info] Resolving org.scala-lang#scalap;2.11.4 ...
[info] Resolving jline#jline;2.12 ...
[info] Done updating.
[success] Total time: 18 s, completed Jun 26, 2015 2:55:51 PM
[success] Total time: 0 s, completed Jun 26, 2015 2:55:51 PM
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Ensime
```

**Comment by omidb** [comment]
server log:
```scala
14:55:54.471 INFO  None a.e.s.Slf4jLogger - Slf4jLogger started
14:55:54.480 DEBUG EventStream(akka://ENSIME) a.e.EventStream - logger log1-Slf4jLogger started
14:55:54.484 DEBUG EventStream(akka://ENSIME) a.e.EventStream - Default Loggers started
14:55:54.484 INFO  None o.e.s.Server - ENSIME Server on 127.0.0.1:58062
14:55:54.486 INFO  None o.e.s.Server - Environment:
  OS : Windows 8.1
  Java : Java HotSpot(TM) 64-Bit Server VM 25.25-b02, Java(TM) SE Runtime Environment 1.8.0_25-b18
  Scala : version 2.11.4
  Ensime : 0.9.10-SNAPSHOT
14:55:54.486 INFO  None o.e.s.Server - creating portfile E:\workspace\tut\testEnsime\.ensime_cache\port
14:55:54.896 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "C:\Users\Omid\AppData\Local\Temp\vfs_cache" as temporary files store.
14:55:55.421 DEBUG akka://ENSIME/user/$a/1 o.e.s.RequestHandler - ConnectionInfoReq
14:55:56.024 INFO  None o.e.i.DatabaseService - creating the search database
14:55:56.341 WARN  None c.j.b.BoneCPConfig - JDBC username was not set in config!
14:55:56.341 WARN  None c.j.b.BoneCPConfig - JDBC password was not set in config!
14:55:56.369 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Successfully bound to /127.0.0.1:58069
14:55:56.375 INFO  akka://ENSIME/user/IO-HTTP/listener-0 s.c.s.HttpListener - Bound to localhost/127.0.0.1:0
14:55:56.376 DEBUG akka://ENSIME/user/$a/docs o.e.s.DocServer - received handled message Bound(/127.0.0.1:58069)
14:55:57.044 INFO  None o.e.i.SearchService - removing 0 stale files from the index
14:55:57.060 INFO  None o.e.i.ClassfileWatcher - Setting up new file watchers
14:55:57.091 DEBUG akka://ENSIME/user/$a/project o.e.c.Project - received handled message ConnectionInfoReq
14:55:57.102 ERROR ActorSystem(ENSIME) a.a.ActorSystemImpl - Uncaught fatal error from thread [ENSIME-akka.actor.default-dispatcher-9] shutting down ActorSystem [ENSIME]
java.lang.NoClassDefFoundError: scala/tools/nsc/interactive/CompilerControl
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_25]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_25]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_25]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455) ~[na:1.8.0_25]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367) ~[na:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_25]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_25]
	at org.ensime.core.Project$$anonfun$preStart$2.apply(Project.scala:69) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Project$$anonfun$preStart$2.apply(Project.scala:69) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.TypedCreatorFunctionConsumer.produce(Props.scala:343) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.Props.newActor(Props.scala:252) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.newActor(ActorCell.scala:552) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:578) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:219) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.4.jar:na]
Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.interactive.CompilerControl
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[na:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_25]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_25]
	... 27 common frames omitted
14:55:57.103 DEBUG akka://ENSIME/user/$a/1 o.e.s.RequestHandler - received handled message ConnectionInfo(None,EnsimeImplementation(ENSIME),0.8.16) in state receive
14:55:57.114 ERROR ActorSystem(ENSIME) a.a.ActorSystemImpl - Uncaught fatal error from thread [ENSIME-akka.actor.default-dispatcher-2] shutting down ActorSystem [ENSIME]
java.lang.NoClassDefFoundError: com/sun/jdi/VMDisconnectedException
	at org.ensime.core.Project$$anonfun$preStart$3.apply(Project.scala:70) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Project$$anonfun$preStart$3.apply(Project.scala:70) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.TypedCreatorFunctionConsumer.produce(Props.scala:343) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.Props.newActor(Props.scala:252) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.newActor(ActorCell.scala:552) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:578) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:219) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.4.jar:na]
Caused by: java.lang.ClassNotFoundException: com.sun.jdi.VMDisconnectedException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[na:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_25]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_25]
	... 15 common frames omitted
14:55:57.122 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.SelectionHandler - Monitored actor [Actor[akka://ENSIME/user/IO-HTTP/listener-0#1163354542]] terminated
14:55:57.123 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Closing serverSocketChannel after being stopped
14:55:57.149 INFO  None c.j.b.BoneCP - Shutting down connection pool...
14:55:57.163 INFO  None c.j.b.BoneCP - Connection pool has been shutdown.
14:55:57.166 ERROR akka://ENSIME/user/$a o.e.s.SocketHandler - Error in socket reader: 
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_25]
	at java.net.SocketInputStream.read(SocketInputStream.java:150) ~[na:1.8.0_25]
	at java.net.SocketInputStream.read(SocketInputStream.java:121) ~[na:1.8.0_25]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284) ~[na:1.8.0_25]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_25]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[na:1.8.0_25]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[na:1.8.0_25]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[na:1.8.0_25]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.8.0_25]
	at org.ensime.jerk.JerkProtocol.fillArray$1(JerkProtocol.scala:47) ~[jerk_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.jerk.JerkProtocol.readJson(JerkProtocol.scala:54) ~[jerk_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.jerk.JerkProtocol.read(JerkProtocol.scala:18) ~[jerk_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.SocketHandler$$anon$2.run(Server.scala:176) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
14:55:57.167 DEBUG EventStream a.e.EventStream - shutting down: StandardOutLogger started

```

**Comment by fommil** [comment]
ENSIME doesn't generate any class files, so it must be another tool that's doing this. Perhaps a wonky sbt setup?

**Comment by fommil** [comment]
ok, well that looks like the java home is a JRE and not a JDK.

**Comment by fommil** [comment]
or, maybe your atom ensime-server start script doesn't work for Windows? `tools.jar` needs to be added. I think this is a client side thing so I'll pong it back at the previous ticket :stuck_out_tongue:

**Comment by omidb** [comment]
@fommil changing it to JRE doesn't solve it, where/what us `tools.jar` ?

**Comment by fommil** [comment]
no, you **need** a JDK, not a JRE. There should be a `lib/tools.jar` in your JDK and the atom launch script should be making sure that it is added to the classpath when ensime starts up. I'm guessing that is broken in Windows.
