### ISSUE TITLE
Timeout in debugmanager

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-server#1047]
```
18:36:06.090 [default-akka.actor.default-dispatcher-28] INFO  org.ensime.core.DebugManager - DebugManager.callMethod(obj = instance of com.typesafe.config.impl.SimpleConfig(id=1336) of type class com.typesafe.config.impl.SimpleConfig (loaded by instance of sun.misc.Launcher$AppClassLoader(id=1337)), name = toString, signature = ()Ljava/lang/String;, args = []
18:36:06.099 [default-akka.actor.default-dispatcher-28] INFO  org.ensime.core.DebugManager - Invoking: com.typesafe.config.impl.SimpleConfig.toString()
18:36:36.077 [default-akka.swank-dispatcher-47] ERROR o.e.s.protocol.swank.SwankProtocol - Exception whilst handling rpc Futures timed out after [30 seconds]
java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) ~[scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223) ~[scala-library.jar:na]
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107) ~[scala-library.jar:na]
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53) ~[scala-library.jar:na]
	at scala.concurrent.Await$.result(package.scala:107) ~[scala-library.jar:na]
	at org.ensime.core.ProjectEnsimeApiImpl$class.callRPC(ProjectEnsimeApiImpl.scala:27) ~[ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Project.callRPC(Project.scala:57) ~[ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.ProjectEnsimeApiImpl$class.rpcDebugToString(ProjectEnsimeApiImpl.scala:135) ~[ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Project.rpcDebugToString(Project.scala:57) ~[ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocol.org$ensime$server$protocol$swank$SwankProtocol$$handleRPCRequest(SwankProtocol.scala:1624) ~[ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocol$$anonfun$handleEmacsRex$1.apply$mcV$sp(SwankProtocol.scala:122) [ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocol$$anonfun$handleEmacsRex$1.apply(SwankProtocol.scala:119) [ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocol$$anonfun$handleEmacsRex$1.apply(SwankProtocol.scala:119) [ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [akka-actor_2.10-2.3.8.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45-internal]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45-internal]
18:36:36.077 [default-akka.actor.default-dispatcher-28] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:abort 201 "Futures timed out after [30 seconds]") 54)
```

This is while the debugger is stopped at a breakpoint.

**Comment by rorygraves** [comment]
@greenrd Sorry, missed this issue.
My guess is that something within the debugging code is failing to send any response to the requestor - we have a default operation timeout of 30 seconds on everything to try to ensure the gui is responsive.

The debugger is the part of ensime requiring the most love and it is on my list to work on when I have free cycles.  
If this is repeatable I would typically run the server up separately so I can add info onto the call and see whether its exceptioning/blocking or simply not returning a value.  

Do any other debug calls function after you see this?

Cheers

Rory

**Comment by rorygraves** [comment]
@greenrd - tweaking the DebugManager to be less susceptible to this - PR shortly.

**Comment by fommil** [comment]
can you `ensime-update` (in 10 mins) and try this again? Raise a ticket if it still happens.
