### ISSUE TITLE
2.10 OffsetPosition.start

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1083]
Happens a lot in 2.10 code.

I think fundamentally we're going to have to ban use of `.start` and `.end` because it breaks in 2.10, and only use the `endOrCursor` variants.

```
11:49:21.988 WARN  None o.e.u.PresentationReporter - Unsupported operation during reporting
java.lang.UnsupportedOperationException: Position.start on class scala.reflect.internal.util.OffsetPosition
	at scala.reflect.internal.util.Position.start(Position.scala:114) ~[scala-reflect-2.10.5.jar:na]
	at org.ensime.util.PresentationReporter.info0(Reporter.scala:44) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
```

**Comment by fommil** [comment]
(if it was possible to override the `.start` and `.end` methods with a pimp in 2.10 that'd fix this)
