### ISSUE TITLE
ensime server crashes with NoSuchMethodError soon after starting

### ISSUE THREAD

**Issue by KeenS** [ensime/ensime-server#1087]
When I start ensime from Emacs with `M-x ensime`, I get "Server connection closed unexpectedly: connection broken by remote peer" and `*inferior-ensime-server-project-name*` declaims that

```
Starting ENSIME server: /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -classpath /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/lib/tools.jar:/Users/a13987/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.10.2.jar:/Users/a13987/.ivy2/cache/org.ensime/ensime_2.10/jars/ensime_2.10-0.9.10-SNAPSHOT.jar:/Users/a13987/.ivy2/cache/org.ensime/server_2.10/jars/server_2.10-0.9.10-SNAPSHOT.jar:/Users/a13987/.ivy2/cache/org.ensime/core_2.10/jars/core_2.10-0.9.10-SNAPSHOT.jar:/Users/a13987/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.10.2.jar:/Users/a13987/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.10.2.jar:/Users/a13987/.ivy2/cache/org.ensime/api_2.10/jars/api_2.10-0.9.10-SNAPSHOT.jar:/Users/a13987/.ivy2/cache/org.scalariform/scalariform_2.10/jars/scalariform_2.10-0.1.7.jar:/Users/a13987/.ivy2/cache/com.github.stacycurl/pimpathon-core_2.10/jars/pimpathon-core_2.10-1.5.0.jar:/Users/a13987/.ivy2/cache/org.ensime/sexpress_2.10/jars/sexpress_2.10-0.9.10-SNAPSHOT.jar:/Users/a13987/.ivy2/cache/org.parboiled/parboiled-scala_2.10/jars/parboiled-scala_2.10-1.1.7.jar:/Users/a13987/.ivy2/cache/org.parboiled/parboiled-core/jars/parboiled-core-1.1.7.jar:/Users/a13987/.ivy2/cache/com.chuusai/shapeless_2.10/bundles/shapeless_2.10-2.2.5.jar:/Users/a13987/.ivy2/cache/org.scalamacros/quasiquotes_2.10/jars/quasiquotes_2.10-2.0.0.jar:/Users/a13987/.ivy2/cache/com.h2database/h2/jars/h2-1.4.188.jar:/Users/a13987/.ivy2/cache/com.typesafe.slick/slick_2.10/bundles/slick_2.10-2.1.0.jar:/Users/a13987/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar:/Users/a13987/.ivy2/cache/com.jolbox/bonecp/bundles/bonecp-0.8.0.RELEASE.jar:/Users/a13987/.ivy2/cache/com.google.guava/guava/bundles/guava-15.0.jar:/Users/a13987/.ivy2/cache/org.apache.commons/commons-vfs2/jars/commons-vfs2-2.0.jar:/Users/a13987/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.1.jar:/Users/a13987/.ivy2/cache/org.apache.maven.scm/maven-scm-api/jars/maven-scm-api-1.4.jar:/Users/a13987/.ivy2/cache/org.codehaus.plexus/plexus-utils/jars/plexus-utils-1.5.6.jar:/Users/a13987/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svnexe/jars/maven-scm-provider-svnexe-1.4.jar:/Users/a13987/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svn-commons/jars/maven-scm-provider-svn-commons-1.4.jar:/Users/a13987/.ivy2/cache/regexp/regexp/jars/regexp-1.3.jar:/Users/a13987/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-4.7.2.jar:/Users/a13987/.ivy2/cache/org.apache.lucene/lucene-analyzers-common/jars/lucene-analyzers-common-4.7.2.jar:/Users/a13987/.ivy2/cache/org.ow2.asm/asm-commons/jars/asm-commons-5.0.4.jar:/Users/a13987/.ivy2/cache/org.ow2.asm/asm-tree/jars/asm-tree-5.0.4.jar:/Users/a13987/.ivy2/cache/org.ow2.asm/asm/jars/asm-5.0.4.jar:/Users/a13987/.ivy2/cache/org.ow2.asm/asm-util/jars/asm-util-5.0.4.jar:/Users/a13987/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.10.2.jar:/Users/a13987/.ivy2/cache/com.typesafe.akka/akka-actor_2.10/jars/akka-actor_2.10-2.3.12.jar:/Users/a13987/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.10/jars/akka-slf4j_2.10-2.3.12.jar:/Users/a13987/.ivy2/cache/org.scala-refactoring/org.scala-refactoring.library_2.10/jars/org.scala-refactoring.library_2.10-0.6.2.jar:/Users/a13987/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.6.jar:/Users/a13987/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.3.jar:/Users/a13987/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.3.jar:/Users/a13987/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.12.jar:/Users/a13987/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.12.jar:/Users/a13987/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.12.jar:/Users/a13987/.ivy2/cache/org.ensime/swank_2.10/jars/swank_2.10-0.9.10-SNAPSHOT.jar:/Users/a13987/.ivy2/cache/org.ensime/jerk_2.10/jars/jerk_2.10-0.9.10-SNAPSHOT.jar:/Users/a13987/.ivy2/cache/com.github.fommil/spray-json-shapeless_2.10/jars/spray-json-shapeless_2.10-1.1.0.jar:/Users/a13987/.ivy2/cache/io.spray/spray-json_2.10/bundles/spray-json_2.10-1.3.2.jar:/Users/a13987/.ivy2/cache/com.typesafe.akka/akka-stream-experimental_2.10/jars/akka-stream-experimental_2.10-1.0.jar:/Users/a13987/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.jar:/Users/a13987/.ivy2/cache/com.typesafe.akka/akka-http-core-experimental_2.10/jars/akka-http-core-experimental_2.10-1.0.jar:/Users/a13987/.ivy2/cache/com.typesafe.akka/akka-parsing-experimental_2.10/jars/akka-parsing-experimental_2.10-1.0.jar:/Users/a13987/.ivy2/cache/com.typesafe.akka/akka-http-experimental_2.10/jars/akka-http-experimental_2.10-1.0.jar:/Users/a13987/.ivy2/cache/com.typesafe.akka/akka-http-spray-json-experimental_2.10/jars/akka-http-spray-json-experimental_2.10-1.0.jar:/Users/a13987/.ivy2/cache/com.typesafe.akka/akka-http-xml-experimental_2.10/jars/akka-http-xml-experimental_2.10-1.0.jar -Densime.config=/Users/a13987/caamoad/genius/batch/deliver-list/.ensime org.ensime.server.Server
11:15:25.525 INFO  None a.e.s.Slf4jLogger - Slf4jLogger started
11:15:25.538 DEBUG EventStream(akka://ENSIME) a.e.EventStream - logger log1-Slf4jLogger started
11:15:25.544 DEBUG EventStream(akka://ENSIME) a.e.EventStream - Default Loggers started
11:15:25.616 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "/var/folders/mz/_jv_0yb53w72jx50jlz2wm_4lx_7d8/T/vfs_cache" as temporary files store.
11:15:25.694 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Successfully bound to /127.0.0.1:56600
11:15:25.698 INFO  None o.e.s.PortUtil$ - creating portfile /Users/a13987/caamoad/genius/batch/deliver-list/.ensime_cache.d/port
11:15:25.700 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Bound server on port 56600
11:15:25.995 INFO  None o.e.i.DatabaseService - creating the search database
11:15:26.392 WARN  None c.j.b.BoneCPConfig - JDBC username was not set in config!
11:15:26.393 WARN  None c.j.b.BoneCPConfig - JDBC password was not set in config!
11:15:26.485 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - Environment:
  OS : Mac OS X
  Java : Java HotSpot(TM) 64-Bit Server VM 24.79-b02, Java(TM) SE Runtime Environment 1.7.0_79-b15
  Scala : version 2.10.2
  Ensime : 0.9.10-SNAPSHOT
11:15:26.488 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - Successfully bound to /127.0.0.1:56601
11:15:26.507 INFO  None o.e.s.PortUtil$ - creating portfile /Users/a13987/caamoad/genius/batch/deliver-list/.ensime_cache.d/http
11:15:26.508 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - ENSIME HTTP on /127.0.0.1
11:15:26.929 INFO  None o.e.i.SearchService - removing 0 stale files from the index
11:15:27.058 INFO  None o.e.i.ClassfileWatcher - Setting up new file watchers
11:15:29.137 DEBUG akka://ENSIME/user/ensime-main/project/analyzer o.e.c.Analyzer - received handled message FullTypeCheckCompleteEvent in state startup
11:15:30.051 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - New connection accepted
11:15:30.069 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Connection from localhost
11:15:30.090 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Client connected - active clients now: 1
11:15:30.221 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/1 o.e.s.RequestHandler - ConnectionInfoReq
11:15:30.223 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message ConnectionInfoReq
11:15:30.230 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/1 o.e.s.RequestHandler - received handled message ConnectionInfo(None,EnsimeImplementation(ENSIME),0.8.17) in state receive
11:15:31.620 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/2 o.e.s.RequestHandler - SymbolDesignationsReq(/Users/a13987/caamoad/genius/batch/deliver-list/src/test/scala/ultima/batch/deliverlist/model/DeliverListLoaderIntegrationSpec.scala,0,10412,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, FunctionCallSymbol, Operator
11:15:31.621 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message SymbolDesignationsReq(/Users/a13987/caamoad/genius/batch/deliver-list/src/test/scala/ultima/batch/deliverlist/model/DeliverListLoaderIntegrationSpec.scala,0,10412,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, Fun
11:15:31.622 DEBUG akka://ENSIME/user/ensime-main/project/analyzer o.e.c.Analyzer - received handled message SymbolDesignationsReq(/Users/a13987/caamoad/genius/batch/deliver-list/src/test/scala/ultima/batch/deliverlist/model/DeliverListLoaderIntegrationSpec.scala,0,10412,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, Fun
10:43:26.722 ERROR ActorSystem(ENSIME) a.a.ActorSystemImpl - Uncaught fatal error from thread [ENSIME-akka.actor.default-dispatcher-6] shutting down ActorSystem [ENSIME]
java.lang.NoSuchMethodError: org.ensime.core.RichPresentationCompiler.askLoadedTyped(Lscala/reflect/internal/util/SourceFile;ZLscala/tools/nsc/interactive/Response;)V
	at org.ensime.core.RichCompilerControl$class.askLoadedTyped(RichPresentationCompiler.scala:113) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.RichPresentationCompiler.askLoadedTyped(RichPresentationCompiler.scala:197) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:240) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:152) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33) ~[scala-library-2.10.2.jar:na]
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33) ~[scala-library-2.10.2.jar:na]
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25) ~[scala-library-2.10.2.jar:na]
	at org.ensime.core.Analyzer$$anonfun$ready$1.applyOrElse(Analyzer.scala:149) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33) ~[scala-library-2.10.2.jar:na]
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33) ~[scala-library-2.10.2.jar:na]
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25) ~[scala-library-2.10.2.jar:na]
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:62) ~[akka-actor_2.10-2.3.12.jar:na]
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:50) ~[akka-actor_2.10-2.3.12.jar:na]
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118) ~[scala-library-2.10.2.jar:na]
	at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50) ~[akka-actor_2.10-2.3.12.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.10-2.3.12.jar:na]
	at org.ensime.core.Analyzer.aroundReceive(Analyzer.scala:41) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.10-2.3.12.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.10-2.3.12.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.10-2.3.12.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.10-2.3.12.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.10-2.3.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.10.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.10.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.10.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.10.2.jar:na]
```

```
$ uname -a
﻿﻿﻿Darwin PC-10025 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

**Comment by fommil** [comment]
This is a dupe. I'm on a phone now and can't navigate easily but have a look under the 1.0 milestone. Upgrade Scala.

**Comment by KeenS** [comment]
I see. Then please mention least scala version in README

**Comment by fommil** [comment]
Feel free to update https://github.com/ensime/ensime-emacs/wiki/Quick-Start-Guide or a PR to support the oldest Scala on each minor release (including updating the build matrix).

**Comment by fommil** [comment]
@KeenS the change you made wasn't quite right, we do still support scala 2.10. I've reverted and updated your suggested change.

**Comment by KeenS** [comment]
@fommil Thank you for your kind support.l

**Comment by Hiroyuki-Nagata** [comment]
I reproduced this issue in my environment. Error log is same as this.
Could anyone tell me why this error occurred ?
Any suggestion for resolving this problem ?
