### ISSUE TITLE
org.apache.commons.vfs2.FileSystemException: Invalid relative file name.

### ISSUE THREAD

**Issue by gregghz** [ensime/ensime-server#1096]
https://github.com/lucidsoftware/relate

I've run `gen-ensime` on this project, but from within emacs when I `M-x ensime`, I get the following error in the `*inferior-ensime-server-root*` buffer:

```
09:50:30.819 ERROR akka://ENSIME/user/ensime-main/project a.a.OneForOneStrategy - exception during creation
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:166) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:596) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:219) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.4.jar:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_45-internal]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_45-internal]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_45-internal]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_45-internal]
	at akka.util.Reflect$.instantiate(Reflect.scala:66) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.ArgsReflectConstructor.produce(Props.scala:352) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.Props.newActor(Props.scala:252) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.ActorCell.newActor(ActorCell.scala:552) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:578) ~[akka-actor_2.11-2.3.12.jar:na]
	... 9 common frames omitted
Caused by: org.apache.commons.vfs2.FileSystemException: Invalid relative file name.
	at org.apache.commons.vfs2.provider.UriParser.normalisePath(UriParser.java:166) ~[commons-vfs2-2.0.jar:2.0]
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveName(DefaultFileSystemManager.java:784) ~[commons-vfs2-2.0.jar:2.0]
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveName(DefaultFileSystemManager.java:738) ~[commons-vfs2-2.0.jar:2.0]
	at org.apache.commons.vfs2.provider.zip.ZipFileSystem.init(ZipFileSystem.java:87) ~[commons-vfs2-2.0.jar:2.0]
	at org.apache.commons.vfs2.provider.AbstractVfsContainer.addComponent(AbstractVfsContainer.java:52) ~[commons-vfs2-2.0.jar:2.0]
	at org.apache.commons.vfs2.provider.AbstractFileProvider.addFileSystem(AbstractFileProvider.java:101) ~[commons-vfs2-2.0.jar:2.0]
	at org.apache.commons.vfs2.provider.AbstractLayeredFileProvider.createFileSystem(AbstractLayeredFileProvider.java:90) ~[commons-vfs2-2.0.jar:2.0]
	at org.apache.commons.vfs2.provider.AbstractLayeredFileProvider.findFile(AbstractLayeredFileProvider.java:63) ~[commons-vfs2-2.0.jar:2.0]
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:693) ~[commons-vfs2-2.0.jar:2.0]
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:649) ~[commons-vfs2-2.0.jar:2.0]
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:605) ~[commons-vfs2-2.0.jar:2.0]
	at org.ensime.indexer.EnsimeVFS.vjar(EnsimeVFS.scala:31) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.indexer.SourceResolver$$anonfun$4.apply(SourceResolver.scala:58) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.indexer.SourceResolver$$anonfun$4.apply(SourceResolver.scala:56) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.4.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.4.jar:na]
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322) ~[scala-library-2.11.4.jar:na]
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978) ~[scala-library-2.11.4.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[scala-library-2.11.4.jar:na]
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47) ~[scala-library-2.11.4.jar:na]
	at scala.collection.SetLike$class.map(SetLike.scala:92) ~[scala-library-2.11.4.jar:na]
	at scala.collection.AbstractSet.map(Set.scala:47) ~[scala-library-2.11.4.jar:na]
	at org.ensime.indexer.SourceResolver.<init>(SourceResolver.scala:56) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Project.<init>(Project.scala:35) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	... 18 common frames omitted
```

Here's my `.ensime` file:

```
(
 :root-dir "/home/gregg/workspace/relate"
 :cache-dir "/home/gregg/workspace/relate/.ensime_cache"
 :name "root"
 :java-home "/usr/lib/jvm/java-8-openjdk-amd64"
 :java-flags ("-Xss2m" "-Xms1024m" "-Xmx1024m" "-XX:ReservedCodeCacheSize=128m" "-XX:MaxMetaspaceSize=256m")
 :reference-source-roots ("/usr/lib/jvm/java-8-openjdk-amd64/src.zip")
 :scala-version "2.11.4"
 :compiler-args ("-deprecation" "-feature" "-language:higherKinds" "-Xlint" "-Yinline-warnings" "-Yno-adapted-args" "-Ywarn-dead-code" "-Ywarn-numeric-widen" "-Xfuture" "-Ywarn-unused-import")
 
 :subprojects ((
   :name "root"
   :source-roots ("/home/gregg/workspace/relate/src/test/scala" "/home/gregg/workspace/relate/src/it/scala" "/home/gregg/workspace/relate/src/main/scala" "/home/gregg/workspace/relate/src/test/java" "/home/gregg/workspace/relate/src/it/java" "/home/gregg/workspace/relate/src/main/java")
   :targets ("/home/gregg/workspace/relate/target/scala-2.11/classes")
   :test-targets ("/home/gregg/workspace/relate/target/scala-2.11/test-classes" "/home/gregg/workspace/relate/target/scala-2.11/it-classes")
   :depends-on-modules nil
   :compile-deps ("/home/gregg/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.4.jar")
   :runtime-deps nil
   :test-deps ("/home/gregg/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.0.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/fastparse-utils_2.11/jars/fastparse-utils_2.11-0.2.1.jar" "/home/gregg/.ivy2/cache/org.spire-math/jawn-parser_2.11/jars/jawn-parser_2.11-0.7.0.jar" "/home/gregg/.ivy2/cache/org.specs2/specs2_2.11/jars/specs2_2.11-2.3.12.jar" "/home/gregg/.ivy2/cache/org.scalaz/scalaz-concurrent_2.11/bundles/scalaz-concurrent_2.11-7.0.6.jar" "/home/gregg/.ivy2/cache/org.parboiled/parboiled-java/jars/parboiled-java-1.1.4.jar" "/home/gregg/.ivy2/cache/org.scalaz/scalaz-core_2.11/bundles/scalaz-core_2.11-7.0.6.jar" "/home/gregg/.ivy2/cache/org.mockito/mockito-core/jars/mockito-core-1.9.5.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/scalaparse_2.11/jars/scalaparse_2.11-0.2.1.jar" "/home/gregg/.ivy2/cache/org.objenesis/objenesis/jars/objenesis-1.0.jar" "/home/gregg/.ivy2/cache/mysql/mysql-connector-java/jars/mysql-connector-java-5.1.23.jar" "/home/gregg/.ivy2/cache/org.hamcrest/hamcrest-core/jars/hamcrest-core-1.3.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/ammonite-ops_2.11/jars/ammonite-ops_2.11-0.4.7.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/ammonite-repl_2.11.4/jars/ammonite-repl_2.11.4-0.4.7.jar" "/home/gregg/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.2.jar" "/home/gregg/.ivy2/cache/junit/junit/jars/junit-4.11.jar" "/home/gregg/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar" "/home/gregg/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.4.jar" "/home/gregg/.ivy2/cache/org.scalacheck/scalacheck_2.11/jars/scalacheck_2.11-1.11.3.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/ammonite-terminal_2.11/jars/ammonite-terminal_2.11-0.4.7.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/derive_2.11/jars/derive_2.11-0.3.6.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/pprint_2.11/jars/pprint_2.11-0.3.6.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/upickle_2.11/jars/upickle_2.11-0.3.6.jar" "/home/gregg/.ivy2/cache/org.ow2.asm/asm-util/jars/asm-util-4.1.jar" "/home/gregg/.ivy2/cache/org.ow2.asm/asm-analysis/jars/asm-analysis-4.1.jar" "/home/gregg/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar" "/home/gregg/.ivy2/cache/org.scalaz/scalaz-effect_2.11/bundles/scalaz-effect_2.11-7.0.6.jar" "/home/gregg/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.0.jar" "/home/gregg/.ivy2/cache/org.ow2.asm/asm-tree/jars/asm-tree-4.1.jar" "/home/gregg/.ivy2/cache/org.specs2/classycle/jars/classycle-1.4.3.jar" "/home/gregg/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.4.jar" "/home/gregg/.ivy2/cache/org.apache.ivy/ivy/jars/ivy-2.4.0.jar" "/home/gregg/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.2.jar" "/home/gregg/.ivy2/cache/com.github.scopt/scopt_2.11/jars/scopt_2.11-3.3.0.jar" "/home/gregg/.ivy2/cache/org.pegdown/pegdown/jars/pegdown-1.2.1.jar" "/home/gregg/.ivy2/cache/org.parboiled/parboiled-core/jars/parboiled-core-1.1.4.jar" "/home/gregg/.ivy2/cache/org.ow2.asm/asm/jars/asm-4.1.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/fastparse_2.11/jars/fastparse_2.11-0.2.1.jar" "/home/gregg/.ivy2/cache/jline/jline/jars/jline-2.12.jar" "/home/gregg/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.1.jar")
   :doc-jars ("/home/gregg/.ivy2/cache/org.hamcrest/hamcrest-core/docs/hamcrest-core-1.3-javadoc.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/fastparse_2.11/docs/fastparse_2.11-0.2.1-javadoc.jar" "/home/gregg/.ivy2/cache/org.apache.ivy/ivy/docs/ivy-2.4.0-javadoc.jar" "/home/gregg/.ivy2/cache/org.scala-sbt/test-interface/docs/test-interface-1.0-javadoc.jar" "/home/gregg/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/docs/scala-parser-combinators_2.11-1.0.2-javadoc.jar" "/home/gregg/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/docs/scala-parser-combinators_2.11-1.0.1-javadoc.jar" "/home/gregg/.ivy2/cache/org.scala-lang/scala-reflect/docs/scala-reflect-2.11.4-javadoc.jar" "/home/gregg/.ivy2/cache/org.ow2.asm/asm-analysis/docs/asm-analysis-4.1-javadoc.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/scalaparse_2.11/docs/scalaparse_2.11-0.2.1-javadoc.jar" "/home/gregg/.ivy2/cache/org.ow2.asm/asm/docs/asm-4.1-javadoc.jar" "/home/gregg/.ivy2/cache/org.scalacheck/scalacheck_2.11/docs/scalacheck_2.11-1.11.3-javadoc.jar" "/home/gregg/.ivy2/cache/org.ow2.asm/asm-util/docs/asm-util-4.1-javadoc.jar" "/home/gregg/.ivy2/cache/org.specs2/specs2_2.11/docs/specs2_2.11-2.3.12-javadoc.jar" "/home/gregg/.ivy2/cache/org.parboiled/parboiled-java/docs/parboiled-java-1.1.4-javadoc.jar" "/home/gregg/.ivy2/cache/org.ow2.asm/asm-tree/docs/asm-tree-4.1-javadoc.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/ammonite-ops_2.11/docs/ammonite-ops_2.11-0.4.7-javadoc.jar" "/home/gregg/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/docs/scala-xml_2.11-1.0.1-javadoc.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/fastparse-utils_2.11/docs/fastparse-utils_2.11-0.2.1-javadoc.jar" "/home/gregg/workspace/relate/target/scala-2.11/relate_2.11-1.12.0-SNAPSHOT-javadoc.jar" "/home/gregg/.ivy2/cache/com.github.scopt/scopt_2.11/docs/scopt_2.11-3.3.0-javadoc.jar" "/home/gregg/.ivy2/cache/org.scala-lang/scala-compiler/docs/scala-compiler-2.11.0-javadoc.jar" "/home/gregg/.ivy2/cache/org.scalaz/scalaz-effect_2.11/docs/scalaz-effect_2.11-7.0.6-javadoc.jar" "/home/gregg/.ivy2/cache/org.scala-lang/scala-compiler/docs/scala-compiler-2.11.4-javadoc.jar" "/home/gregg/.ivy2/cache/org.scala-lang/scala-library/docs/scala-library-2.11.4-javadoc.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/upickle_2.11/docs/upickle_2.11-0.3.6-javadoc.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/pprint_2.11/docs/pprint_2.11-0.3.6-javadoc.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/derive_2.11/docs/derive_2.11-0.3.6-javadoc.jar" "/home/gregg/.ivy2/cache/org.pegdown/pegdown/docs/pegdown-1.2.1-javadoc.jar" "/home/gregg/.ivy2/cache/org.objenesis/objenesis/docs/objenesis-1.0-javadoc.jar" "/home/gregg/.ivy2/cache/org.scala-lang/scala-reflect/docs/scala-reflect-2.11.0-javadoc.jar" "/home/gregg/.ivy2/cache/org.mockito/mockito-core/docs/mockito-core-1.9.5-javadoc.jar" "/home/gregg/.ivy2/cache/jline/jline/docs/jline-2.12-javadoc.jar" "/home/gregg/.ivy2/cache/org.specs2/classycle/docs/classycle-1.4.3-javadoc.jar" "/home/gregg/.ivy2/cache/junit/junit/docs/junit-4.11-javadoc.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/ammonite-terminal_2.11/docs/ammonite-terminal_2.11-0.4.7-javadoc.jar" "/home/gregg/.ivy2/cache/org.scalaz/scalaz-concurrent_2.11/docs/scalaz-concurrent_2.11-7.0.6-javadoc.jar" "/home/gregg/.ivy2/cache/org.scalaz/scalaz-core_2.11/docs/scalaz-core_2.11-7.0.6-javadoc.jar" "/home/gregg/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/docs/scala-xml_2.11-1.0.2-javadoc.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/ammonite-repl_2.11.4/docs/ammonite-repl_2.11.4-0.4.7-javadoc.jar" "/home/gregg/.ivy2/cache/org.spire-math/jawn-parser_2.11/docs/jawn-parser_2.11-0.7.0-javadoc.jar" "/home/gregg/.ivy2/cache/org.parboiled/parboiled-core/docs/parboiled-core-1.1.4-javadoc.jar")
   :reference-source-roots ("/home/gregg/.ivy2/cache/org.scala-lang/scala-compiler/srcs/scala-compiler-2.11.4-sources.jar" "/home/gregg/.ivy2/cache/org.parboiled/parboiled-core/srcs/parboiled-core-1.1.4-sources.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/upickle_2.11/srcs/upickle_2.11-0.3.6-sources.jar" "/home/gregg/.ivy2/cache/org.parboiled/parboiled-java/srcs/parboiled-java-1.1.4-sources.jar" "/home/gregg/.ivy2/cache/org.apache.ivy/ivy/srcs/ivy-2.4.0-sources.jar" "/home/gregg/.ivy2/cache/org.specs2/classycle/srcs/classycle-1.4.3-sources.jar" "/home/gregg/.ivy2/cache/org.pegdown/pegdown/srcs/pegdown-1.2.1-sources.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/fastparse_2.11/srcs/fastparse_2.11-0.2.1-sources.jar" "/home/gregg/.ivy2/cache/org.mockito/mockito-core/srcs/mockito-core-1.9.5-sources.jar" "/home/gregg/.ivy2/cache/org.ow2.asm/asm-analysis/srcs/asm-analysis-4.1-sources.jar" "/home/gregg/.ivy2/cache/org.scala-sbt/test-interface/srcs/test-interface-1.0-sources.jar" "/home/gregg/.ivy2/cache/org.scalaz/scalaz-concurrent_2.11/srcs/scalaz-concurrent_2.11-7.0.6-sources.jar" "/home/gregg/.ivy2/cache/org.ow2.asm/asm-util/srcs/asm-util-4.1-sources.jar" "/home/gregg/.ivy2/cache/org.scala-lang/scala-compiler/srcs/scala-compiler-2.11.0-sources.jar" "/home/gregg/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/srcs/scala-parser-combinators_2.11-1.0.1-sources.jar" "/home/gregg/.ivy2/cache/org.scalaz/scalaz-core_2.11/srcs/scalaz-core_2.11-7.0.6-sources.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/derive_2.11/srcs/derive_2.11-0.3.6-sources.jar" "/home/gregg/.ivy2/cache/junit/junit/srcs/junit-4.11-sources.jar" "/home/gregg/.ivy2/cache/org.ow2.asm/asm/srcs/asm-4.1-sources.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/fastparse-utils_2.11/srcs/fastparse-utils_2.11-0.2.1-sources.jar" "/home/gregg/.ivy2/cache/org.scalaz/scalaz-effect_2.11/srcs/scalaz-effect_2.11-7.0.6-sources.jar" "/home/gregg/.ivy2/cache/com.github.scopt/scopt_2.11/srcs/scopt_2.11-3.3.0-sources.jar" "/home/gregg/.ivy2/cache/org.objenesis/objenesis/srcs/objenesis-1.0-sources.jar" "/home/gregg/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/srcs/scala-parser-combinators_2.11-1.0.2-sources.jar" "/home/gregg/.ivy2/cache/jline/jline/srcs/jline-2.12-sources.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/scalaparse_2.11/srcs/scalaparse_2.11-0.2.1-sources.jar" "/home/gregg/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/srcs/scala-xml_2.11-1.0.1-sources.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/ammonite-repl_2.11.4/srcs/ammonite-repl_2.11.4-0.4.7-sources.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/ammonite-ops_2.11/srcs/ammonite-ops_2.11-0.4.7-sources.jar" "/home/gregg/.ivy2/cache/org.ow2.asm/asm-tree/srcs/asm-tree-4.1-sources.jar" "/home/gregg/.ivy2/cache/org.specs2/specs2_2.11/srcs/specs2_2.11-2.3.12-sources.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/ammonite-terminal_2.11/srcs/ammonite-terminal_2.11-0.4.7-sources.jar" "/home/gregg/.ivy2/cache/org.hamcrest/hamcrest-core/srcs/hamcrest-core-1.3-sources.jar" "/home/gregg/.ivy2/cache/org.scalacheck/scalacheck_2.11/srcs/scalacheck_2.11-1.11.3-sources.jar" "/home/gregg/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.11.4-sources.jar" "/home/gregg/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/srcs/scala-xml_2.11-1.0.2-sources.jar" "/home/gregg/.ivy2/cache/org.scala-lang/scala-reflect/srcs/scala-reflect-2.11.0-sources.jar" "/home/gregg/.ivy2/cache/org.spire-math/jawn-parser_2.11/srcs/jawn-parser_2.11-0.7.0-sources.jar" "/home/gregg/.ivy2/cache/com.lihaoyi/pprint_2.11/srcs/pprint_2.11-0.3.6-sources.jar" "/home/gregg/.ivy2/cache/org.scala-lang/scala-reflect/srcs/scala-reflect-2.11.4-sources.jar")))
)
```

Clearing both `.ensime` and `.ensime_cache` doesn't improve the situation.

I attempted to build/run my own ensime-server in an effort to get more debug info, but the instructions (from https://github.com/ensime/ensime-emacs/wiki/Quick-Start-Guide) on how to do so don't work for me. Specifically, `ensime/assembly` isn't an sbt task:

```
➜  ensime-server git:(master) sbt ++2.10.5 ensime/assembly
[info] Loading global plugins from /home/gregg/.sbt/0.13/plugins
[info] Updating {file:/home/gregg/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /home/gregg/workspace/ensime-server/project
[info] Updating {file:/home/gregg/workspace/ensime-server/project/}ensime-server-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* org.ensime:ensime-sbt:0.1.7 -> 0.2.0
[warn] Run 'evicted' to see detailed eviction warnings
[info] Set current project to ensime (in build file:/home/gregg/workspace/ensime-server/)
[info] Setting version to 2.10.5
[info] Reapplying settings...
[info] Set current project to ensime (in build file:/home/gregg/workspace/ensime-server/)
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: assembly
[error] ensime/assembly
[error]                ^
```

**Comment by fommil** [comment]
@cvogt recently did something in this area. Are you using ammonite by any chance? It exposes a bug in SBT.

**Comment by fommil** [comment]
BTW, don't worry about the assembly instructions I haven't merged that branch yet. Use my branch in PR.

**Comment by cvogt** [comment]
here is the related error message improvement for ensime server: https://github.com/ensime/ensime-server/pull/1092

and here is the fix for ammonite: https://github.com/lihaoyi/Ammonite/issues/227

the bug is really in ammonite, but sbt doesn't catch it, which can be considered a bug as well.

**Comment by gregghz** [comment]
yep, using Ammonite.

**Comment by cvogt** [comment]
@gregghz then switch to 0.4.6 or 0.4.8 once it is out. be aware that 0.4.6 has a limitation or bug if you will that throws a NoSuchDirectory exception when using rm in certain cases, so consider 0.4.5. With those ensime should work fine

**Comment by fommil** [comment]
@gregghz for now, if you want to run your own server, do an `sbt publishLocal`. This will change very soon... just need to get my PR to pass the tests!

**Comment by gregghz** [comment]
@cvogt I get this error now if I switch to ammonite 0.4.5:

```
Caused by: org.apache.commons.vfs2.FileSystemException: Unknown message with code "Invalid relative file name. in /home/gregg/.ivy2/cache/com.lihaoyi/ammonite-repl_2.10.5/srcs/ammonite-repl_2.10.5-0.4.5-sources.jar"
```
