### ISSUE TITLE
Server dies after hitting breakpoint in debugger

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-server#1099]
It's our old friend `com.sun.jdi.AbsentInformationException: null`

```
19:28:19.037 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/2145 o.e.s.RequestHandler - received handled message Some(SymbolInfo(headers,headers,Some(OffsetSourcePosition(/home/robin/git/foo/.ensime_cache/dep-src/source-jars/spray/http/HttpMessage.scala,2402)),BasicTypeInfo(List,16,Class,scala.collection.immutable.List,List(BasicTyp
19:28:19.038 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/2146 o.e.s.RequestHandler - DebugLocateNameReq(DebugThreadId(1355),headers)
19:28:19.038 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugLocateNameReq(DebugThreadId(1355),headers)
19:28:19.038 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugManager - received handled message DebugLocateNameReq(DebugThreadId(1355),headers)
19:28:19.039 ERROR akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugManager - Exception thrown whilst handling vm action
com.sun.jdi.AbsentInformationException: null
	at com.sun.tools.jdi.ConcreteMethodImpl.getVariables1(ConcreteMethodImpl.java:495) ~[tools.jar:na]
	at com.sun.tools.jdi.ConcreteMethodImpl.getVariables(ConcreteMethodImpl.java:540) ~[tools.jar:na]
	at com.sun.tools.jdi.ConcreteMethodImpl.variables(ConcreteMethodImpl.java:217) ~[tools.jar:na]
	at com.sun.tools.jdi.StackFrameImpl.createVisibleVariables(StackFrameImpl.java:159) ~[tools.jar:na]
	at com.sun.tools.jdi.StackFrameImpl.visibleVariables(StackFrameImpl.java:182) ~[tools.jar:na]
	at org.ensime.core.debug.VM.stackSlotForName(VM.scala:472) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.VM.locationForName(VM.scala:364) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$fromUser$1$$anonfun$applyOrElse$19.apply(DebugManager.scala:347) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$fromUser$1$$anonfun$applyOrElse$19.apply(DebugManager.scala:346) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$org$ensime$core$debug$DebugManager$$handleRPCWithVMAndThread$1$$anonfun$apply$4.apply(DebugManager.scala:141) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$org$ensime$core$debug$DebugManager$$handleRPCWithVMAndThread$1$$anonfun$apply$4.apply(DebugManager.scala:140) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
	at org.ensime.core.debug.DebugManager$$anonfun$org$ensime$core$debug$DebugManager$$handleRPCWithVMAndThread$1.apply(DebugManager.scala:140) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$org$ensime$core$debug$DebugManager$$handleRPCWithVMAndThread$1.apply(DebugManager.scala:139) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$liftedTree1$1$1.apply(DebugManager.scala:115) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$liftedTree1$1$1.apply(DebugManager.scala:114) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
	at org.ensime.core.debug.DebugManager.liftedTree1$1(DebugManager.scala:114) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager.withVM(DebugManager.scala:113) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager.org$ensime$core$debug$DebugManager$$handleRPCWithVMAndThread(DebugManager.scala:139) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$fromUser$1.applyOrElse(DebugManager.scala:345) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
	at org.ensime.core.debug.DebugManager$$anonfun$fromJvm$1.applyOrElse(DebugManager.scala:159) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167) ~[scala-library-2.11.7.jar:na]
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:62) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:50) ~[akka-actor_2.11-2.3.12.jar:na]
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123) ~[scala-library-2.11.7.jar:na]
	at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.12.jar:na]
	at org.ensime.core.debug.DebugManager.aroundReceive(DebugManager.scala:25) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
19:28:19.040 WARN  akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugManager - Could not access debug VM
19:28:19.040 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/2146 o.e.s.RequestHandler - received handled message FalseResponse in state receive
19:28:19.040 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/2147 o.e.s.RequestHandler - SymbolAtPointReq(/home/robin/git/foo/api/src/test/scala/com/example/Censored.scala,2671)
19:28:19.041 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message SymbolAtPointReq(/home/robin/git/foo/api/src/test/scala/com/example/Censored.scala,2671)
19:28:19.041 DEBUG akka://ENSIME/user/ensime-main/project/analyzer o.e.c.Analyzer - received handled message SymbolAtPointReq(/home/robin/git/foo/api/src/test/scala/com/example/Censored.scala,2671) in state ready
19:28:19.041 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/2147 o.e.s.RequestHandler - received handled message Some(SymbolInfo(headers,headers,Some(OffsetSourcePosition(/home/robin/git/foo/.ensime_cache/dep-src/source-jars/spray/http/HttpMessage.scala,2402)),BasicTypeInfo(List,16,Class,scala.collection.immutable.List,List(BasicTyp
19:28:19.041 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/2148 o.e.s.RequestHandler - DebugLocateNameReq(DebugThreadId(1355),headers)
19:28:19.041 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugLocateNameReq(DebugThreadId(1355),headers)
19:28:19.041 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugManager - received handled message DebugLocateNameReq(DebugThreadId(1355),headers)
19:28:19.041 ERROR akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugManager - Exception thrown whilst handling vm action
com.sun.jdi.AbsentInformationException: null
	at com.sun.tools.jdi.ConcreteMethodImpl.getVariables(ConcreteMethodImpl.java:532) ~[tools.jar:na]
	at com.sun.tools.jdi.ConcreteMethodImpl.variables(ConcreteMethodImpl.java:217) ~[tools.jar:na]
	at com.sun.tools.jdi.StackFrameImpl.createVisibleVariables(StackFrameImpl.java:159) ~[tools.jar:na]
	at com.sun.tools.jdi.StackFrameImpl.visibleVariables(StackFrameImpl.java:182) ~[tools.jar:na]
	at org.ensime.core.debug.VM.stackSlotForName(VM.scala:472) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.VM.locationForName(VM.scala:364) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$fromUser$1$$anonfun$applyOrElse$19.apply(DebugManager.scala:347) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$fromUser$1$$anonfun$applyOrElse$19.apply(DebugManager.scala:346) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$org$ensime$core$debug$DebugManager$$handleRPCWithVMAndThread$1$$anonfun$apply$4.apply(DebugManager.scala:141) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$org$ensime$core$debug$DebugManager$$handleRPCWithVMAndThread$1$$anonfun$apply$4.apply(DebugManager.scala:140) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
	at org.ensime.core.debug.DebugManager$$anonfun$org$ensime$core$debug$DebugManager$$handleRPCWithVMAndThread$1.apply(DebugManager.scala:140) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$org$ensime$core$debug$DebugManager$$handleRPCWithVMAndThread$1.apply(DebugManager.scala:139) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$liftedTree1$1$1.apply(DebugManager.scala:115) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$liftedTree1$1$1.apply(DebugManager.scala:114) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
	at org.ensime.core.debug.DebugManager.liftedTree1$1(DebugManager.scala:114) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager.withVM(DebugManager.scala:113) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager.org$ensime$core$debug$DebugManager$$handleRPCWithVMAndThread(DebugManager.scala:139) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.debug.DebugManager$$anonfun$fromUser$1.applyOrElse(DebugManager.scala:345) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
	at org.ensime.core.debug.DebugManager$$anonfun$fromJvm$1.applyOrElse(DebugManager.scala:159) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167) ~[scala-library-2.11.7.jar:na]
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:62) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:50) ~[akka-actor_2.11-2.3.12.jar:na]
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123) ~[scala-library-2.11.7.jar:na]
	at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.12.jar:na]
	at org.ensime.core.debug.DebugManager.aroundReceive(DebugManager.scala:25) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
19:28:19.045 WARN  akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugManager - Could not access debug VM
19:28:19.045 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/2148 o.e.s.RequestHandler - received handled message FalseResponse in state receive
19:28:19.046 ERROR akka://ENSIME/user/ensime-main/tcp-server/con1 o.e.s.t.TCPConnectionActor - Error seen during message processing, closing client connection
org.ensime.server.protocol.swank.SwankRPCFormatException: Invalid rpc request (swank:debug-value nil)
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:870) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:859) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.SwankProtocol.decode(SwankProtocol.scala:14) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor.repeatedDecode(TCPConnectionActor.scala:104) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor.attemptProcess(TCPConnectionActor.scala:93) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor$$anonfun$incoming$1.applyOrElse(TCPConnectionActor.scala:45) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170) ~[scala-library-2.11.7.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.12.jar:na]
	at org.ensime.server.tcp.TCPConnectionActor.aroundReceive(TCPConnectionActor.scala:15) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: org.ensime.sexp.DeserializationException: Unable to parse SexpNil
	at org.ensime.sexp.formats.package$.deserializationError(package.scala:5) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolCommon$TraitFormatAlt.read(SwankFormats.scala:63) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.LowPriorityProductFormats$HListFormat$$anon$4.read(ProductFormats.scala:39) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.LowPriorityProductFormats$HListFormat$$anon$4.read(ProductFormats.scala:33) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$$anon$68.read(SwankFormats.scala:663) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$$anon$68.read(SwankFormats.scala:657) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestFormat$.read(SwankFormats.scala:847) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestFormat$.read(SwankFormats.scala:795) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$$anonfun$42.apply(SwankFormats.scala:864) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$$anonfun$42.apply(SwankFormats.scala:864) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.util.Try$.apply(Try.scala:192) ~[scala-library-2.11.7.jar:na]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:864) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	... 18 common frames omitted
19:28:19.047 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.SelectionHandler - Monitored actor [Actor[akka://ENSIME/user/ensime-main/tcp-server/con1#-1158275555]] terminated
```

**Comment by fommil** [comment]
Oh joy

**Comment by fommil** [comment]
Actually looks like a SWANK thing

**Comment by rorygraves** [comment]
So there are two issues here:

1) Why is emacs sending ```org.ensime.server.protocol.swank.SwankRPCFormatException: Invalid rpc request (swank:debug-value nil)``` this should not happen
2) If ```DebugLocateNameReq(DebugThreadId(1355),headers)``` returns no values its probably not an error worthy of a stacktrace - need to investigate the behaviour there.

**Comment by fommil** [comment]
@rorygraves I think we should be much more forgiving of these sorts of marshalling errors and not kill the connection. Same with presentation compiler blow-ups... the nuclear option is a bit nasty. Especially since I can't track continuous release at work :-(

**Comment by aemoncannon** [comment]
+1

**Comment by fommil** [comment]
We're going through the older bug reports that don't have a reproduction.

Nowadays, we close tickets that look like a known issue or don't provide the details requested by the template (which didn't exist when you reported this). The reason is to improve the quality of our issue tracker and to make it easier for contributors to help.

Can you please give a full reproduction, ideally in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also good. We are happy to help you write an automated test exhibiting the bug, and discuss ideas on how to fix, read the http://ensime.org/contributing guide for more information.

We will leave this ticket open for a few weeks. If you can confirm it is a bug by giving us a **detailed** reproduction - or let us know that you're working on a fix - we will leave it open for longer.

Please read the http://ensime.org/getting_help guide to understand the steps that are now required prior to submitting a bug report. We recently rewrote almost all the documentation since this bug was initially reported and you might find some useful information in there.
