### ISSUE TITLE
Shutting down ActorSystem unexpectedly when emacs open some scala files.

### ISSUE THREAD

**Issue by Hiroyuki-Nagata** [ensime/ensime-server#1111]
Probably related with #944 

I doubt SNAPSHOT build ensime brought by `ensime-update` caused it.

* Environment
```
16:30:03.811 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - Environment:
  OS : Linux
  Java : OpenJDK 64-Bit Server VM 24.85-b03, OpenJDK Runtime Environment 1.7.0_85-mockbuild_2015_07_15_12_57-b00
  Scala : version 2.10.2
  Ensime : 0.9.10-SNAPSHOT
```

* Log
```
16:30:31.862 ERROR ActorSystem(ENSIME) a.a.ActorSystemImpl - Uncaught fatal error from thread [ENSIME-akka.actor.default-dispatcher-2] shutting down ActorSystem [ENSIME]
java.lang.NoSuchMethodError: org.ensime.core.RichPresentationCompiler.askLoadedTyped(Lscala/reflect/internal/util/SourceFile;ZLscala/tools/nsc/interactive/Response;)V
        at org.ensime.core.RichCompilerControl$class.askLoadedTyped(RichPresentationCompiler.scala:114) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.RichPresentationCompiler.askLoadedTyped(RichPresentationCompiler.scala:198) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:240) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:152) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33) ~[scala-library-2.10.2.jar:na]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33) ~[scala-library-2.10.2.jar:na]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25) ~[scala-library-2.10.2.jar:na]
        at org.ensime.core.Analyzer$$anonfun$ready$1.applyOrElse(Analyzer.scala:149) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33) ~[scala-library-2.10.2.jar:na]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33) ~[scala-library-2.10.2.jar:na]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25) ~[scala-library-2.10.2.jar:na]
        at akka.event.LoggingReceive.apply(LoggingReceive.scala:62) ~[akka-actor_2.10-2.3.14.jar:na]
        at akka.event.LoggingReceive.apply(LoggingReceive.scala:50) ~[akka-actor_2.10-2.3.14.jar:na]
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118) ~[scala-library-2.10.2.jar:na]
        at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50) ~[akka-actor_2.10-2.3.14.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.10-2.3.14.jar:na]
        at org.ensime.core.Analyzer.aroundReceive(Analyzer.scala:41) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.10-2.3.14.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.10-2.3.14.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.10-2.3.14.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.10-2.3.14.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.10-2.3.14.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.10.2.jar:na]
16:30:31.867 ERROR ActorSystem(ENSIME) a.a.ActorSystemImpl - Uncaught fatal error from thread [ENSIME-akka.actor.default-dispatcher-8] shutting down ActorSystem [ENSIME]
java.lang.NoSuchMethodError: org.ensime.core.RichPresentationCompiler.askLoadedTyped(Lscala/reflect/internal/util/SourceFile;ZLscala/tools/nsc/interactive/Response;)V
        at org.ensime.core.RichCompilerControl$class.askLoadedTyped(RichPresentationCompiler.scala:114) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.RichPresentationCompiler.askLoadedTyped(RichPresentationCompiler.scala:198) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:240) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:152) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33) ~[scala-library-2.10.2.jar:na]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33) ~[scala-library-2.10.2.jar:na]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25) ~[scala-library-2.10.2.jar:na]
        at org.ensime.core.Analyzer$$anonfun$ready$1.applyOrElse(Analyzer.scala:149) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33) ~[scala-library-2.10.2.jar:na]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33) ~[scala-library-2.10.2.jar:na]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25) ~[scala-library-2.10.2.jar:na]
        at akka.event.LoggingReceive.apply(LoggingReceive.scala:62) ~[akka-actor_2.10-2.3.14.jar:na]
        at akka.event.LoggingReceive.apply(LoggingReceive.scala:50) ~[akka-actor_2.10-2.3.14.jar:na]
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118) ~[scala-library-2.10.2.jar:na]
        at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50) ~[akka-actor_2.10-2.3.14.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.10-2.3.14.jar:na]
        at org.ensime.core.Analyzer.aroundReceive(Analyzer.scala:41) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.10-2.3.14.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.10-2.3.14.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.10-2.3.14.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.10-2.3.14.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.10-2.3.14.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.10.2.jar:na]
```

**Comment by rorygraves** [comment]
Did you do the snapshot build on a different version of scala to to the one your project is using?
```java.lang.NoSuchMethodError: org.ensime.core.RichPresentationCompiler.askLoadedTyped(Lscala/reflect/internal/util/SourceFile;ZLscala/tools/nsc/interactive/Response;)V
``` implies to me that the the version of ensime and the version of the Scala compiler libraries are out of sync.

**Comment by Hiroyuki-Nagata** [comment]
Thanks @rorygraves 
It seems this issue depends on Scala version of target project.
This was happened in a case of `Scala : version 2.10.2`, but not happened `Scala : version 2.10.4`.

**Comment by fommil** [comment]
Yes, sorry we were not aware of that version restriction. OK to close based on Scala version? If support for older Scala 2.10 is needed we might be able to do something. Can somebody please update the wiki version requirements if we don't plan to fix?
