### ISSUE TITLE
UNRESOLVED DEPENDENCIES org.ensime#ensime_2.10;0.9.10-SNAPSHOT: not found

### ISSUE THREAD

**Issue by jlallison** [ensime/ensime-server#1185]
Using sbt .13.9 and scala 2.10.4 both on AWS emr-4.2.0. Attempting to establish ensime connection through emacs running on a client with ensime as available 12/18/2015 via MELPA.

Various errors akin to this have been noted in the archives. Is this a known issue, explainable or easily resolved?

[info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.9 ...
[info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.9 ...
[info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.9 ...
[info] Resolving org.scala-lang#jline;2.10.5 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to ensime_update_7528ior (in build file:/private/tmp/ensime_update_7528Ior/)
[info] Updating {file:/private/tmp/ensime_update_7528Ior/}ensime_update_7528ior...
[warn] Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/ensime/ensime_2.10/0.9.10-SNAPSHOT/maven-metadata.xml
[info] You probably access the destination server through a proxy server that is not well configured.
[warn] Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/ensime/ensime_2.10/0.9.10-SNAPSHOT/ensime_2.10-0.9.10-SNAPSHOT.pom
[info] You probably access the destination server through a proxy server that is not well configured.
[warn] Host bits.netbeans.org not found. url=http://bits.netbeans.org/nexus/content/groups/netbeans/org/ensime/ensime_2.10/0.9.10-SNAPSHOT/maven-metadata.xml
[info] You probably access the destination server through a proxy server that is not well configured.
[warn] Host bits.netbeans.org not found. url=http://bits.netbeans.org/nexus/content/groups/netbeans/org/ensime/ensime_2.10/0.9.10-SNAPSHOT/ensime_2.10-0.9.10-SNAPSHOT.pom
[info] You probably access the destination server through a proxy server that is not well configured.
[warn] Host oss.sonatype.org not found. url=https://oss.sonatype.org/content/repositories/snapshots/org/ensime/ensime_2.10/0.9.10-SNAPSHOT/maven-metadata.xml
[info] You probably access the destination server through a proxy server that is not well configured.
[warn] Host oss.sonatype.org not found. url=https://oss.sonatype.org/content/repositories/snapshots/org/ensime/ensime_2.10/0.9.10-SNAPSHOT/ensime_2.10-0.9.10-SNAPSHOT.pom
[info] You probably access the destination server through a proxy server that is not well configured.
[warn] 	module not found: org.ensime#ensime_2.10;0.9.10-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/ja80670/.ivy2/local/org.ensime/ensime_2.10/0.9.10-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/ensime/ensime_2.10/0.9.10-SNAPSHOT/ensime_2.10-0.9.10-SNAPSHOT.pom
[warn] ==== Maven2 Local: tried
[warn]   file:/Users/ja80670/.m2/repository/org/ensime/ensime_2.10/0.9.10-SNAPSHOT/ensime_2.10-0.9.10-SNAPSHOT.pom
[warn] ==== NetBeans: tried
[warn]   http://bits.netbeans.org/nexus/content/groups/netbeans/org/ensime/ensime_2.10/0.9.10-SNAPSHOT/ensime_2.10-0.9.10-SNAPSHOT.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/org/ensime/ensime_2.10/0.9.10-SNAPSHOT/ensime_2.10-0.9.10-SNAPSHOT.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.ensime#ensime_2.10;0.9.10-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.ensime:ensime_2.10:0.9.10-SNAPSHOT (/private/tmp/ensime_update_7528Ior/build.sbt#L25-26)
[warn] 		  +- default:ensime_update_7528ior_2.10:0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: org.ensime#ensime_2.10;0.9.10-SNAPSHOT: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.ensime#ensime_2.10;0.9.10-SNAPSHOT: not found
[error] Total time: 2 s, completed Dec 19, 2015 12:11:13 AM

**Comment by fommil** [comment]
Please raise tickets on the ENSIME Emacs tracker. Also, read CONTRIBUTING.

**Comment by fommil** [comment]
actually, this is a proxy issue. Probably best to ask about it from an sbt expert, or use the pre-built ensime jars https://github.com/ensime/ensime-emacs/wiki/Quick-Start-Guide#installing-the-server-from-assembly-builds-or-source

**Comment by jlallison** [comment]
Checked with an sbt expert who didn't see it as a proxy issue. Followed the above link and do not see any ensime jars, ensime .els, yes but no jars. Are you sure the link is what you intended?

**Comment by gregnwosu** [comment]
im seeing this issue

**Comment by fommil** [comment]
http://ensime.github.io/getting_help/
