### ISSUE TITLE
`EnDeclaration` is not working

### ISSUE THREAD

**Issue by jvican** [ensime/ensime-server#1211]
This issue is related to [ensime-vim](https://github.com/ensime/ensime-vim). I open vim, wait for the `ensime analyzer` to be ready and run `EnDeclaration`. Nothing happens.
  
On the `ensime-vim` side:
```
2016-01-08 10:58:30.057000: handle_payload: in {u'typehint': u'FullTypeCheckCompleteEvent'}
2016-01-08 10:59:12.040998: open_declaration: in
2016-01-08 10:59:12.042399: path: in
2016-01-08 10:59:12.043191: path: in
2016-01-08 10:59:12.043875: send_request: in
2016-01-08 10:59:12.044036: send: in
2016-01-08 10:59:12.044144: send: {"callId": 1, "req": {"typehint": "SymbolAtPointReq", "file": "/data/rw/code/scala/phonebook-server/src/main/scala/Server.scala", "point": 739}}
2016-01-08 10:59:14.050244: unqueue: result received {
  "callId": 1,
  "payload": {
    "typehint": "FalseResponse"
  }
}
2016-01-08 10:59:14.050513: handle_payload: in {u'typehint': u'FalseResponse'}
```
  
On the `ensime-server` side:
```
10:58:00.993 INFO  None a.e.s.Slf4jLogger - Slf4jLogger started
10:58:01.008 DEBUG EventStream(akka://ENSIME) a.e.EventStream - logger log1-Slf4jLogger started
10:58:01.014 DEBUG EventStream(akka://ENSIME) a.e.EventStream - Default Loggers started
10:58:01.088 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
10:58:01.135 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Successfully bound to /127.0.0.1:39779
10:58:01.139 INFO  None o.e.s.PortUtil$ - creating portfile /data/rw/code/scala/phonebook-server/.ensime_cache/port
10:58:01.139 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Bound server on port 39779
10:58:02.179 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - Environment:
  OS : Linux
  Java : OpenJDK 64-Bit Server VM 24.91-b01, OpenJDK Runtime Environment 1.7.0_91-b02
  Scala : version 2.11.7
  Ensime : 0.9.10-SNAPSHOT
10:58:02.201 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - Successfully bound to /127.0.0.1:37168
10:58:02.224 INFO  None o.e.s.PortUtil$ - creating portfile /data/rw/code/scala/phonebook-server/.ensime_cache/http
10:58:02.225 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - ENSIME HTTP on /127.0.0.1
10:58:02.873 INFO  None o.e.i.ClassfileWatcher - Setting up new file watchers
10:58:24.606 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - New connection accepted
10:58:24.622 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - New connection accepted
10:58:24.653 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/2 a.a.LocalActorRef - unhandled message from Actor[akka://ENSIME/system/IO-TCP-STREAM/server-1-%2F127.0.0.1%3A0/$a#-359696789]: ResumeReading
10:58:25.367 DEBUG akka://ENSIME/user/$a/0 o.e.s.RequestHandler - ConnectionInfoReq
10:58:25.368 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message ConnectionInfoReq in state awaitingConnectionInfoReq
10:58:25.371 DEBUG akka://ENSIME/user/$a/0 o.e.s.RequestHandler - received handled message ConnectionInfo(None,EnsimeImplementation(ENSIME),0.8.19) in state receive
10:58:25.685 WARN  None c.j.b.BoneCPConfig - JDBC username was not set in config!
10:58:26.158 WARN  akka://ENSIME/user/ensime-main/project o.e.c.Project - org.h2.jdbc.JdbcSQLException: Table "FILECHECKS" not found; SQL statement:
select "id", "filename", "timestamp" from "FILECHECKS" [42102-190]
10:58:26.163 ERROR akka.dispatch.Dispatcher a.d.Dispatcher - Table "FILECHECKS" not found; SQL statement:
select "id", "filename", "timestamp" from "FILECHECKS" [42102-190]
org.h2.jdbc.JdbcSQLException: Table "FILECHECKS" not found; SQL statement:
select "id", "filename", "timestamp" from "FILECHECKS" [42102-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.readTableOrView(Parser.java:5293) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.readTableFilter(Parser.java:1234) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1873) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1982) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parseSelectSub(Parser.java:1867) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1688) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parseSelect(Parser.java:1676) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parsePrepared(Parser.java:432) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parse(Parser.java:304) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parse(Parser.java:276) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.prepareCommand(Parser.java:241) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.engine.Session.prepareLocal(Session.java:460) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.engine.Session.prepareCommand(Session.java:402) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:72) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276) ~[h2-1.4.190.jar:1.4.190]
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1024) ~[bonecp-0.8.0.RELEASE.jar:na]
	at slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:297) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:407) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:33) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.Invoker$class.foreach(Invoker.scala:48) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.StreamingInvokerAction$class.run(StreamingInvokerAction.scala:22) ~[slick_2.11-3.1.1.jar:na]
	at slick.driver.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:218) ~[slick_2.11-3.1.1.jar:na]
	at slick.driver.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:218) ~[slick_2.11-3.1.1.jar:na]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237) ~[slick_2.11-3.1.1.jar:na]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237) ~[slick_2.11-3.1.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_91]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_91]
10:58:27.788 DEBUG akka://ENSIME/user/$a o.e.s.ConnectionHandler - received handled message SendBackgroundMessageEvent(Initializing Analyzer. Please wait...,105)
10:58:27.809 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message FullTypeCheckCompleteEvent in state startup
10:58:27.810 DEBUG akka://ENSIME/user/$a o.e.s.ConnectionHandler - received handled message AnalyzerReadyEvent
10:58:27.811 DEBUG akka://ENSIME/user/$a o.e.s.ConnectionHandler - received handled message FullTypeCheckCompleteEvent
10:58:29.969 DEBUG akka://ENSIME/user/ensime-main/$a/flow-5-0-publisherSource-prefixAndTail a.s.i.PrefixAndTailImpl - Cancelling akka.stream.impl.MultiStreamOutputProcessor$SubstreamOutput@46c2d609 (after: 5000 ms)
10:59:12.114 DEBUG akka://ENSIME/user/$a/1 o.e.s.RequestHandler - SymbolAtPointReq(Left(/data/rw/code/scala/phonebook-server/src/main/scala/Server.scala),739)
10:59:12.118 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message SymbolAtPointReq(Left(/data/rw/code/scala/phonebook-server/src/main/scala/Server.scala),739) in state handleRequests
10:59:12.119 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message SymbolAtPointReq(Left(/data/rw/code/scala/phonebook-server/src/main/scala/Server.scala),739) in state ready
10:59:13.494 DEBUG None o.e.c.RichPresentationCompiler - using symbol of class scala.reflect.internal.Trees$Select tree
10:59:13.528 ERROR None o.e.c.RichPresentationCompiler - Error during askOption
org.h2.jdbc.JdbcSQLException: Table "FQN_SYMBOLS" not found; SQL statement:
select "id", "file", "path", "fqn", "descriptor", "internal", "source handle", "line in source", "offset in source" from "FQN_SYMBOLS" where "fqn" = ? limit 1 [42102-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.readTableOrView(Parser.java:5293) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.readTableFilter(Parser.java:1234) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1873) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1982) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parseSelectSub(Parser.java:1867) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1688) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parseSelect(Parser.java:1676) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parsePrepared(Parser.java:432) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parse(Parser.java:304) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.parse(Parser.java:276) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Parser.prepareCommand(Parser.java:241) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.engine.Session.prepareLocal(Session.java:460) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.engine.Session.prepareCommand(Session.java:402) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:72) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276) ~[h2-1.4.190.jar:1.4.190]
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1024) ~[bonecp-0.8.0.RELEASE.jar:na]
	at slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:297) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:407) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:33) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.Invoker$class.foreach(Invoker.scala:48) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.Invoker$class.firstOption(Invoker.scala:24) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.StatementInvoker.firstOption(StatementInvoker.scala:16) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.StreamingInvokerAction$HeadOptionAction.run(StreamingInvokerAction.scala:57) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.StreamingInvokerAction$HeadOptionAction.run(StreamingInvokerAction.scala:56) ~[slick_2.11-3.1.1.jar:na]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237) ~[slick_2.11-3.1.1.jar:na]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237) ~[slick_2.11-3.1.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_91]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_91]
10:59:13.529 DEBUG akka://ENSIME/user/$a/1 o.e.s.RequestHandler - received handled message None in state receive
```
  
My `.ensime` looks like this:
```
(
 :root-dir "/data/rw/code/scala/phonebook-server"
 :cache-dir "/data/rw/code/scala/phonebook-server/.ensime_cache"
 :name "phonebook-server"
 :java-home "/etc/java-config-2/current-system-vm"
 :java-flags ("-XX:MaxPermSize=256m" "-XX:ReservedCodeCacheSize=128m" "-Xms1024m" "-Xmx1024m" "-Xss2m")
 :reference-source-roots ("/etc/java-config-2/current-system-vm/src.zip")
 :scala-version "2.11.7"
 :compiler-args ("-Xfuture" "-Xlint" "-Yinline-warnings" "-Yno-adapted-args" "-Ywarn-dead-code" "-Ywarn-numeric-widen" "-Ywarn-unused-import" "-deprecation" "-feature")
 :formatting-prefs nil
 :subprojects ((
   :name "phonebook-server"
   :source-roots ("/data/rw/code/scala/phonebook-server/src/main/scala" "/data/rw/code/scala/phonebook-server/src/test/scala")
   :targets ("/data/rw/code/scala/phonebook-server/target/scala-2.11/classes")
   :test-targets ("/data/rw/code/scala/phonebook-server/target/scala-2.11/test-classes")
   :depends-on-modules nil
   :compile-deps ("/home/jvican/.ivy2/cache/com.chuusai/shapeless_2.11/jars/shapeless_2.11-1.2.4.jar" "/home/jvican/.ivy2/cache/com.h2database/h2/jars/h2-1.3.170.jar" "/home/jvican/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.3.9.jar" "/home/jvican/.ivy2/cache/com.typesafe.slick/slick_2.11/bundles/slick_2.11-3.1.0.jar" "/home/jvican/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar" "/home/jvican/.ivy2/cache/io.spray/spray-can_2.11/bundles/spray-can_2.11-1.3.3.jar" "/home/jvican/.ivy2/cache/io.spray/spray-http_2.11/bundles/spray-http_2.11-1.3.3.jar" "/home/jvican/.ivy2/cache/io.spray/spray-httpx_2.11/bundles/spray-httpx_2.11-1.3.3.jar" "/home/jvican/.ivy2/cache/io.spray/spray-io_2.11/bundles/spray-io_2.11-1.3.3.jar" "/home/jvican/.ivy2/cache/io.spray/spray-json_2.11/bundles/spray-json_2.11-1.3.2.jar" "/home/jvican/.ivy2/cache/io.spray/spray-routing_2.11/bundles/spray-routing_2.11-1.3.3.jar" "/home/jvican/.ivy2/cache/io.spray/spray-util_2.11/bundles/spray-util_2.11-1.3.3.jar" "/home/jvican/.ivy2/cache/org.jvnet.mimepull/mimepull/jars/mimepull-1.9.5.jar" "/home/jvican/.ivy2/cache/org.parboiled/parboiled-core/jars/parboiled-core-1.1.7.jar" "/home/jvican/.ivy2/cache/org.parboiled/parboiled-scala_2.11/jars/parboiled-scala_2.11-1.1.7.jar" "/home/jvican/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.jar" "/home/jvican/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.3.jar" "/home/jvican/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar" "/home/jvican/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.10.jar" "/home/jvican/.ivy2/cache/org.slf4j/slf4j-nop/jars/slf4j-nop-1.6.4.jar")
   :runtime-deps nil
   :test-deps ("/home/jvican/.ivy2/cache/com.typesafe.akka/akka-testkit_2.11/jars/akka-testkit_2.11-2.3.9.jar" "/home/jvican/.ivy2/cache/io.spray/spray-testkit_2.11/jars/spray-testkit_2.11-1.3.3.jar" "/home/jvican/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.1.jar" "/home/jvican/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.2.jar" "/home/jvican/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar" "/home/jvican/.ivy2/cache/org.scalacheck/scalacheck_2.11/jars/scalacheck_2.11-1.12.5.jar" "/home/jvican/.ivy2/cache/org.scalatest/scalatest_2.11/bundles/scalatest_2.11-2.2.4.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-concurrent_2.11/bundles/scalaz-concurrent_2.11-7.0.6.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-core_2.11/bundles/scalaz-core_2.11-7.0.6.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-effect_2.11/bundles/scalaz-effect_2.11-7.0.6.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-common_2.11/jars/specs2-common_2.11-2.3.11.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-core_2.11/jars/specs2-core_2.11-2.3.11.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-matcher_2.11/jars/specs2-matcher_2.11-2.3.11.jar")
   :doc-jars ("/data/rw/code/scala/phonebook-server/target/scala-2.11/agenda-server_2.11-1.0-javadoc.jar" "/home/jvican/.ivy2/cache/com.chuusai/shapeless_2.11/docs/shapeless_2.11-1.2.4-javadoc.jar" "/home/jvican/.ivy2/cache/com.h2database/h2/docs/h2-1.3.170-javadoc.jar" "/home/jvican/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/docs/akka-actor_2.11-2.3.9-javadoc.jar" "/home/jvican/.ivy2/cache/com.typesafe.akka/akka-testkit_2.11/docs/akka-testkit_2.11-2.3.9-javadoc.jar" "/home/jvican/.ivy2/cache/com.typesafe.slick/slick_2.11/docs/slick_2.11-3.1.0-javadoc.jar" "/home/jvican/.ivy2/cache/com.typesafe/config/docs/config-1.2.1-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-can_2.11/docs/spray-can_2.11-1.3.3-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-http_2.11/docs/spray-http_2.11-1.3.3-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-httpx_2.11/docs/spray-httpx_2.11-1.3.3-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-io_2.11/docs/spray-io_2.11-1.3.3-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-json_2.11/docs/spray-json_2.11-1.3.2-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-routing_2.11/docs/spray-routing_2.11-1.3.3-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-testkit_2.11/docs/spray-testkit_2.11-1.3.3-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-util_2.11/docs/spray-util_2.11-1.3.3-javadoc.jar" "/home/jvican/.ivy2/cache/org.jvnet.mimepull/mimepull/docs/mimepull-1.9.5-javadoc.jar" "/home/jvican/.ivy2/cache/org.parboiled/parboiled-core/docs/parboiled-core-1.1.7-javadoc.jar" "/home/jvican/.ivy2/cache/org.parboiled/parboiled-scala_2.11/docs/parboiled-scala_2.11-1.1.7-javadoc.jar" "/home/jvican/.ivy2/cache/org.reactivestreams/reactive-streams/docs/reactive-streams-1.0.0-javadoc.jar" "/home/jvican/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/docs/scala-parser-combinators_2.11-1.0.1-javadoc.jar" "/home/jvican/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/docs/scala-xml_2.11-1.0.3-javadoc.jar" "/home/jvican/.ivy2/cache/org.scala-lang/scala-library/docs/scala-library-2.11.7-javadoc.jar" "/home/jvican/.ivy2/cache/org.scala-lang/scala-reflect/docs/scala-reflect-2.11.2-javadoc.jar" "/home/jvican/.ivy2/cache/org.scala-sbt/test-interface/docs/test-interface-1.0-javadoc.jar" "/home/jvican/.ivy2/cache/org.scalacheck/scalacheck_2.11/docs/scalacheck_2.11-1.12.5-javadoc.jar" "/home/jvican/.ivy2/cache/org.scalatest/scalatest_2.11/docs/scalatest_2.11-2.2.4-javadoc.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-concurrent_2.11/docs/scalaz-concurrent_2.11-7.0.6-javadoc.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-core_2.11/docs/scalaz-core_2.11-7.0.6-javadoc.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-effect_2.11/docs/scalaz-effect_2.11-7.0.6-javadoc.jar" "/home/jvican/.ivy2/cache/org.slf4j/slf4j-api/docs/slf4j-api-1.7.10-javadoc.jar" "/home/jvican/.ivy2/cache/org.slf4j/slf4j-nop/docs/slf4j-nop-1.6.4-javadoc.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-common_2.11/docs/specs2-common_2.11-2.3.11-javadoc.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-core_2.11/docs/specs2-core_2.11-2.3.11-javadoc.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-matcher_2.11/docs/specs2-matcher_2.11-2.3.11-javadoc.jar")
   :reference-source-roots ("/home/jvican/.ivy2/cache/com.chuusai/shapeless_2.11/srcs/shapeless_2.11-1.2.4-sources.jar" "/home/jvican/.ivy2/cache/com.h2database/h2/srcs/h2-1.3.170-sources.jar" "/home/jvican/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/srcs/akka-actor_2.11-2.3.9-sources.jar" "/home/jvican/.ivy2/cache/com.typesafe.akka/akka-testkit_2.11/srcs/akka-testkit_2.11-2.3.9-sources.jar" "/home/jvican/.ivy2/cache/com.typesafe.slick/slick_2.11/srcs/slick_2.11-3.1.0-sources.jar" "/home/jvican/.ivy2/cache/com.typesafe/config/srcs/config-1.2.1-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-can_2.11/srcs/spray-can_2.11-1.3.3-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-http_2.11/srcs/spray-http_2.11-1.3.3-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-httpx_2.11/srcs/spray-httpx_2.11-1.3.3-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-io_2.11/srcs/spray-io_2.11-1.3.3-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-json_2.11/srcs/spray-json_2.11-1.3.2-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-routing_2.11/srcs/spray-routing_2.11-1.3.3-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-testkit_2.11/srcs/spray-testkit_2.11-1.3.3-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-util_2.11/srcs/spray-util_2.11-1.3.3-sources.jar" "/home/jvican/.ivy2/cache/org.jvnet.mimepull/mimepull/srcs/mimepull-1.9.5-sources.jar" "/home/jvican/.ivy2/cache/org.parboiled/parboiled-core/srcs/parboiled-core-1.1.7-sources.jar" "/home/jvican/.ivy2/cache/org.parboiled/parboiled-scala_2.11/srcs/parboiled-scala_2.11-1.1.7-sources.jar" "/home/jvican/.ivy2/cache/org.reactivestreams/reactive-streams/srcs/reactive-streams-1.0.0-sources.jar" "/home/jvican/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/srcs/scala-parser-combinators_2.11-1.0.1-sources.jar" "/home/jvican/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/srcs/scala-xml_2.11-1.0.3-sources.jar" "/home/jvican/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.11.7-sources.jar" "/home/jvican/.ivy2/cache/org.scala-lang/scala-reflect/srcs/scala-reflect-2.11.2-sources.jar" "/home/jvican/.ivy2/cache/org.scala-sbt/test-interface/srcs/test-interface-1.0-sources.jar" "/home/jvican/.ivy2/cache/org.scalacheck/scalacheck_2.11/srcs/scalacheck_2.11-1.12.5-sources.jar" "/home/jvican/.ivy2/cache/org.scalatest/scalatest_2.11/srcs/scalatest_2.11-2.2.4-sources.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-concurrent_2.11/srcs/scalaz-concurrent_2.11-7.0.6-sources.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-core_2.11/srcs/scalaz-core_2.11-7.0.6-sources.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-effect_2.11/srcs/scalaz-effect_2.11-7.0.6-sources.jar" "/home/jvican/.ivy2/cache/org.slf4j/slf4j-api/srcs/slf4j-api-1.7.10-sources.jar" "/home/jvican/.ivy2/cache/org.slf4j/slf4j-nop/srcs/slf4j-nop-1.6.4-sources.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-common_2.11/srcs/specs2-common_2.11-2.3.11-sources.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-core_2.11/srcs/specs2-core_2.11-2.3.11-sources.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-matcher_2.11/srcs/specs2-matcher_2.11-2.3.11-sources.jar")))
)
```
Running sbt `0.13.9` and scala `2.11.7`.

**Comment by rorygraves** [comment]
I suspect that your cache directory is out of sync with the latest ensime server changes, can you please clear your .ensime_cache, regenerate your .ensime and try again?

**Comment by fommil** [comment]
yeah, I think Rory has it. Please reopen if it still happens after that.

**Comment by jvican** [comment]
Yep, got it! Why is that happening?

**Comment by rorygraves** [comment]
Database Schema has changed due to recent work, we don't currently detect this,  If we did then we could automatically rebuild the database.

**Comment by fommil** [comment]
hmm, no, we're careful about the schema and we have versioning. My guess is you created an ensime server and then killed the process, and it was partway through creating the schema.

**Comment by rorygraves** [comment]
Whoops my bad, spreading false rumors....

**Comment by fommil** [comment]
btw we have this checklist for working through problems in ENSIME Emacs https://github.com/ensime/ensime-emacs/wiki/issue

I can imagine ENSIME Vim could have a similar thing... might be worth following if anything else like this comes up (although chances are most problems you encounter will be due to the Vim client simply not supporting it yet).

We're very tolerant of false alarms on the issue tracker when somebody is trying to implement something, so don't be shy.

**Comment by jvican** [comment]
Is there anything that can be done to avoid those kind of errors @fommil? I think it's not the first error that happens because of bad initialization.
  
Yes, I will give those pending features a try! Hope me to be around.

**Comment by fommil** [comment]
it's probably related to the basic state of ensime-vim. Once you get the launching stabilised, this will be extremely rare.

We should touch base after the Emacs launching refactorings, we're hoping to use coursier instead of sbt.

**Comment by jvican** [comment]
Nice, `coursier` is great, let me know if I can help.
