### ISSUE TITLE
SearchService parsing exception

### ISSUE THREAD

**Issue by rlvoyer** [ensime/ensime-server#1214]
It looks as though the ENSIME indexer is blowing up while trying to index [rojoma-json](https://github.com/rjmac/rojoma-json) classfiles.

```
17:41:11.973 WARN  akka://ENSIME/user/ensime-main/project o.e.c.Project - org.parboiled.errors.ParsingException: Invalid :
Invalid input '/', expected ![;/()EOI] or ';' (line 1, pos 33):
()Lcom/rojoma/json/v3/$minusimpl/util/WrapperJsonCodecImpl;
                                ^

17:41:11.979 ERROR akka.dispatch.Dispatcher a.d.Dispatcher - Invalid :
Invalid input '/', expected ![;/()EOI] or ';' (line 1, pos 33):
()Lcom/rojoma/json/v3/$minusimpl/util/WrapperJsonCodecImpl;
                                ^

org.parboiled.errors.ParsingException: Invalid :
Invalid input '/', expected ![;/()EOI] or ';' (line 1, pos 33):
()Lcom/rojoma/json/v3/$minusimpl/util/WrapperJsonCodecImpl;
                                ^

	at org.ensime.sexp.util.ParboiledParser$$anonfun$parse$1.apply(ParboiledParser.scala:23) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.util.ParboiledParser$$anonfun$parse$1.apply(ParboiledParser.scala:23) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.7.jar:na]
	at org.ensime.sexp.util.ParboiledParser$class.parse(ParboiledParser.scala:22) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.indexer.DescriptorParser$.parse(DescriptorParser.scala:12) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.indexer.ClassfileIndexer$class.org$ensime$indexer$ClassfileIndexer$$classesInDescriptor(ClassfileIndexer.scala:35) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.indexer.ClassfileIndexer$ReferenceInMethodHunter$class.visitMethodInsn(ClassfileIndexer.scala:203) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.indexer.ClassfileIndexer$AsmCallback$$anon$1.visitMethodInsn(ClassfileIndexer.scala:78) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-5.0.4.jar:5.0.4]
	at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-5.0.4.jar:5.0.4]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.4.jar:5.0.4]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.4.jar:5.0.4]
	at org.ensime.indexer.ClassfileIndexer$class.indexClassfile(ClassfileIndexer.scala:26) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.indexer.SearchService.indexClassfile(SearchService.scala:24) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.indexer.SearchService.org$ensime$indexer$SearchService$$extractSymbols(SearchService.scala:161) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.indexer.SearchService$$anonfun$org$ensime$indexer$SearchService$$indexBase$1$1$$anonfun$8$$anonfun$apply$3.apply(SearchService.scala:102) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.indexer.SearchService$$anonfun$org$ensime$indexer$SearchService$$indexBase$1$1$$anonfun$8$$anonfun$apply$3.apply(SearchService.scala:102) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.package$.blocking(package.scala:123) ~[scala-library-2.11.7.jar:na]
	at org.ensime.indexer.SearchService$$anonfun$org$ensime$indexer$SearchService$$indexBase$1$1$$anonfun$8.apply(SearchService.scala:101) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.indexer.SearchService$$anonfun$org$ensime$indexer$SearchService$$indexBase$1$1$$anonfun$8.apply(SearchService.scala:101) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.7.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) ~[akka-actor_2.11-2.3.14.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
```

**Comment by jasonij** [comment]
Yeah, it happens with [socrata-http](https://github.com/socrata-platform/socrata-http) too. It's the `-impl` directory. The idea, I think, was that things in `-impl`are implementation details that a developer shouldn't have to bother with. However, it does monkey up ENSIME.

**Comment by fommil** [comment]
Those classnames are breaking the JVM bytecode naming standards, so we'll have to put in a workaround. If you'd like to have a look at this, in should be pretty simple. First look in DescriptorParserSpec and add a test (obvious, some examples to copy) then DD the extra rules in DescriptorParser

**Comment by fommil** [comment]
the dollar sign is not a valid package descriptor name. We can workaround this but I advise flagging this upstream. In @jasonij's case, it looks like the dash is used in a package, but that is also not allowed. Both packages must be doing this in bad macros.

Incidentally, is there any reason why you wouldn't use spray-json-shapeless or circe for JSON? This seems like a pretty obscure library.

**Comment by rlvoyer** [comment]
@fommil: I'd be happy to try to attack a workaround. While we can consider moving away from rojoma and socrata-http for some projects at Socrata, it's unlikely we'll phase them out everywhere, so it'd be nice if we could add some workarounds to work with them w/ ENSIME. As for why we're using rojoma... One of our colleagues started building it quite a while ago (before the Scala JSON ecosystem had exploded) as an alternative to lift-json. It serves us well. (Although circe looks interesting...) Anyway, I'm going to look into addressing the package naming issues.

**Comment by fommil** [comment]
@rlvoyer it's probably allowed by the JMV bytecode internals, but it is most certainly **not** allowed according to the Java Language Specification (I read that chapter in detail when writing the `DescriptorParser`... amusingly, there are classes in the `sun.` namespace which are also not valid, possibly to avoid people calling them from Java)

**Comment by rlvoyer** [comment]
The Scala compiler is translating the dash into "$minus" and if I'm reading the spec correctly, "$minus" is a valid identifier. According to [the spec](http://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.8), a valid identifier must start with a "Java letter":

> A "Java letter" is a character for which the method Character.isJavaIdentifierStart(int) returns true.

```scala
scala> import java.lang.Character
import java.lang.Character

scala> Character.isJavaIdentifierStart('$')
res4: Boolean = true
```

For example, here's the output from Scalap when pointed at one of the classes in the relevant package:

```java
package com.rojoma.json.v3.$minusimpl.codec
final class PrefixableDecodeError extends scala.AnyVal {
  val private once 2.10 is gone: com.rojoma.json.v3.codec.DecodeError = { /* compiled code */ }
  def this(private$u0020once$u00202$u002E10$u0020is$u0020gone: com.rojoma.json.v3.codec.DecodeError) = { /* compiled code */ }
  def prefix(field: scala.Predef.String): com.rojoma.json.v3.codec.DecodeError = { /* compiled code */ }
  def prefix(index: scala.Int): com.rojoma.json.v3.codec.DecodeError = { /* compiled code */ }
  override def hashCode(): scala.Int = { /* compiled code */ }
  override def equals(x$1: scala.Any): scala.Boolean = { /* compiled code */ }
}
object PrefixableDecodeError extends scala.AnyRef {
  def this() = { /* compiled code */ }
  final def prefix$extension0($this: com.rojoma.json.v3.-impl.codec.PrefixableDecodeError)(field: scala.Predef.String): com.rojoma.json.v3.codec.DecodeError = { /* compiled code */ }
  final def prefix$extension1($this: com.rojoma.json.v3.-impl.codec.PrefixableDecodeError)(index: scala.Int): com.rojoma.json.v3.codec.DecodeError = { /* compiled code */ }
  final def hashCode$extension($this: com.rojoma.json.v3.-impl.codec.PrefixableDecodeError)(): scala.Int = { /* compiled code */ }
  final def equals$extension($this: com.rojoma.json.v3.-impl.codec.PrefixableDecodeError)(x$1: scala.Any): scala.Boolean = { /* compiled code */ }
}
```

I'm a huge fan of ENSIME, BTW -- thanks for all your efforts making it so usable. Not trying to be a pain...

**Comment by fommil** [comment]
Hmm, interesting! I thought we'd nailed the spec. Always room for improvement.

**Comment by fommil** [comment]
oh but hold on, @rlvoyer an `Identifier` is not a valid character in a package name in the JLS. It seems to be permitted in the bytecode, evidently.

**Comment by rlvoyer** [comment]
@fommil what makes you say that? Section 6.5 of the JLS has this recursive definition of PackageName:

```
PackageName:
  Identifier
  PackageName . Identifier
```

My interpretation of this is that a package name is one or more "."-separated Identifiers. Am I misreading this?

**Comment by fommil** [comment]
heh, no I must have misinterpreted it. That's a real pain actually, because a lot of people use `$` to detect the class part of a FQN.

BTW, if you want a **real** challenge, try rewriting the parser with parboiled2. It should give us a performance boost.

**Comment by rlvoyer** [comment]
My level of familiarity w/ the ENSIME codebase and w/ parboiled is limited to about the 1.5 hours I spent looking at it this weekend, split between understanding the code and understanding the Java Language spec. :) But if you're looking for more contributors, I'm happy to help where I can.

**Comment by jasonij** [comment]
A dash in the package name (as in `-impl`) is legal in Scala but illegal in Java.

**Comment by fommil** [comment]
btw, some people worked on this at the hack day, so expect a fix soon. @jasonij you'll need to give us an explicit example of what is going wrong for you because hyphens in the package name worked for us. A failing test case in `DescriptorParserSpec.scala` would be good.

**Comment by jasonij** [comment]
It's the same problem in a different package:
```
org.parboiled.errors.ParsingException: Invalid :
Invalid input '/', expected ![;/()EOI] or ';' (line 1, pos 55):
(Lscala/Function1;)Lcom/socrata/http/server/$minusimpl/ChainedHttpResponse;
```
Go `-impl`!

Thanks for taking an interest in this one. I'm eager to dig into the ensime codebase but I'm not yet familiar enough with it for a quick-fix PR.

**Comment by rorygraves** [comment]
@jasonij  I think this is fixed, can you please verify and close?

**Comment by jasonij** [comment]
Verified, has been working since the Parboiled2 merge.
