### ISSUE TITLE
SymbolDesignationsReq kills the presentation compiler if file does not exist

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-server#1221]
```15:26:27.702 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message SymbolDesignationsReq(Right(SourceFileInfo(/home/sohum/versioned/ludington-test/.ensime_cache/dep-src/source-jars/ludington/management/tenant/protocol/ReportType.scala,None,None)),0,1889,List(VarSymbol, ValSymbol, VarFieldSym
15:26:27.702 ERROR akka://ENSIME/user/ensime-main/project/scalac a.a.OneForOneStrategy - /home/sohum/versioned/ludington-test/.ensime_cache/dep-src/source-jars/ludington/management/tenant/protocol/ReportType.scala (No such file or directory)
java.io.FileNotFoundException: /home/sohum/versioned/ludington-test/.ensime_cache/dep-src/source-jars/ludington/management/tenant/protocol/ReportType.scala (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_72-internal]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_72-internal]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_72-internal]
        at com.google.common.io.Files$FileByteSource.openStream(Files.java:125) ~[guava-18.0.jar:na]
        at com.google.common.io.Files$FileByteSource.openStream(Files.java:115) ~[guava-18.0.jar:na]
        at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:420) ~[guava-18.0.jar:na]
        at com.google.common.io.CharSource.read(CharSource.java:147) ~[guava-18.0.jar:na]
        at com.google.common.io.Files.toString(Files.java:264) ~[guava-18.0.jar:na]
        at org.ensime.util.file.package$RichFile$.readString$extension(file.scala:87) ~[util_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.RichCompilerControl$class.createSourceFile(RichPresentationCompiler.scala:234) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.RichPresentationCompiler.createSourceFile(RichPresentationCompiler.scala:259) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.Analyzer.createSourceFile(Analyzer.scala:299) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:238) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:155) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33) ~[scala-library.jar:na]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33) ~[scala-library.jar:na]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25) ~[scala-library.jar:na]
        at org.ensime.core.Analyzer$$anonfun$ready$1.applyOrElse(Analyzer.scala:152) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33) ~[scala-library.jar:na]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33) ~[scala-library.jar:na]
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25) ~[scala-library.jar:na]
        at akka.event.LoggingReceive.apply(LoggingReceive.scala:62) ~[akka-actor_2.10-2.3.14.jar:na]
        at akka.event.LoggingReceive.apply(LoggingReceive.scala:50) ~[akka-actor_2.10-2.3.14.jar:na]
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118) ~[scala-library.jar:na]
        at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50) ~[akka-actor_2.10-2.3.14.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.10-2.3.14.jar:na]
        at org.ensime.core.Analyzer.aroundReceive(Analyzer.scala:42) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.10-2.3.14.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.10-2.3.14.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.10-2.3.14.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.10-2.3.14.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.10-2.3.14.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
```

**Comment by fommil** [comment]
the problem is that `SourceFileInfo` (which should be in `common.scala` not `outgoing.scala`) doesn't contain a `contents` or `contentsIn`. We otherwise support `File`s that do not exist (e.g. new buffers or scratch playgrounds).

Arguably, this is a client side bug and the current behaviour is correct according to the documentation https://github.com/ensime/ensime-server/blob/6d52e1090ffcd39ca25e23f72b94a50db147e70e/api/src/main/scala/org/ensime/api/incoming.scala#L268 but I'd be open to returning an error code instead. I'm surprised we don't send back an error, are you sure the `Analyzer` doesn't just get restarted safely and the client gets the expected response?

**Comment by rorygraves** [comment]
Its a client side bug, but it destroys the PC - so needs some defence on the server side.
