### ISSUE TITLE
java.lang.StackOverflowError: null at startup in atom

### ISSUE THREAD

**Issue by yoeluk** [ensime/ensime-server#1246]
In Atom getting consistency this exception on `ensime start` logged under server.log

```
02:33:54.461 INFO  None a.e.s.Slf4jLogger - Slf4jLogger started
02:33:54.469 DEBUG EventStream(akka://ENSIME) a.e.EventStream - logger log1-Slf4jLogger started
02:33:54.471 DEBUG EventStream(akka://ENSIME) a.e.EventStream - Default Loggers started
02:33:54.497 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "/var/folders/0d/9w6rm_457ll36_63fnjsq6jr1n7hv2/T/vfs_cache" as temporary files store.
02:33:54.529 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Successfully bound to /127.0.0.1:50363
02:33:54.531 INFO  None o.e.s.PortUtil$ - creating portfile /Users/yoel.garciadiaz/code/string-encoding/.ensime_cache/port
02:33:54.531 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Bound server on port 50363
02:33:54.585 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - New connection accepted
02:33:54.673 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Connection from localhost
02:33:54.674 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Client connected - active clients now: 1
02:33:54.823 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/1 o.e.s.RequestHandler - ConnectionInfoReq
02:33:55.050 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - Environment:
  OS : Mac OS X
  Java : Java HotSpot(TM) 64-Bit Server VM 25.45-b02, Java(TM) SE Runtime Environment 1.8.0_45-b14
  Scala : version 2.11.6
  Ensime : 0.9.10-SNAPSHOT
02:33:55.051 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/2 a.i.TcpListener - Successfully bound to /127.0.0.1:50365
02:33:55.055 INFO  None o.e.s.PortUtil$ - creating portfile /Users/yoel.garciadiaz/code/string-encoding/.ensime_cache/http
02:33:55.056 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - ENSIME HTTP on /127.0.0.1
02:33:55.057 INFO  None o.e.i.DatabaseService - creating the search database...
02:33:55.204 WARN  None c.j.b.BoneCPConfig - JDBC username was not set in config!
02:33:55.463 INFO  None o.e.i.DatabaseService - ... created the search database
02:33:55.473 INFO  None o.e.i.ApachePollingFileWatcherWithWorkaroundImpl - Setting up new file watchers
02:33:55.478 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message ConnectionInfoReq in state awaitingConnectionInfoReq
02:33:55.479 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/1 o.e.s.RequestHandler - received handled message ConnectionInfo(None,EnsimeImplementation(ENSIME),0.8.19) in state receive
02:33:55.625 INFO  None o.e.i.SearchService - findStaleFileChecks
02:33:55.626 INFO  None o.e.i.SearchService - removing 0 stale files from the index
02:33:55.632 INFO  None o.e.i.SearchService - findBases
02:33:55.635 INFO  None o.e.i.SearchService - Indexing bases...
02:33:55.636 DEBUG None o.e.i.SearchService - indexing file:///Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/rt.jar
02:33:55.638 DEBUG None o.e.i.SearchService - indexing file:///Users/yoel.garciadiaz/Downloads/activator-dist-1.3.7/repository/org.scala-lang/scala-library/2.11.6/jars/scala-library.jar
02:33:57.092 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message FullTypeCheckCompleteEvent in state startup
02:33:57.121 ERROR ActorSystem(ENSIME) a.a.ActorSystemImpl - Uncaught fatal error from thread [ENSIME-akka.actor.default-dispatcher-4] shutting down ActorSystem [ENSIME]
java.lang.StackOverflowError: null
	at org.ensime.jerk.JerkConversions$fresh$macro$1992$1.inst$macro$1988(JerkFormats.scala:45) ~[jerk_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.jerk.JerkConversions$fresh$macro$1992$1.inst$macro$1988$lzycompute(JerkFormats.scala:45) ~[jerk_2.11.jar:0.9.10-SNAPSHOT]
...
at org.ensime.jerk.JerkConversions$fresh$macro$1992$1.inst$macro$1988$lzycompute(JerkFormats.scala:45) ~[jerk_2.11.jar:0.9.10-SNAPSHOT]
02:33:57.130 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/2 a.i.TcpListener - Unbinding endpoint /127.0.0.1:50365
02:33:57.131 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/2 a.i.TcpListener - Unbound endpoint /127.0.0.1:50365, stopping listener
02:33:57.131 INFO  akka://ENSIME/system/IO-TCP-STREAM/server-1-%2F127.0.0.1%3A0 a.a.LocalActorRef - Message [akka.io.Tcp$Unbound$] from Actor[akka://ENSIME/system/IO-TCP/selectors/$a/2#849715644] to Actor[akka://ENSIME/system/IO-TCP-STREAM/server-1-%2F127.0.0.1%3A0#684158954] was not delivered. [1] dead letters encountered. This logging can be turn
02:33:57.132 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.SelectionHandler - Monitored actor [Actor[akka://ENSIME/user/ensime-main/tcp-server#-1397826066]] terminated
02:33:57.132 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Closing serverSocketChannel after being stopped
02:33:57.133 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.SelectionHandler - Monitored actor [Actor[akka://ENSIME/user/ensime-main/tcp-server/con1#796259128]] terminated
02:33:57.138 DEBUG EventStream a.e.EventStream - shutting down: StandardOutLogger started
```

**Comment by fommil** [comment]
Please report with ensime atom.
