### ISSUE TITLE
ClassCastException when requesting DocUriAtPointReq over HTTP

### ISSUE THREAD

**Issue by msiegenthaler** [ensime/ensime-server#1267]
I'm writing a Scala plugin for Cloud9, while most other things (compile errors, code completions, formatting) work I run into a problem with the tooltips I want to display:

I get a "ClassCastException: Cannot cast scala.Some to org.ensime.api.EnsimeServerMessage" whenever I call ENSIME with a DocUriAtPointReq (and if I'm correct also on TypeAtPointReq).
It does not seem to depend on the contents of the file or the position (aka point).

I use the 0.9.10-SNAPSHOT from today.

Full request
`
{
  "typehint": "DocUriAtPointReq",
  "file": {
    "file": "/home/ubuntu/workspace/src/main/scala/B.scala"
  },
  "point": {
    "from": 40,
    "to": 40
  }
}
`

Full exception:
`
23:03:58.315 ERROR ActorSystem(ENSIME) a.a.ActorSystemImpl - Error during processing of request HttpRequest(HttpMethod(POST),http://localhost:38541/rpc,List(Host: localhost:38541, Connection: close),HttpEntity.Default(application/json,146,akka.stream.scaladsl.Source@237af028),HttpProtocol(HTTP/1.1))
java.lang.ClassCastException: Cannot cast scala.Some to org.ensime.api.EnsimeServerMessage
        at java.lang.Class.cast(Class.java:3369) ~[na:1.8.0_72]
        at scala.concurrent.Future$$anonfun$mapTo$1.apply(Future.scala:405) ~[scala-library-2.11.7.jar:na]
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[scala-library-2.11.7.jar:na]
        at scala.util.Try$.apply(Try.scala:192) ~[scala-library-2.11.7.jar:na]
        at scala.util.Success.map(Try.scala:237) ~[scala-library-2.11.7.jar:na]
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.7.jar:na]
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.7.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[scala-library-2.11.7.jar:na]
        at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63) ~[scala-library-2.11.7.jar:na]
        at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78) ~[scala-library-2.11.7.jar:na]
        at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55) ~[scala-library-2.11.7.jar:na]
        at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55) ~[scala-library-2.11.7.jar:na]
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) ~[scala-library-2.11.7.jar:na]
        at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54) ~[scala-library-2.11.7.jar:na]
        at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599) ~[scala-library-2.11.7.jar:na]
        at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106) ~[scala-library-2.11.7.jar:na]
        at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597) ~[scala-library-2.11.7.jar:na]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) ~[scala-library-2.11.7.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) ~[scala-library-2.11.7.jar:na]
        at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:266) ~[akka-actor_2.11-2.3.14.jar:na]
        at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:217) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:157) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
        at org.ensime.core.Analyzer$$anonfun$ready$1.applyOrElse(Analyzer.scala:154) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
        at akka.event.LoggingReceive.apply(LoggingReceive.scala:62) ~[akka-actor_2.11-2.3.14.jar:na]
        at akka.event.LoggingReceive.apply(LoggingReceive.scala:50) ~[akka-actor_2.11-2.3.14.jar:na]
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123) ~[scala-library-2.11.7.jar:na]
        at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50) ~[akka-actor_2.11-2.3.14.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.14.jar:na]
        at org.ensime.core.Analyzer.aroundReceive(Analyzer.scala:44) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.14.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.14.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
`

**Comment by fommil** [comment]
http://ensime.github.io/editors/emacs/troubleshooting/

**Comment by fommil** [comment]
OK, you're doing a new client, cool. In that case can you please send your payload in JSON as I suspect this is a marshalling problem.

**Comment by fommil** [comment]
Btw, check the protocol-jerky directory for lots of examples of payloads.

**Comment by rorygraves** [comment]
@msiegenthaler Is it possible to get a test project where you are seeing this error?  I tried a few test and can't replicate the error.  It looks like there is an internal conversion failure within the server, but the two paths I can see don't trigger it for me.

**Comment by msiegenthaler** [comment]
Happens only if accessed via HTTP (not Websocket). Relevant lines are
`def restHandler(in: RpcRequest): Future[EnsimeServerMessage] = {
    (project ? Canonised(in)).mapTo[EnsimeServerMessage].map(Canonised(_))
  }` in WebServerImpl

**Comment by fommil** [comment]
You need to show your source code and payload example. It's impossible to debug this from a stacktrace.

**Comment by rorygraves** [comment]
I disagree - DocUriAtPoint can never work over the rest interface, the response message is of type Option[String] and this http code cases it to EnsimeServerMessage - that call simply cannot work.

**Comment by rorygraves** [comment]
(in this case, generally I agree)

**Comment by fommil** [comment]
I'd be happy killing off the REST API, it was always just a hack for @propensive but somebody wrote a proper vim client instead.

**Comment by rorygraves** [comment]
I agree with that, I had practically forgotten about it.
It has numerous problems
* No async events (typecheck)
* Any endpoint not using ensime types (there are several) 

@msiegenthaler How do you feel about using websockets for all your interactions?

**Comment by msiegenthaler** [comment]
I fixed it with a few added lines, it should now work in all cases where Websockets do.

I agree it's not the best interface to Ensime, but it was the easiest to implement for cloud9. I can't call server side Websocket from the Browser (port not public). But I could probably implement a bridge. The events are no issue, I already handle them (using Websocket on the Server)

I suggest to either get rid of it completely our accept the pull request. The current state is very confusing because most calls work, but some don't. Wasted a lot of time on this, searching the error in the calling code.
