### ISSUE TITLE
Ensime-server doesn't start, java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Crazy-Owl** [ensime/ensime-server#1278]
Hello, I'm using `ensime 20160201.637`. Yesterday the ensime server (in emacs) started just fine, but today I can't make it start.

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Charsets
	at org.ensime.server.Server$.main(Server.scala:109)
	at org.ensime.server.Server.main(Server.scala)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Charsets
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

Process *inferior-ensime-server-tutorial* exited abnormally with code 1
```

I use Typesafe Activator (and `ensime-sbt-command` variable is set according to that fact).

**Comment by Crazy-Owl** [comment]
Okay, I probably have found and resolved my problem. In case anyone else encounter this:

I have moved the Activator dist to another directory and updated my `PATH` accordingly, considering that would be enough. But ensime still tried to find some libraries (guava for example) in the old path. This behavior persisted even on freshly created empty projects.

After some poking around the `.emacs.d` directory I've found that old dirs are coming from `~/.emacs.d/ensime` directory, where a classpath snapshot is stored. After I've deleted that snapshot file, ensime started just fine.

Sorry to bother you with this.

**Comment by timcharper** [comment]
I'm running in to this same error, although not using activator. Trying to launch ensime 2.0.0-SNAPSHOT, getting this:

```
00:22:51.834 ERROR None Server - There was a problem parsing /Users/tim/src/m8e/marathon/.ensime
java.lang.NoClassDefFoundError: com/google/common/base/Charsets
	at org.ensime.server.Server$.main(Server.scala:132)
	at org.ensime.server.Server.main(Server.scala)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Charsets
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 common frames omitted
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Charsets
	at org.ensime.server.Server$.main(Server.scala:132)
	at org.ensime.server.Server.main(Server.scala)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Charsets
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

I found the cache path you described, deleted it. Error persists. Will continue to investigate.

**Comment by timcharper** [comment]
I rather aggressively deleted all versions of ensime from `find  ~/.coursier/ -type d | grep ensime | xargs rm -rf {}`.

I also completely uninstalled ensime from emacs, and restarted Emacs.

Then, I re-followed the instructions to install, evaluating the following:

```
(use-package ensime
  :ensure t
  :pin melpa)
(use-package sbt-mode
  :pin melpa)
(use-package scala-mode
  :pin melpa)
```

(which reinstalled the package).

I regenerated the ensime config, and ran `rm -rf .ensime_cache` in my project.

_somewhere_ in there lies the fix, because, now it is working.
