### ISSUE TITLE
Refactor failure: UnsupportedOperationException: RenameSourceFileChange

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-server#1283]
```
java.lang.UnsupportedOperationException: RenameSourceFileChange(/home/robin/git/censored/Foo.scala,Bar.scala)
	at org.ensime.util.FileEditHelper$.fromChange(FileEditHelper.scala:15) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.RefactoringEnvironment$$anonfun$2.apply(Refactoring.scala:41) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.RefactoringEnvironment$$anonfun$2.apply(Refactoring.scala:41) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.collection.immutable.List.map(List.scala:277) ~[scala-library-2.11.6.jar:na]
	at org.ensime.core.RefactoringEnvironment.performRefactoring(Refactoring.scala:41) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.RefactoringImpl$$anon$7.<init>(Refactoring.scala:190) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.RefactoringImpl$class.doRename(Refactoring.scala:183) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.RichPresentationCompiler.doRename(RichPresentationCompiler.scala:251) [core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.RefactoringImpl$class.prepareRefactor(Refactoring.scala:266) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.RichPresentationCompiler.prepareRefactor(RichPresentationCompiler.scala:251) [core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.RefactoringControl$$anonfun$askPrepareRefactor$1.apply(Refactoring.scala:156) [core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.RefactoringControl$$anonfun$askPrepareRefactor$1.apply(Refactoring.scala:156) [core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.tools.nsc.util.InterruptReq.execute(InterruptReq.scala:26) [scala-compiler-2.11.6.jar:na]
	at scala.tools.nsc.interactive.Global$$anonfun$pollForWork$1.apply$mcV$sp(Global.scala:455) [scala-compiler-2.11.6.jar:na]
	at scala.util.control.Breaks.breakable(Breaks.scala:38) [scala-library-2.11.6.jar:na]
	at scala.tools.nsc.interactive.Global.pollForWork(Global.scala:429) [scala-compiler-2.11.6.jar:na]
	at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:22) [scala-compiler-2.11.6.jar:na]
```

**Comment by greenrd** [comment]
Yup, it is indeed not implemented. I'll take this, and try to integrate it with vc-mode too.

**Comment by fommil** [comment]
`vc-mode`?

**Comment by fommil** [comment]
you mean so refactorings are consider to be atomic commits in the vc? That would be cool.

**Comment by greenrd** [comment]
Yes, that's what I meant. Some trickiness there though.

**Comment by sugakandrey** [comment]
I'll pick this one, if nobody is on it.
