### ISSUE TITLE
Javac error brings down entire server

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#1285]
11:55:07.928 ERROR LocalActorRefProvider(akka://ENSIME) LocalActorRefProvider(akka://ENSIME) - guardian failed, shutting down system
com.sun.tools.javac.util.Abort: null
	at com.sun.tools.javac.comp.Check.completionError(Check.java:258) ~[tools.jar:na]
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:437) ~[tools.jar:na]
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:418) ~[tools.jar:na]
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:473) ~[tools.jar:na]
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:466) ~[tools.jar:na]
	at com.sun.tools.javac.comp.MemberEnter.attribImportType(MemberEnter.java:721) ~[tools.jar:na]
	at com.sun.tools.javac.comp.MemberEnter.visitImport(MemberEnter.java:558) ~[tools.jar:na]
	at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:513) ~[tools.jar:na]
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:401) ~[tools.jar:na]
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:413) ~[tools.jar:na]
	at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:525) ~[tools.jar:na]
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:459) ~[tools.jar:na]
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:401) ~[tools.jar:na]
	at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:876) ~[tools.jar:na]
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:421) ~[tools.jar:na]
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:821) ~[tools.jar:na]
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:491) ~[tools.jar:na]
	at com.sun.tools.javac.comp.Enter.main(Enter.java:469) ~[tools.jar:na]
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:929) ~[tools.jar:na]
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:319) ~[tools.jar:na]
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:362) ~[tools.jar:na]
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:347) ~[tools.jar:na]
	at org.ensime.core.javac.JavaCompiler.typecheckAll(JavaCompiler.scala:173) ~[core_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.javac.JavaCompiler.askTypecheckFiles(JavaCompiler.scala:92) ~[core_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.JavaAnalyzer$$anonfun$receive$1.applyOrElse(JavaAnalyzer.scala:56) ~[core_2.11.jar:0.9.10-SNAPSHOT]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.14.jar:na]
	at org.ensime.core.JavaAnalyzer.aroundReceive(JavaAnalyzer.scala:13) ~[core_2.11.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.14.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
11:55:07.930 ERROR akka://ENSIME/user a.a.OneForOneStrategy - 
com.sun.tools.javac.util.Abort: null
	at com.sun.tools.javac.comp.Check.completionError(Check.java:258) ~[tools.jar:na]
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:437) ~[tools.jar:na]
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:418) ~[tools.jar:na]
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:473) ~[tools.jar:na]
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:466) ~[tools.jar:na]
	at com.sun.tools.javac.comp.MemberEnter.attribImportType(MemberEnter.java:721) ~[tools.jar:na]
	at com.sun.tools.javac.comp.MemberEnter.visitImport(MemberEnter.java:558) ~[tools.jar:na]
	at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:513) ~[tools.jar:na]
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:401) ~[tools.jar:na]
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:413) ~[tools.jar:na]
	at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:525) ~[tools.jar:na]
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:459) ~[tools.jar:na]
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:401) ~[tools.jar:na]
	at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:876) ~[tools.jar:na]
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:421) ~[tools.jar:na]
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:821) ~[tools.jar:na]
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:491) ~[tools.jar:na]
	at com.sun.tools.javac.comp.Enter.main(Enter.java:469) ~[tools.jar:na]
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:929) ~[tools.jar:na]
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:319) ~[tools.jar:na]
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:362) ~[tools.jar:na]
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:347) ~[tools.jar:na]
	at org.ensime.core.javac.JavaCompiler.typecheckAll(JavaCompiler.scala:173) ~[core_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.javac.JavaCompiler.askTypecheckFiles(JavaCompiler.scala:92) ~[core_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.JavaAnalyzer$$anonfun$receive$1.applyOrElse(JavaAnalyzer.scala:56) ~[core_2.11.jar:0.9.10-SNAPSHOT]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.14.jar:na]
	at org.ensime.core.JavaAnalyzer.aroundReceive(JavaAnalyzer.scala:13) ~[core_2.11.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.14.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
11:55:07.947 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - Unbinding endpoint /127.0.0.1:56778
11:55:07.947 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - Unbound endpoint /127.0.0.1:56778, stopping listener

**Comment by fommil** [comment]
Lovely

**Comment by fommil** [comment]
@aemoncannon did your latest PR close this?

**Comment by aemoncannon** [comment]
Yeah, until a new Error pops up : )
