### ISSUE TITLE
Race condition inside presentation compiler triggered by ensime-server

### ISSUE THREAD

**Issue by jix** [ensime/ensime-server#1463]
While working on some code using the chisel3 library, the ensime-server dropped the connections to ensime-atom. A look into the server log revealed the following exception:

```
17:40:48.791 ERROR LocalActorRefProvider(akka://ENSIME) LocalActorRefProvider(akka://ENSIME) - guardian failed, shutting down system
java.lang.AssertionError: assertion failed: Race condition detected: You are running a presentation compiler method outside the PC thread.[phase: <no phase>] Please file a ticket with the current stack trace at https://www.assembla.com/spaces/scala-ide/support/tickets
	at scala.tools.nsc.interactive.Global.assertCorrectThread(Global.scala:535)
	at scala.reflect.internal.Symbols$Symbol.rawInfo(Symbols.scala:1565)
	at scala.reflect.internal.Symbols$Symbol.hasCompleteInfo(Symbols.scala:1543)
	at scala.reflect.internal.Symbols$Symbol.symbolKind(Symbols.scala:2555)
	at scala.reflect.internal.Symbols$Symbol.sanitizedKindString(Symbols.scala:2570)
	at scala.reflect.internal.Symbols$Symbol.kindString(Symbols.scala:2578)
	at scala.reflect.internal.Symbols$Symbol.toString(Symbols.scala:2631)
	at java.lang.String.valueOf(String.java:2994)
	at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:200)
	at scala.reflect.internal.Trees$TreeContextApiImpl.summaryString(Trees.scala:228)
	at scala.reflect.internal.Trees$TreeContextApiImpl.summaryString(Trees.scala:224)
	at org.ensime.core.CompletionControl$class.completionsAt(Completion.scala:127)
	at org.ensime.core.RichPresentationCompiler.completionsAt(RichPresentationCompiler.scala:252)
	at org.ensime.core.RichCompilerControl$class.askCompletionsAt(RichPresentationCompiler.scala:183)
	at org.ensime.core.RichPresentationCompiler.askCompletionsAt(RichPresentationCompiler.scala:252)
	at org.ensime.core.Analyzer$$anonfun$allTheThings$1$$anonfun$applyOrElse$4.apply(Analyzer.scala:202)
	at org.ensime.core.Analyzer$$anonfun$allTheThings$1$$anonfun$applyOrElse$4.apply(Analyzer.scala:200)
	at org.ensime.core.Analyzer.withExisting(Analyzer.scala:307)
	at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:200)
	at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:159)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.ensime.core.Analyzer$$anonfun$ready$1.applyOrElse(Analyzer.scala:156)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:62)
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:50)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at org.ensime.core.Analyzer.aroundReceive(Analyzer.scala:47)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I didn't manage to create a small project to reproduce this bug, but looking at Completion.scala:127, the call causing the exception is just issued to create some debug message. Commenting out that debug message resolved this issue for me.

**Comment by fommil** [comment]
Can you please give a reproduction in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also a good starting point. We are more than happy to help you turn it into an automated test, and discuss ideas on how to fix it. Read the http://ensime.org/contributing guide for more information.

We close tickets that look like a known issue or don't provide the details requested by the template, but it's not the end of the conversation and we will open it up again when there is enough information to go on. This is to improve the quality of our issue tracker and to make it easier for contributors to help.

We will reopen this ticket if you can confirm it is a bug by giving us a **detailed** reproduction. Please read the http://ensime.org/getting_help guide to understand the steps that are required prior to submitting a bug report.

**Comment by fommil** [comment]
if you think a change to `Completion.scala` would help improve the quality of the code, please send a PR with your suggested change.
