### ISSUE TITLE
could not read file: jar:file

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1526]
looks like we have this bug

http://groovyjavathoughts.blogspot.co.uk/2015/01/why-am-i-getting-warning-arguments-left.html

https://github.com/ensime/ensime-server/blob/2.0/core/src/main/scala/org/ensime/indexer/SearchService.scala#L337

which means there is probably another bug hiding under this.

**Comment by rorygraves** [comment]
Looking at this.  For akka logging the correct form is:

```
log.warning(t, "msg") 
```
rather than
```
log.warning("msg", t)
```
Of course for direct use of SLF its the other way round (not a var-args)

**Comment by fommil** [comment]
ok, the problem happens when a jar file is deleted and recreated. The file watcher is too fast or the OS doesn't write the file fast enough or something. I guess the only way we can recover from this is by having a debounce to give the OS some time to write out the file.

**Comment by fommil** [comment]
more importantly, this happens when the jar is deleted and replaced within a very short timeframe.

**Comment by fommil** [comment]
```
org.apache.commons.vfs2.FileSystemException: Could not read file "jar:file:///C:/FOO/scala-2.11/last/BAR.jar!/foo/Bar.class".
	at org.apache.commons.vfs2.provider.AbstractFileObject.getInputStream(AbstractFileObject.java:1317)
	at org.apache.commons.vfs2.provider.DefaultFileContent.getInputStream(DefaultFileContent.java:411)
	at org.ensime.indexer.ClassfileIndexer$class.indexClassfile(ClassfileIndexer.scala:24)
	at org.ensime.indexer.SearchService.indexClassfile(SearchService.scala:28)
	at org.ensime.indexer.SearchService.org$ensime$indexer$SearchService$$extractSymbols(SearchService.scala:212)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1$$anonfun$apply$7$$anonfun$apply$8.apply(SearchService.scala:196)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1$$anonfun$apply$7$$anonfun$apply$8.apply(SearchService.scala:196)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1$$anonfun$apply$7.apply(SearchService.scala:196)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1$$anonfun$apply$7.apply(SearchService.scala:183)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.package$.blocking(package.scala:123)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1.apply(SearchService.scala:183)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1.apply(SearchService.scala:183)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:634)
	at java.util.zip.ZipFile.getInputStream(ZipFile.java:347)
	at java.util.jar.JarFile.getInputStream(JarFile.java:412)
	at org.apache.commons.vfs2.provider.zip.ZipFileObject.doGetInputStream(ZipFileObject.java:174)
	at org.apache.commons.vfs2.provider.AbstractFileObject.getInputStream(AbstractFileObject.java:1301)
	... 19 common frames omitted

```

**Comment by fommil** [comment]
I'm finding it exceptionally difficult to test this because basically when an error happens in the indexing actor, it's a dead end and nowhere to send that message. However, the failure has minimal impact because it just results in not updating the jars... they'll be caught on a restart.

That said, I did find a semaphore leak.

**Comment by fommil** [comment]
still getting this. I wonder if it's more a problem of Apache VFS closing the jar in a different thread or something.

**Comment by fommil** [comment]
I've got a manual reproduction, but I can't see how to test it. Start up ensime against ensime-server and type (on a full compile) `testingSimpleJar/clean` to see this

```
22:20:41.799 WARN  akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - Restarting the Presentation Compiler
org.apache.commons.vfs2.FileSystemException: Could not determine the last modified timestamp of "file:///home/fommil/Projects/ensime-server/testing/simpleJar/target/scala-2.11/testingsimplejar_2.11-1.0.0-SNAPSHOT.jar" because it does not exist.
	at org.apache.commons.vfs2.provider.DefaultFileContent.getLastModifiedTime(DefaultFileContent.java:171)
	at org.ensime.indexer.database.DatabaseService$FileCheck$.apply(DatabaseService.scala:128)
	at org.ensime.indexer.IndexingQueueActor$$anonfun$receive$1$$anonfun$applyOrElse$2$$anonfun$apply$13$$anonfun$apply$14.apply(SearchService.scala:359)
	at org.ensime.indexer.IndexingQueueActor$$anonfun$receive$1$$anonfun$applyOrElse$2$$anonfun$apply$13$$anonfun$apply$14.apply(SearchService.scala:356)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.ensime.indexer.IndexingQueueActor$$anonfun$receive$1$$anonfun$applyOrElse$2$$anonfun$apply$13.apply(SearchService.scala:356)
	at org.ensime.indexer.IndexingQueueActor$$anonfun$receive$1$$anonfun$applyOrElse$2$$anonfun$apply$13.apply(SearchService.scala:351)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
22:20:42.146 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message FullTypeCheckCompleteEvent in state ready
```

**Comment by fommil** [comment]
oh, this is fixed in the 1.0 branch.

**Comment by fommil** [comment]
backporting the fix for that small problem I can reproduce locally by typing `testingSimpleJar/clean` and `testingSimpleJar/packageBin` in quick succession (or just a `touch testing/simpleJar/target/scala-2.11/testingsimplejar_2.11-1.0.0-SNAPSHOT.jar`)

```
org.apache.commons.vfs2.FileSystemException: Could not read file "jar:file:///home/fommil/Projects/ensime-server/testing/simpleJar/target/scala-2.11/testingsimplejar_2.11-1.0.0-SNAPSHOT.jar!/baz/Foo.class".
	at org.apache.commons.vfs2.provider.AbstractFileObject.getInputStream(AbstractFileObject.java:1317)
	at org.apache.commons.vfs2.provider.DefaultFileContent.getInputStream(DefaultFileContent.java:411)
	at org.ensime.indexer.ClassfileIndexer$class.indexClassfile(ClassfileIndexer.scala:24)
	at org.ensime.indexer.SearchService.indexClassfile(SearchService.scala:28)
	at org.ensime.indexer.SearchService.org$ensime$indexer$SearchService$$extractSymbols(SearchService.scala:212)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1$$anonfun$apply$7$$anonfun$apply$8.apply(SearchService.scala:196)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1$$anonfun$apply$7$$anonfun$apply$8.apply(SearchService.scala:196)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1$$anonfun$apply$7.apply(SearchService.scala:196)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1$$anonfun$apply$7.apply(SearchService.scala:183)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.package$.blocking(package.scala:123)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1.apply(SearchService.scala:183)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1.apply(SearchService.scala:183)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:634)
	at java.util.zip.ZipFile.getInputStream(ZipFile.java:347)
	at java.util.jar.JarFile.getInputStream(JarFile.java:412)
	at org.apache.commons.vfs2.provider.zip.ZipFileObject.doGetInputStream(ZipFileObject.java:174)
	at org.apache.commons.vfs2.provider.AbstractFileObject.getInputStream(AbstractFileObject.java:1301)
	... 19 common frames omitted

```

**Comment by fommil** [comment]
I think this is because of the aggressive vfs.nuke-ing that we're doing. I guess we need to unregister the file when we close it.
