### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1592]
looks like we have a file leak in the graphpocalypse. I get this about twice when I run `it:test` on a stock ArchLinux system (I think file handle limit is 1000).

```
[info]   Cause: java.io.FileNotFoundException: /tmp/1471699337373-0/.ensime_cache/graph-2.3/field.pcl (Too many open files)
[info]   at java.io.RandomAccessFile.open(Native Method)
[info]   at java.io.RandomAccessFile.<init>(RandomAccessFile.java:241)
[info]   at com.orientechnologies.orient.core.storage.fs.OFileClassic.openChannel(OFileClassic.java:791)
[info]   at com.orientechnologies.orient.core.storage.fs.OFileClassic.create(OFileClassic.java:528)
[info]   at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.addFile(OWOWCache.java:1053)
[info]   at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.addFile(OWOWCache.java:370)
[info]   at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.addFile(O2QCache.java:174)
[info]   at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.addFile(ODurableComponent.java:178)
[info]   at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.create(OPaginatedCluster.java:186)
[info]   at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addClusterInternal(OAbstractPaginatedStorage.java:3349)
[info]   at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doAddCluster(OAbstractPaginatedStorage.java:3330)
[info]   at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addCluster(OAbstractPaginatedStorage.java:511)
[info]   at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.addCluster(ODatabaseDocumentTx.java:1274)
[info]   at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClusters(OSchemaShared.java:1224)
[info]   at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClusters(OSchemaShared.java:1192)
[info]   at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:382)
[info]   at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:363)
[info]   at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:95)
[info]   at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1309)
[info]   at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1307)
[info]   at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1817)
[info]   at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1307)
[info]   at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1274)
[info]   at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1245)
[info]   at org.ensime.indexer.orientdb.syntax.package$RichOrientGraph.createVertexFrom(SimpleOrient.scala:92)
[info]   at org.ensime.indexer.graph.GraphService.<init>(GraphService.scala:205)
[info]   at org.ensime.indexer.SearchService.<init>(SearchService.scala:77)
[info]   at org.ensime.fixture.IsolatedSearchServiceFixture$$anonfun$withSearchService$1.apply(SearchServiceFixture.scala:15)
[info]   at org.ensime.fixture.IsolatedSearchServiceFixture$$anonfun$withSearchService$1.apply(SearchServiceFixture.scala:14)
[info]   at org.ensime.fixture.IsolatedSourceResolverFixture$$anonfun$withSourceResolver$2.apply(SourceResolverFixture.scala:27)
[info]   at org.ensime.fixture.IsolatedSourceResolverFixture$$anonfun$withSourceResolver$2.apply(SourceResolverFixture.scala:24)
[info]   at org.ensime.fixture.IsolatedEnsimeConfigFixture$$anonfun$withEnsimeConfig$1.apply(EnsimeConfigFixture.scala:171)
[info]   at org.ensime.fixture.IsolatedEnsimeConfigFixture$$anonfun$withEnsimeConfig$1.apply(EnsimeConfigFixture.scala:171)
[info]   at org.ensime.util.file.package$.withTempDir(file.scala:42)
[info]   at org.ensime.fixture.IsolatedEnsimeConfigFixture$class.withEnsimeConfig(EnsimeConfigFixture.scala:170)
[info]   at org.ensime.core.RichPresentationCompilerSpec.withEnsimeConfig(RichPresentationCompilerSpec.scala:52)
[info]   at org.ensime.fixture.IsolatedSourceResolverFixture$class.withSourceResolver(SourceResolverFixture.scala:24)
[info]   at org.ensime.core.RichPresentationCompilerSpec.withSourceResolver(RichPresentationCompilerSpec.scala:52)
[info]   at org.ensime.fixture.IsolatedSearchServiceFixture$class.withSearchService(SearchServiceFixture.scala:14)
[info]   at org.ensime.core.RichPresentationCompilerSpec.withSearchService(RichPresentationCompilerSpec.scala:52)
[info]   at org.ensime.fixture.IsolatedRichPresentationCompilerFixture$$anonfun$withRichPresentationCompiler$1$$anonfun$apply$1.apply(RichPresentationCompilerFixture.scala:86)
[info]   at org.ensime.fixture.IsolatedRichPresentationCompilerFixture$$anonfun$withRichPresentationCompiler$1$$anonfun$apply$1.apply(RichPresentationCompilerFixture.scala:84)
[info]   at org.ensime.fixture.IsolatedTestKitFixture$class.withTestKit(TestKitFixture.scala:41)
[info]   at org.ensime.core.RichPresentationCompilerSpec.withTestKit(RichPresentationCompilerSpec.scala:52)
[info]   at org.ensime.fixture.IsolatedRichPresentationCompilerFixture$$anonfun$withRichPresentationCompiler$1.apply(RichPresentationCompilerFixture.scala:84)
[info]   at org.ensime.fixture.IsolatedRichPresentationCompilerFixture$$anonfun$withRichPresentationCompiler$1.apply(RichPresentationCompilerFixture.scala:83)
[info]   at org.ensime.fixture.IsolatedEnsimeVFSFixture$class.withVFS(EnsimeVFSFixture.scala:18)
[info]   at org.ensime.core.RichPresentationCompilerSpec.withVFS(RichPresentationCompilerSpec.scala:52)
[info]   at org.ensime.fixture.IsolatedRichPresentationCompilerFixture$class.withRichPresentationCompiler(RichPresentationCompilerFixture.scala:83)
[info]   at org.ensime.core.RichPresentationCompilerSpec.withRichPresentationCompiler(RichPresentationCompilerSpec.scala:52)
[info]   at org.ensime.core.ReallyRichPresentationCompilerFixture$class.withPresCompiler(RichPresentationCompilerSpec.scala:496)
[info]   at org.ensime.core.RichPresentationCompilerSpec.withPresCompiler(RichPresentationCompilerSpec.scala:52)
[info]   at org.ensime.core.ReallyRichPresentationCompilerFixture$class.withPosInCompiledSource(RichPresentationCompilerSpec.scala:502)
[info]   at org.ensime.core.RichPresentationCompilerSpec.withPosInCompiledSource(RichPresentationCompilerSpec.scala:52)
[info]   at org.ensime.core.RichPresentationCompilerSpec$$anonfun$19.apply(RichPresentationCompilerSpec.scala:278)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1684)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at org.ensime.core.RichPresentationCompilerSpec.org$ensime$util$EnsimeSpec$$super$withFixture(RichPresentationCompilerSpec.scala:52)
[info]   at org.ensime.util.EnsimeSpec$class.withFixture(EnsimeSpec.scala:49)
[info]   at org.ensime.core.RichPresentationCompilerSpec.withFixture(RichPresentationCompilerSpec.scala:52)
[info]   at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1681)
[info]   at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1694)
[info]   at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1694)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:299)
[info]   at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1694)
[info]   at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1691)
[info]   at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1752)
[info]   at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1752)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:406)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:394)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:394)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:383)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:420)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:394)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:394)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:389)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:471)
[info]   at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1752)
[info]   at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1691)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1691)
[info]   at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1798)
[info]   at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1798)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[info]   at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1798)
[info]   at org.scalatest.FlatSpec.run(FlatSpec.scala:1691)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:470)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[info]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by pascr** [comment]
It could be linked to orientechnologies/orientdb#6269 so bumping orientdb to 2.2.4 could fix it. The default limit is 1024 but it can be configured with the "storage.openFiles.limit" property.

**Comment by fommil** [comment]
cool, thanks @pascr ! we'll try that out :smile: does it work on Java 7?

**Comment by pascr** [comment]
@fommil yes it should work, it's built against 1.6 AFAIK

**Comment by nagarajasr** [comment]
@fommil @pascr orientdb 2.2.4 apparently has a critical bug that can damage data: https://github.com/orientechnologies/orientdb/issues/6638#issuecomment-245297083 
so you might want to consider upgrading to later version.

**Comment by pascr** [comment]
@fommil Is it still happenning after the #1599 fix?

**Comment by fommil** [comment]
Best ask @sugakandrey I've not had a chance to try it out yet

**Comment by sugakandrey** [comment]
I was able to reproduce it pre efe184ed82c9bf509b2420361d796634dca1bf80 with `ulimit -Sn 1024` on test machine, but testing shows that it's gone for good with orient version upgrade. I'm closing this, if somehow it reappears we can reconsider.

**Comment by fommil** [comment]
I'll try on my machine again at the weekend to really confirm

**Comment by sugakandrey** [comment]
@fommil Cool.
