### ISSUE TITLE
parse this generic string

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1614]
I have a jar that I don't control with a sig string like this

```
Lscala/runtime/AbstractFunction1<Lfoo/cm/model/BazModelExtensions$BazModelExtender<Lfoo/cm/bar/gx/IOVPfooableBazModel<Lfoo/cmx/iov/gx/GXIOV;Lfoo/cm/core/WowParameters;Lfoo/cm/core/Wow;Lfoo/cm/core/PlaceState;Lfoo/cm/core/PlaceModelConfiguration;Lfoo/cm/core/DonePlaceModel;>;>;Lfoo/fuzz/exodus/product/model/iov/binding/ThingStyleBinding$$anon$1$$anonfun$$lessinit$greater$1$$anonfun$apply$1$$<init>_map_14$node;>;Lscala/Serializable;
```

which fails parsing.

1. it would be good to log this out, but continue.
2. check if this is really valid and handle if it is

**Comment by fommil** [comment]
almost certainly this is causing refresh indexing to not complete

**Comment by fommil** [comment]
@asznajder any chance you could take a look? I'm not sure if the generic is valid or not

**Comment by fommil** [comment]
stacktrace is

```
7 rules mismatched at error location:
  ...ture/ |:-118 /GenericClassSig/ |:-118 /GenericClassSigWithArgs/ /GenericArgs/ + / | /ExtendsObject/ /ExtendsObjectStar/ '*'
  ...ClassSig/ |:-118 /GenericClassSigWithArgs/ /GenericArgs/ + / | /GenericArgWithSignature/ ? / | /LowerBoundary/ /LowerB/ '-'
  ...ClassSig/ |:-118 /GenericClassSigWithArgs/ /GenericArgs/ + / | /GenericArgWithSignature/ ? / | /UpperBoundary/ /UpperB/ '+'
  ...gs/ + / | /GenericArgWithSignature/ /FieldTypeSignature/ | /GenericClassSig/ | /GenericClassSigWithArgs/ /ClassNameSig/ 'L'
  ... + / | /GenericArgWithSignature/ /FieldTypeSignature/ | /GenericClassSig/ | /GenericClassSigWithoutArgs/ /ClassNameSig/ 'L'
  ...|:-118 /GenericClassSigWithArgs/ /GenericArgs/ + / | /GenericArgWithSignature/ /FieldTypeSignature/ | /GenericArraySig/ '['
  ...assSig/ |:-118 /GenericClassSigWithArgs/ /GenericArgs/ + / | /GenericArgWithSignature/ /FieldTypeSignature/ | /TypeVar/ 'T'

	at org.ensime.indexer.SignatureParser$.parseGeneric(SignatureParser.scala:19)
	at org.ensime.indexer.ClassfileIndexer$AsmCallback.visit(ClassfileIndexer.scala:54)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.ensime.indexer.ClassfileIndexer$class.indexClassfile(ClassfileIndexer.scala:28)
	at org.ensime.indexer.SearchService.indexClassfile(SearchService.scala:29)
	at org.ensime.indexer.SearchService.org$ensime$indexer$SearchService$$extractSymbols(SearchService.scala:216)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1$$anonfun$apply$7$$anonfun$apply$8.apply(SearchService.scala:201)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1$$anonfun$apply$7$$anonfun$apply$8.apply(SearchService.scala:201)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1$$anonfun$apply$7.apply(SearchService.scala:201)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1$$anonfun$apply$7.apply(SearchService.scala:188)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.package$.blocking(package.scala:123)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1.apply(SearchService.scala:188)
	at org.ensime.indexer.SearchService$$anonfun$extractSymbolsFromClassOrJar$1.apply(SearchService.scala:188)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by fommil** [comment]
Turns out this is not a valid generic string name. Which leads me to believe that ensime is doing the right thing here. Rather than bend over backwards to support a broken ASM, I suggest we push the problem onto the user (me) to exclude the broken jar from indexing.

**Comment by fommil** [comment]
Of course, if it's trivial to catch and skip exceptions, maybe we should, with very noisy logs.
