### ISSUE TITLE
Lucene write lock left behind

### ISSUE THREAD

**Issue by dragos** [ensime/ensime-server#1623]
I may not be very clear on the shutdown procedure, but it looks to me like the `IndexerService` never closes the Lucene writer. I regularly see `writer.lock` files inside `.ensime_cache`. Sometimes (not always, surprisingly!) Ensime crashes on startup because the `.ensime_cache/index-..` is locked.

I believe a `writer.close()` should be added somewhere in the IndexerService, and probably a new `shutdown` method needs to be added too. The [SimpleLucene](https://github.com/ensime/ensime-server/blob/2.0/core/src/main/scala/org/ensime/indexer/lucene/SimpleLucene.scala) wrapper doesn't even expose `close()`.

Feel free to close it if I misunderstood something. I'm happy to add the call, but I wouldn't do the work if this is known and expected

EDIT: exception trace:

```
[2016-11-02 19:06:32,103] INFO org.apache.commons.vfs2.impl.StandardFileSystemManager - Using "/var/folders/d0/p2vnqqmx4355wcfvjsbhd39c0000gn/T/vfs_cache" as temporary files store.
[2016-11-02 19:06:34,216] ERROR akka.actor.OneForOneStrategy - exception during creation
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:166)
	at akka.actor.ActorCell.create(ActorCell.scala:596)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at akka.util.Reflect$.instantiate(Reflect.scala:66)
	at akka.actor.ArgsReflectConstructor.produce(Props.scala:355)
	at akka.actor.Props.newActor(Props.scala:255)
	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
	at akka.actor.ActorCell.create(ActorCell.scala:578)
	... 9 common frames omitted
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/Users/dragos/workspace/.../.ensime_cache/index-1.4/write.lock
	at org.apache.lucene.store.Lock.obtain(Lock.java:89)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:707)
	at org.ensime.indexer.lucene.SimpleLucene.<init>(SimpleLucene.scala:69)
	at org.ensime.indexer.IndexService.<init>(IndexService.scala:85)
	at org.ensime.indexer.SearchService.<init>(SearchService.scala:64)
	at org.ensime.core.Project.<init>(Project.scala:45)
	... 18 common frames omitted
```

**Comment by fommil** [comment]
just checked and I have one hanging around too... but it is usually harmless. I've never had startup fail because of a locked file... can you please try to capture the log when this next happens?

**Comment by dragos** [comment]
Sure

**Comment by dragos** [comment]
Added a stack trace. Any idea what might be going on here? Why it fails randomly?

**Comment by fommil** [comment]
You're using ensime 1.0 instead of dev? We upgraded lucene, that could help.

**Comment by fommil** [comment]
Are you maybe restarting a server too quickly after closing one? We've noticed in the Emacs tests that one has to wait a few seconds before the jvm releases the db file locks.

**Comment by fommil** [comment]
I think this might have been fixed with the latest PR, which shuts down lucene properly (although I guess a hard kill of the server can't avoid this). Reopen if you still see it.
