### ISSUE TITLE
Deamon thread keeps the ensime process alive

### ISSUE THREAD

**Issue by dragos** [ensime/ensime-server#1640]
I have a bunch of zombies on my system, all due to a few non-daemon threads

```
"Thread-2" #20 prio=5 os_prio=31 tid=0x00007ffeb2f70800 nid=0x6c03 waiting on condition [0x0000700001ef0000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007413a30d8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
	at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)
	at sun.nio.fs.AbstractWatchService.take(AbstractWatchService.java:118)
	at org.ensime.filewatcher.FileWatchService$$anonfun$4.apply(FileWatchService.scala:179)
	at org.ensime.filewatcher.FileWatchService$$anonfun$4.apply(FileWatchService.scala:179)
	at scala.util.Try$.apply(Try.scala:192)
	at org.ensime.filewatcher.FileWatchService.org$ensime$filewatcher$FileWatchService$$monitor(FileWatchService.scala:179)
	at org.ensime.filewatcher.FileWatchService$$anon$1.run(FileWatchService.scala:65)
	at java.lang.Thread.run(Thread.java:745)
```

There are a bunch of other thread-pool threads that stick around but seem to be doing nothing:

```
pool-1-thread-1" #17 prio=5 os_prio=31 tid=0x00007ffeb6a2a000 nid=0x6603 waiting on condition [0x0000700001be7000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007406cb920> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rorygraves** [comment]
I thought daemon threads did not prevent shutdown.

**Comment by dragos** [comment]
You're right.. I picked the wrong one. I'll update the ticket with the other ones.

**Comment by rorygraves** [comment]
Yep definately a bug

**Comment by fommil** [comment]
@dragos is this still happening?

**Comment by fommil** [comment]
This is expected though... otherwise the server shuts down because everything is a daemon.

**Comment by fommil** [comment]
Non-daemon.

**Comment by dragos** [comment]
How do you shut it down though? Notice that leftover files leads to crashes if I do `System.exit`

**Comment by fommil** [comment]
the DB backend is completely rewritten now, so try `sys.exit` again.
