### ISSUE TITLE
support java editing when using jar urls

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1648]
loose ends after #1637

we are not supporting java editing when using jar entries (as opposed to extracted files) because we don't fully understand how to add support in the JDK.

To reproduce the problem, remove the `.copy(...)` of the definition of `original` in `JavaCompilerSpec`. To see previous attempts, look in the history of the `JavaCompiler` file for references to `NotSoSimpleJavaFileObject`

@hardmettle

**Comment by fommil** [comment]
@hedefalk a caveat to be aware of with the new jar url feature

**Comment by gaydenko** [comment]
I have java project. On jumping to external dep file (`M-.` in emacs) I get:
```
06.08 22:15:51.521 jazz E URI must have a path: jar:file:///usr/lib/jvm/java-8-jdk/src.zip!/java/lang/String.java
java.lang.IllegalArgumentException: URI must have a path: jar:file:///usr/lib/jvm/java-8-jdk/src.zip!/java/lang/String.java
	at javax.tools.SimpleJavaFileObject.<init>(SimpleJavaFileObject.java:68)
	at org.ensime.core.javac.JavaCompiler$JavaObjectEnsimeFile.<init>(JavaCompiler.scala:151)
	at org.ensime.core.javac.JavaCompiler.createJavaFileObject(JavaCompiler.scala:62)
	at org.ensime.core.javac.JavaCompiler.internSource(JavaCompiler.scala:70)
	at org.ensime.core.javac.JavaCompiler.$anonfun$typecheckForUnits$1(JavaCompiler.scala:127)
```
Ensime's `JavaCompiler` uses `SimpleJavaFileObject` this way:
```Scala
  private class JavaObjectEnsimeFile(
      val f: EnsimeFile,
      val contents: Option[String]
  ) extends SimpleJavaFileObject(f.uri, JavaFileObject.Kind.SOURCE) {
    override def getCharContent(ignoreEncodingErrors: Boolean): CharSequence =
      contents.getOrElse(f.readStringDirect)
  }
```
At the case of external archive `EnsimeFile` is `ArchiveFile` powered with this implementation:
```Scala
  implicit class RichArchiveFile(val archive: ArchiveFile) extends RichEnsimeFile {
    ....
    override def uri: URI = URI.create(s"jar:${archive.jar.toUri}!${archive.entry}") // path is null (opaque)
    ....
  }
```
This `uri` returns `null` on `uri.getPath`, and this is the reason of the problem: `SimpleJavaFileObject`'s constructor check it:
```Java
     protected SimpleJavaFileObject(URI uri, Kind kind) {
         // null checks
         uri.getClass();
         kind.getClass();
         if (uri.getPath() == null)
             throw new IllegalArgumentException("URI must have a path: " + uri);
         this.uri = uri;
         this.kind = kind;
     }
```

**Comment by fommil** [comment]
@gaydenko this is all known and explored in the history mentioned in the ticket / linked PR. If you'd like to have a go at solving this, that's where I'd suggest looking first of all. It will involve learning the JDK API.

**Comment by gaydenko** [comment]
I will try that No So Simple for Java projects upcoming days and will report here. At least I can jump to external sources now with that `JavaFileObject` implementation :)

**Comment by fommil** [comment]
to be clear though, we never got it working... that's just a guess about where to start. We think there is something else still needed to workaround problems in the JDK API.

**Comment by fommil** [comment]
this was the final ticket in the 2.0.0 milestone and since nobody really seems to care about it, I'm pushing it to the backlog.
