### ISSUE TITLE
MatchError on NoSymbol in askDocSignatureAtPoint

### ISSUE THREAD

**Issue by dragos** [ensime/ensime-server#1713]
This seems to completely kill my ensime server (no requests are served anymore). I don't see why that should be the case though, so maybe the error is on my side. But nevertheless ensime should be a bit more robust when things aren't found by the PC.

```
scala.MatchError: <none> (of class scala.reflect.internal.Symbols$NoSymbol)
	at org.ensime.core.SymbolToFqn$class.toFqn(SymbolToFqn.scala:89)
	at org.ensime.core.RichPresentationCompiler.toFqn(RichPresentationCompiler.scala:280)
	at org.ensime.core.DocFinding$class.javaFqn(DocFinding.scala:55)
	at org.ensime.core.DocFinding$class.linkName(DocFinding.scala:88)
	at org.ensime.core.DocFinding$class.docSig$1(DocFinding.scala:115)
	at org.ensime.core.DocFinding$class.docSignature(DocFinding.scala:117)
	at org.ensime.core.RichPresentationCompiler.docSignature(RichPresentationCompiler.scala:280)
	at org.ensime.core.RichCompilerControl$$anonfun$askDocSignatureAtPoint$1$$anonfun$apply$3.apply(RichPresentationCompiler.scala:89)
	at org.ensime.core.RichCompilerControl$$anonfun$askDocSignatureAtPoint$1$$anonfun$apply$3.apply(RichPresentationCompiler.scala:89)
	at scala.Option.flatMap(Option.scala:171)
	at org.ensime.core.RichCompilerControl$$anonfun$askDocSignatureAtPoint$1.apply(RichPresentationCompiler.scala:89)
	at org.ensime.core.RichCompilerControl$$anonfun$askDocSignatureAtPoint$1.apply(RichPresentationCompiler.scala:89)
	at scala.tools.nsc.util.InterruptReq.execute(InterruptReq.scala:26)
	at scala.tools.nsc.interactive.Global$$anonfun$pollForWork$1.apply$mcV$sp(Global.scala:457)
	at scala.util.control.Breaks.breakable(Breaks.scala:38)
	at scala.tools.nsc.interactive.Global.pollForWork(Global.scala:431)
	at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:22)
```

**Comment by fommil** [comment]
*sigh* this is exactly the sort of thing akka is supposed to magically handle for us, but never does...

**Comment by ktonga** [comment]
@fommil That's happening to me a lot as well, I think the server should have sme sort of mechanism to make itself stay in a good shape. But I'm afraid if I propose it you will ask me to implement it :stuck_out_tongue_closed_eyes: 

It can monitor the quality of the req/resp metrics and trigger an internal restart of the PC and anything related if the response times go high (ensime-vim timeouts some requests after waiting 10s for the server to respond) or a high rate of empty or failed responses is detected. Or and internal health-check that can be consulted periodically.

After all that's the akka motto "let it crash" and the main idea behind the supervision strategy stuff.

What you reckon?
