### ISSUE TITLE
filewatcher not cleaning up properly on Windows

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1752]
Sometimes the file watcher hangs on shutdown... e.g. in the `ReverseLookupsSpec` (could be the shared testkit).

As workaround, we just don't wait for the actor system to shutdown in the shared testkit fixture.

```
"default-akka.actor.default-dispatcher-6" #21 prio=5 os_prio=0 tid=0x000000005b896800 nid=0xf9c in Object.wait() [0x000000005ed3d000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000ab26d5b0> (a sun.nio.fs.AbstractPoller$Request)
        at java.lang.Object.wait(Object.java:502)
        at sun.nio.fs.AbstractPoller$Request.awaitResult(AbstractPoller.java:196)
        - locked <0x00000000ab26d5b0> (a sun.nio.fs.AbstractPoller$Request)
        at sun.nio.fs.AbstractPoller.invoke(AbstractPoller.java:225)
        at sun.nio.fs.AbstractPoller.cancel(AbstractPoller.java:133)
        at sun.nio.fs.WindowsWatchService$WindowsWatchKey.cancel(WindowsWatchService.java:196)
        at org.ensime.filewatcher.FileWatchService$WatchKeyManager$.$anonfun$removeObservers$1(FileWatchService.scala:460)
        at org.ensime.filewatcher.FileWatchService$WatchKeyManager$$$Lambda$2203/1045679152.apply(Unknown Source)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
        at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:178)
        at org.ensime.filewatcher.FileWatchService$WatchKeyManager$.removeObservers(FileWatchService.scala:454)
        at org.ensime.filewatcher.Watcher.shutdown(FileWatchService.scala:28)
        at org.ensime.indexer.Java7WatchServiceBuilder$EnsimeWatcher$1.shutdown(FileWatchers.scala:247)
        at org.ensime.indexer.Java7WatchServiceBuilder$EnsimeWatcher$1.shutdown$(FileWatchers.scala:244)
        at org.ensime.indexer.Java7WatchServiceBuilder$$anon$1.shutdown(FileWatchers.scala:250)
        at org.ensime.indexer.SourceWatcher.$anonfun$shutdown$1(FileWatchers.scala:94)
        at org.ensime.indexer.SourceWatcher.$anonfun$shutdown$1$adapted(FileWatchers.scala:94)
        at org.ensime.indexer.SourceWatcher$$Lambda$2212/1556831139.apply(Unknown Source)
        at scala.collection.immutable.List.foreach(List.scala:378)
        at org.ensime.indexer.SourceWatcher.shutdown(FileWatchers.scala:94)
        at org.ensime.core.Project.$anonfun$postStop$1(Project.scala:122)
        at org.ensime.core.Project$$Lambda$2211/1156903670.apply$mcV$sp(Unknown Source)
```

**Comment by fommil** [comment]
looks related to `WatchKey.cancel` being unreliable on Windows https://bugs.openjdk.java.net/browse/JDK-8029516
