### ISSUE TITLE
bump fastparse to >= 0.4.3

### ISSUE THREAD

**Issue by MasseGuillaume** [ensime/ensime-server#1784]
scalameta 1.8.0 uses fastparse 0.4.3.

If I put both ensime core 2.0.0-M1 and scalameta 1.8.0 on my classpath it crash with:

```
sbtRunner[ERROR] java.lang.NoSuchMethodError: fastparse.all$.CharPred(Lscala/Function1;)Lfastparse/core/Parser;
sbtRunner[ERROR]        at org.ensime.sexp.SexpParser$.<init>(SexpParser.scala:46)
sbtRunner[ERROR]        at org.ensime.sexp.SexpParser$.<clinit>(SexpParser.scala)
sbtRunner[ERROR]        at org.ensime.sexp.package$EnrichedString$.parseSexp$extension(package.scala:21)
sbtRunner[ERROR]        at org.ensime.config.EnsimeConfigProtocol$.parse(EnsimeConfigProtocol.scala:32)
sbtRunner[ERROR]        at com.olegych.scastie.sbt.SbtActor.<init>(SbtActor.scala:40)
sbtRunner[ERROR]        at com.olegych.scastie.sbt.SbtMain$.$anonfun$main$1(SbtMain.scala:31)
sbtRunner[ERROR]        at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
sbtRunner[ERROR]        at akka.actor.Props.newActor(Props.scala:213)
sbtRunner[ERROR]        at akka.actor.ActorCell.newActor(ActorCell.scala:563)
sbtRunner[ERROR]        at akka.actor.ActorCell.create(ActorCell.scala:589)
sbtRunner[ERROR]        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
sbtRunner[ERROR]        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
sbtRunner[ERROR]        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
sbtRunner[ERROR]        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
sbtRunner[ERROR]        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
sbtRunner[ERROR]        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
sbtRunner[ERROR]        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
sbtRunner[ERROR]        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
sbtRunner[ERROR]        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

context: https://github.com/scalacenter/scastie/pull/223

I attached the dependency graph: https://drive.google.com/open?id=0B5glSD3SCWJrTjVLeFlrNlBPX1U

**Comment by fommil** [comment]
already done in #1783 :wink: I just need to fix up a wart in the 2.10 build.

**Comment by MasseGuillaume** [comment]
Awesome thanks!

**Comment by fommil** [comment]
btw @MasseGuillaume if you're depending on ensime-server as a binary dependency, you need to make your application GPLv3. You can depend on the wire protocol and use whatever license you want, much to my annoyance.
