### ISSUE TITLE
OrientDB: You have reached maximum pool size for given partition

### ISSUE THREAD

**Issue by dragos** [ensime/ensime-server#1808]
Using Ensime on Sbt sources I get the following crashes quite regularly when trying to hyperlink:

```
[2017-06-20 16:22:39,633] DEBUG org.github.dragos.vscode.ensime.EnsimeProjectServer - Forwarding SymbolAtPointReq(Right(SourceFileInfo(RawFile(/Users/dragos/workspace/oss/sbt/compile/integration/src/main/scala/sbt/compiler/AggressiveCompile.scala),Some(...),None)),7247)
[2017-06-20 16:22:39,633] DEBUG org.github.dragos.vscode.ensime.EnsimeProjectServer - Forwarding SymbolAtPointReq(Right(SourceFileInfo(RawFile(/Users/dragos/workspace/oss/sbt/compile/integration/src/main/scala/sbt/compiler/AggressiveCompile.scala),Some(...),None)),7247)
[2017-06-20 16:22:39,634] ERROR org.ensime.core.RichPresentationCompiler - Error during askOption
java.lang.IllegalStateException: You have reached maximum pool size for given partition
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:243)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:144)
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:77)
        at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:135)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory$1.getGraph(OrientGraphFactory.java:84)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:221)
        at org.ensime.indexer.orientdb.syntax.package$.withGraph(SimpleOrient.scala:164)
        at org.ensime.indexer.orientdb.syntax.package$$anonfun$withGraphAsync$1$$anonfun$apply$1.apply(SimpleOrient.scala:176)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
        at scala.concurrent.package$.blocking(package.scala:123)
        at org.ensime.indexer.orientdb.syntax.package$$anonfun$withGraphAsync$1.apply(SimpleOrient.scala:176)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by fommil** [comment]
you mean on the github.com/sbt/sbt project?

Is this 2.0.0-M2 ?

**Comment by dragos** [comment]
Yes, and yes.

**Comment by pallix** [comment]
I got the same on a hello world project when using the ensime-refactor functions.

**Comment by atk91** [comment]
Why this issue was closed? What does that label mean?

**Comment by jozi-k** [comment]
Bug bankruptcy was declared as clean start of new development cycle (3.0). As a consequence all issues had been closed, as noone knew if they are still relevant.
