### ISSUE TITLE
DeserializationException causes ensime-server to crash

### ISSUE THREAD

**Issue by timcharper** [ensime/ensime-server#1878]
If you invoke the emacs function `(ensime-db-location-at-point (point))` while the debugger is not active, it returns `nil` (because [the condition in this sexp is nil, and consequently evaluates to nil](https://github.com/ensime/ensime-emacs/blob/v2.0.1/ensime-debug.el#L685)). This is then passed to `ensime-rpc-debug-value`, which causes the tcp-server actor of ensime server to crash with the following exception:

```
org.ensime.server.protocol.swank.SwankRPCFormatException: Invalid rpc request (swank:debug-value nil)
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:870)
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:859)
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:21)
	at org.ensime.server.SwankProtocol.decode(SwankProtocol.scala:17)
	at org.ensime.server.tcp.TCPConnectionActor.repeatedDecode(TCPConnectionActor.scala:108)
	at org.ensime.server.tcp.TCPConnectionActor.attemptProcess(TCPConnectionActor.scala:97)
	at org.ensime.server.tcp.TCPConnectionActor$$anonfun$incoming$1.applyOrElse(TCPConnectionActor.scala:49)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor.aroundReceive(Actor.scala:513)
	at akka.actor.Actor.aroundReceive$(Actor.scala:511)
	at org.ensime.server.tcp.TCPConnectionActor.aroundReceive(TCPConnectionActor.scala:17)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.ensime.sexp.DeserializationException: Unable to parse SexpNil
	at org.ensime.sexp.formats.package$.deserializationError(package.scala:7)
	at org.ensime.server.protocol.swank.SwankProtocolCommon$TraitFormatAlt.read(SwankFormats.scala:66)
	at org.ensime.sexp.formats.LegacyLowPriorityProductFormats$HListFormat$$anon$4.read(LegacyProductFormats.scala:41)
	at org.ensime.sexp.formats.LegacyLowPriorityProductFormats$HListFormat$$anon$4.read(LegacyProductFormats.scala:35)
	at org.ensime.server.protocol.swank.SwankProtocolRequest$$anon$73.read(SwankFormats.scala:678)
	at org.ensime.server.protocol.swank.SwankProtocolRequest$$anon$73.read(SwankFormats.scala:672)
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:21)
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestReader$.read(SwankFormats.scala:847)
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestReader$.read(SwankFormats.scala:808)
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:21)
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.$anonfun$read$16(SwankFormats.scala:864)
	at scala.util.Try$.apply(Try.scala:209)
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:864)
	... 19 common frames omitted
```

Followed by the actor crashing:

```
13:46:30.457 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/3 a.i.SelectionHandler - Monitored actor [Actor[akka://ENSIME/user/ensime-main/tcp-server/con3#-12557968]] terminated
```

The tcp-server actor recovers (manually reconnecting works), but Emacs does not recover its connection.

Unsure if it is better for clients to automatically-recover their connection, or if it would be better to not kill the TCP connection.

Ensime server version: 2.0.0
Ensime emacs version: 2.0.1

**Comment by timcharper** [comment]
Well, I went to reproduce this issue again, and I can't. So, closing this seems like the right thing to do.
