### ISSUE TITLE
Timeout exceptions break LSP communication

### ISSUE THREAD

**Issue by laughedelic** [ensime/ensime-server#1948]
After LSP server launches, most of the time it fails on some request with a timeout exception. I don't understand why, but the exception is written in the _beginning_ of the `pc.stdout.log` log, so it may be hard to notice if you just look at the appended messages in the end of the file. 

The problem is that the server stops communicating, so the client cannot do anything and the server has to be restarted manually.

I see 2 different exceptions:

```
Exception in thread "main" akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://ENSIME/user/server#1606763570]] after [5000 ms]. Sender[null] sent message of type "org.ensime.api.StructureViewReq".
	at akka.pattern.PromiseActorRef$.$anonfun$defaultOnTimeout$1(AskSupport.scala:595)
	at akka.pattern.PromiseActorRef$.$anonfun$apply$1(AskSupport.scala:605)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:140)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:866)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:109)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:103)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:864)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:328)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:279)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:283)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:235)
	at java.lang.Thread.run(Thread.java:748)
```

Is probably about this timeout:

https://github.com/ensime/ensime-server/blob/483b2d43ca9abc06a21e0e8ab07751c75d1470a9/lsp/src/main/scala/org/ensime/lsp/ensime/EnsimeLanguageServer.scala#L99

And

```
Exception in thread "main" java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:142)
	at org.ensime.lsp.ensime.EnsimeLanguageServer.$anonfun$documentSymbols$7(EnsimeLanguageServer.scala:466)
	at scala.Option.map(Option.scala:146)
	at org.ensime.lsp.ensime.EnsimeLanguageServer.documentSymbols(EnsimeLanguageServer.scala:466)
	at org.ensime.lsp.core.LanguageServer$ResponseHandler$$anonfun$buildHandler$1.applyOrElse(LanguageServer.scala:49)
	at org.ensime.lsp.core.LanguageServer$ResponseHandler$$anonfun$buildHandler$1.applyOrElse(LanguageServer.scala:21)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:220)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at org.ensime.lsp.core.LanguageServer.$anonfun$connection$1(LanguageServer.scala:92)
	at org.ensime.lsp.core.Connection.handleMessage(Connection.scala:113)
	at org.ensime.lsp.core.Connection.start(Connection.scala:127)
	at org.ensime.lsp.core.LanguageServer.start(LanguageServer.scala:96)
	at org.ensime.lsp.ensime.EnsimeLanguageServer.start(EnsimeLanguageServer.scala:102)
	at org.ensime.server.Server$.startLspServer(Server.scala:182)
	at org.ensime.server.Server$.main(Server.scala:193)
	at org.ensime.server.Server.main(Server.scala)
```

Points here:

https://github.com/ensime/ensime-server/blob/483b2d43ca9abc06a21e0e8ab07751c75d1470a9/lsp/src/main/scala/org/ensime/lsp/ensime/EnsimeLanguageServer.scala#L466

It's the same for other requests, they all have such `Await` call with a hardcoded 5s timeout.

**Comment by rorygraves** [comment]
Thanks @laughedelic 
The code has timeouts to try and provide a responsive behaviour. Certainly some of our older clients used to block on requests so we timed out and set an empty response back.
So the timeout should be turned into a sensible response further up (which sounds like its not happening).

If nobody gets to it beforehand I will try and take a look later in the weekend/early next week .

**Comment by zainab-ali** [comment]
I'm halfway through implementing this. 

It would be cleaner if all functions on the `LanguageServer` returned a `Future[A]` instead of throwing.  We could wait on the future in `Connection.handleMessage`, and return an `InternalError` response if it times out, or anything else errors.

I have a strong dislike of futures, but that's what's in the codebase currently.  I'd be very happy to code this with a cats effect IO or a Monix Task.
