### ISSUE TITLE
Ensime server crashes on startup with some dependencies in build file

### ISSUE THREAD

**Issue by ashkan-leo** [ensime/ensime-server#1965]
Leave this list and include an `x` in the relevant boxes:

- [x] I have read http://ensime.org/getting_help/
- [x] I have followed the troubleshooting guide for my text editor
- [x] I have asked in http://gitter.im/ensime/ensime-server
- [x] I have included a link to an example project
- [x] I have included exact bug reproduction instructions

Hi!
I'm having issues making this work. Ensime server fails to start in this project: https://github.com/ashkan-leo/ensime-test

Steps to reproduce:
run `ensimeConfig` and then `M-x ensime` in Emacs.

The following exception will be shown in the ensime buffer:
```

Starting ENSIME server: /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/lib/tools.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/ensime/monkeys_2.11/2.0.1/monkeys_2.11-2.0.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/javax/activation/activation/1.1/activation-1.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.11/2.5.11/akka-actor_2.11-2.5.11.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.11/2.5.11/akka-slf4j_2.11-2.5.11.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/ensime/api_2.11/2.0.1/api_2.11-2.0.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/ow2/asm/asm/6.1.1/asm-6.1.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/ow2/asm/asm-analysis/6.1.1/asm-analysis-6.1.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/ow2/asm/asm-commons/6.1.1/asm-commons-6.1.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/ow2/asm/asm-tree/6.1.1/asm-tree-6.1.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/ow2/asm/asm-util/6.1.1/asm-util-6.1.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/tinkerpop/blueprints/blueprints-core/2.6.0/blueprints-core-2.6.0.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/commons-digester/commons-digester/1.8/commons-digester-1.8.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/commons-lang/commons-lang/2.4/commons-lang-2.4.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/apache/commons/commons-vfs2/2.1/commons-vfs2-2.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap-lru/1.4.1/concurrentlinkedhashmap-lru-1.4.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/ensime/core_2.11/2.0.1/core_2.11-2.0.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/fastparse-utils_2.11/1.0.0/fastparse-utils_2.11-1.0.0.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/fastparse_2.11/1.0.0/fastparse_2.11-1.0.0.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/carrotsearch/hppc/0.6.0/hppc-0.6.0.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.6.0/jackson-annotations-2.6.0.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.6.0/jackson-core-2.6.0.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.6.0/jackson-databind-2.6.0.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.2.3/jaxb-impl-2.2.3.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/ensime/jerky_2.11/2.0.1/jerky_2.11-2.0.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/codehaus/jettison/jettison/1.3.3/jettison-1.3.3.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/4.5.0/jna-4.5.0.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna-platform/4.5.0/jna-platform-4.5.0.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/ensime/json_2.11/2.0.1/json_2.11-2.0.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.25/log4j-over-slf4j-1.7.25.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/apache/lucene/lucene-analyzers-common/6.4.2/lucene-analyzers-common-6.4.2.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/apache/lucene/lucene-core/6.4.2/lucene-core-6.4.2.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/typelevel/macro-compat_2.11/1.1.1/macro-compat_2.11-1.1.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/javax/mail/mail/1.4.7/mail-1.4.7.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-buffer/4.1.22.Final/netty-buffer-4.1.22.Final.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-codec/4.1.22.Final/netty-codec-4.1.22.Final.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-codec-http/4.1.22.Final/netty-codec-http-4.1.22.Final.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-common/4.1.22.Final/netty-common-4.1.22.Final.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-handler/4.1.22.Final/netty-handler-4.1.22.Final.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-resolver/4.1.22.Final/netty-resolver-4.1.22.Final.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-transport/4.1.22.Final/netty-transport-4.1.22.Final.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-refactoring/org.scala-refactoring.library_2.11.8/0.13.0/org.scala-refactoring.library_2.11.8-0.13.0.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/orientechnologies/orientdb-client/2.2.33/orientdb-client-2.2.33.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/orientechnologies/orientdb-core/2.2.33/orientdb-core-2.2.33.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/orientechnologies/orientdb-graphdb/2.2.33/orientdb-graphdb-2.2.33.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/orientechnologies/orientdb-server/2.2.33/orientdb-server-2.2.33.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/orientechnologies/orientdb-tools/2.2.33/orientdb-tools-2.2.33.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/ensime/s-express_2.11/2.0.1/s-express_2.11-2.0.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-debugger/scala-debugger-api_2.11/1.1.0-M3/scala-debugger-api_2.11-1.1.0-M3.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-debugger/scala-debugger-macros_2.11/1.1.0-M3/scala-debugger-macros_2.11-1.1.0-M3.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.11/0.7.0/scala-java8-compat_2.11-0.7.0.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/ensime/server_2.11/2.0.1/server_2.11-2.0.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/chuusai/shapeless_2.11/2.3.2/shapeless_2.11-2.3.2.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.0.1/snappy-java-1.1.0.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.11/0.1.4/sourcecode_2.11-0.1.4.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/stax/stax-api/1.0.1/stax-api-1.0.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/ensime/swanky_2.11/2.0.1/swanky_2.11-2.0.1.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/lib/tools.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/ensime/util_2.11/2.0.1/util_2.11-2.0.1.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.12/scala-compiler-2.11.12.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.12/scala-reflect-2.11.12.jar:/Users/aaleali/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scalap/2.11.12/scalap-2.11.12.jar -Dscala.classpath.closeZip=true -XX:ReservedCodeCacheSize=128m -XX:MaxMetaspaceSize=256m -Xss2m -Xms512m -Xmx4g -XX:MaxMetaspaceSize=256m -XX:StringTableSize=1000003 -XX:+UnlockExperimentalVMOptions -XX:SymbolTableSize=1000003 -Densime.index.no.reverse.lookups=true -Densime.config=/Users/aaleali/w/ensime-test/.ensime org.ensime.server.Server
12:31:25.558 WARN  None o.e.c.EnsimeConfigProtocol$ - RawFile(/Users/aaleali/w/ensime-test/target/scala-2.11/classes) does not exist, creating
12:31:25.573 WARN  None o.e.c.EnsimeConfigProtocol$ - RawFile(/Users/aaleali/w/ensime-test/target/scala-2.11/test-classes) does not exist, creating
12:31:25.758 INFO  None a.e.s.Slf4jLogger - Slf4jLogger started
12:31:25.765 DEBUG EventStream(akka://ENSIME) a.e.EventStream - logger log1-Slf4jLogger started
12:31:25.769 DEBUG EventStream(akka://ENSIME) a.e.EventStream - Default Loggers started
12:31:25.829 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "/var/folders/31/gjbjq8b11z9fgnxnvy3lkn3rc5y5f6/T/vfs_cache" as temporary files store.
12:31:25.901 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Successfully bound to /127.0.0.1:55582
12:31:25.904 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Bound server on port 55582
12:31:25.904 INFO  None o.e.s.PortUtil$ - creating port file: /Users/aaleali/w/ensime-test/.ensime_cache/port
12:31:26.179 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - Environment:
12:31:26.180 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   OS : Mac OS X
12:31:26.180 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Java : Java HotSpot(TM) 64-Bit Server VM 25.202-b08, Java(TM) SE Runtime Environment 1.8.0_202-b08
12:31:26.180 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Scala version: version 2.11.12
12:31:26.181 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Ensime : 2.0.1
12:31:26.181 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Heap Size : 3817865216
12:31:26.181 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built with Scala version: 2.11.12
12:31:26.182 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built with sbt version: 0.13.17
12:31:26.182 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built from git sha: 5dc1afd7d96569ef965899a1f78e6c5603ed82ec
12:31:26.182 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built on: 2018-03-26
12:31:26.184 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - ENSIME HTTP on /127.0.0.1:55583
12:31:26.184 INFO  None o.e.s.PortUtil$ - creating port file: /Users/aaleali/w/ensime-test/.ensime_cache/http
12:31:26.190 ERROR None Server - Shutdown requested due to internal error: Monitor actor failed with class akka.actor.ActorInitializationException - akka.actor.ActorInitializationException: akka://ENSIME/user/ensime-main/project: exception during creation
12:31:26.252 INFO  None Server - Shutting down the ActorSystem
12:31:26.252 INFO  None Server - Awaiting actor system termination
12:31:26.255 ERROR akka://ENSIME/user/ensime-main o.e.s.ServerActor - Error with monitor actor akka://ENSIME/user/ensime-main/project: exception during creation
akka.actor.ActorInitializationException: akka://ENSIME/user/ensime-main/project: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:193)
	at akka.actor.ActorCell.create(ActorCell.scala:671)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:525)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.util.Reflect$.instantiate(Reflect.scala:65)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:626)
	at akka.actor.ActorCell.create(ActorCell.scala:652)
	... 9 common frames omitted
Caused by: org.apache.commons.vfs2.FileSystemException: Unknown message with code "URI "c:" is not an absolute file name. in /Users/aaleali/.ivy2/cache/org.testng/testng/srcs/testng-6.9.4-sources.jar =>".
	at org.ensime.vfs.package$RichVFS$.org$ensime$vfs$RichVFS$$withContext$extension(EnsimeVFS.scala:79)
	at org.ensime.vfs.package$RichVFS$.vjar$extension(EnsimeVFS.scala:92)
	at org.ensime.indexer.SourceResolver$$anonfun$6.apply(SourceResolver.scala:96)
	at org.ensime.indexer.SourceResolver$$anonfun$6.apply(SourceResolver.scala:94)
	at scala.collection.immutable.List.map(List.scala:288)
	at org.ensime.indexer.SourceResolver.<init>(SourceResolver.scala:94)
	at org.ensime.core.Project.<init>(Project.scala:50)
	... 18 common frames omitted
Caused by: org.apache.commons.vfs2.FileSystemException: URI "c:" is not an absolute file name.
	at org.apache.commons.vfs2.provider.local.GenericFileNameParser.extractRootPrefix(GenericFileNameParser.java:54)
	at org.apache.commons.vfs2.provider.local.LocalFileNameParser.parseUri(LocalFileNameParser.java:84)
	at org.apache.commons.vfs2.provider.url.UrlFileNameParser.parseUri(UrlFileNameParser.java:65)
	at org.apache.commons.vfs2.provider.AbstractFileProvider.parseUri(AbstractFileProvider.java:202)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveName(DefaultFileSystemManager.java:930)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveName(DefaultFileSystemManager.java:849)
	at org.apache.commons.vfs2.provider.zip.ZipFileSystem.init(ZipFileSystem.java:92)
	at org.apache.commons.vfs2.provider.AbstractVfsContainer.addComponent(AbstractVfsContainer.java:56)
	at org.apache.commons.vfs2.provider.AbstractFileProvider.addFileSystem(AbstractFileProvider.java:108)
	at org.apache.commons.vfs2.provider.AbstractLayeredFileProvider.createFileSystem(AbstractLayeredFileProvider.java:88)
	at org.apache.commons.vfs2.provider.AbstractLayeredFileProvider.findFile(AbstractLayeredFileProvider.java:61)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:804)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:760)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:709)
	at org.ensime.vfs.package$RichVFS$$anonfun$vjar$extension$1.apply(EnsimeVFS.scala:92)
	at org.ensime.vfs.package$RichVFS$$anonfun$vjar$extension$1.apply(EnsimeVFS.scala:92)
	at org.ensime.vfs.package$RichVFS$.org$ensime$vfs$RichVFS$$withContext$extension(EnsimeVFS.scala:77)
	... 24 common frames omitted
12:31:26.526 INFO  None Server - Shutting down the Netty channel
12:31:26.529 INFO  None Server - Shutdown complete

Process *ENSIME-ensime-test* exited abnormally with code 1
```

**Comment by akilegaspi** [comment]
Are you using Windows or Mac? Seems like the function is trying to call a `c:` which is a windows style directory
