### ISSUE TITLE
stacktracing work in sbt-mode

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#565]
it looks like the stacktraces from sbt don't get caught by the stacktrace-mode because of sbt's stupid insistence on capturing/rewriting stdout. e.g. this is not highlighted: 

```
[info] - should parse a simple config *** FAILED ***
[info]   scala.MatchError: Expecting a list of string values at key: :compiler-args (of class java.lang.String)
[info]   at org.ensime.util.SExpExplorer$.matchError(SExp.scala:6)
[info]   at org.ensime.util.SExpMapExplorer$$anonfun$getStringList$1.apply(SExp.scala:56)
[info]   at org.ensime.util.SExpMapExplorer$$anonfun$getStringList$1.apply(SExp.scala:56)
[info]   at scala.Option.getOrElse(Option.scala:120)
[info]   at org.ensime.util.SExpMapExplorer.getStringList(SExp.scala:55)
[info]   at org.ensime.util.SExpMapExplorer.getStringList(SExp.scala:54)
[info]   at org.ensime.config.EnsimeConfig$.parse(EnsimeConfig.scala:75)
[info]   at org.ensime.server.Server$.readEnsimeConfig(Server.scala:117)
[info]   at org.ensime.config.EnsimeConfigSpec$$anonfun$test$1.apply(EnsimeConfigSpec.scala:24)
[info]   at org.ensime.config.EnsimeConfigSpec$$anonfun$test$1.apply(EnsimeConfigSpec.scala:21)
[info]   ...
[info] 36mRun completed in 988 milliseconds.0m
```

**Comment by fommil** [comment]
found myself wanting this again recently

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#179
