### ISSUE TITLE
formatting preferences not supported: alignSingleLineCaseStatements.maxArrowIndent

### ISSUE THREAD

**Issue by ajevans85** [ensime/ensime-server#709]
**UPDATE** (`fommil`): 

the SexpFormat for the scalariform preferences doesn't like the name in the `alignSingleLineCaseStatements.maxArrowIndent` property (also, check that the parser allows the dot).

------

Hi,

I'm trying to get ensime setup using the latest build from elpa, when I try to start ensime I get the below.
 
```
[info] Running org.ensime.server.Server 
[info] 10:37:29.462 [main] ERROR org.ensime.util.SExpParser$ - Failure whilst reading SExp: `)' expected but `(' found
[error] Exception in thread "main" java.lang.ClassCastException: org.ensime.util.NilAtom$ cannot be cast to org.ensime.util.SExpList
[error] 	at org.ensime.server.Server$.readEnsimeConfig(Server.scala:54)
[error] 	at org.ensime.server.Server$.main(Server.scala:31)
[error] 	at org.ensime.server.Server.main(Server.scala)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run 'last compile:run' for the full output.
[error] (compile:run) Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run 'last compile:run' for the full output.
[error] (compile:run) Nonzero exit code returned from runner: 1
[error] Total time: 0 s, completed 17/12/2014 10:37:29 AM

Process *inferior-ensime-server-brahma* exited abnormally with code 1[
```

**Comment by fommil** [comment]
I think I know what this is: it's a symptom of the mess of #792
