### ISSUE TITLE
SexpParser should allow symbols with dots in their name

### ISSUE THREAD

**Issue by raboof** [ensime/ensime-server#874]
I'm using version 0.1.5 of ensime-sbt and version 20150305.651 of the ensime plugin in emacs.

I'm new to all this so not so comfortable tracking versions yet. It seems ensime-sbt generates the following line in my .ensime:

```
:formatting-prefs (:alignSingleLineCaseStatements.maxArrowIndent 90 :preserveDanglingCloseParenthesis t :alignSingleLineCaseStatements t :alignParameters nil :doubleIndentClassDeclaration t :rewriteArrowSymbols t)
```

Which cannot be parsed by ensime-server:

```
Starting ENSIME server: /usr/lib/jvm/java-8-openjdk-amd64/bin/java -classpath /usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar:/home/aengelen/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar:/home/aengelen/.ivy2/cache/org.ensime/ensime_2.11/jars/ensime_2.11-0.9.10-SNAPSHOT.jar:/home/aengelen/.ivy2/cache/org.ensime/server_2.11/jars/server_2.11-0.9.10-SNAPSHOT.jar:/home/aengelen/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.5.jar:/home/aengelen/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.5.jar:/home/aengelen/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.3.jar:/home/aengelen/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.3.jar:/home/aengelen/.ivy2/cache/org.ensime/api_2.11/jars/api_2.11-0.9.10-SNAPSHOT.jar:/home/aengelen/.ivy2/cache/com.github.stacycurl/pimpathon-core_2.11/jars/pimpathon-core_2.11-1.2.0.jar:/home/aengelen/.ivy2/cache/com.danieltrinh/scalariform_2.11/jars/scalariform_2.11-0.1.5.jar:/home/aengelen/.ivy2/cache/org.ensime/swank_2.11/jars/swank_2.11-0.9.10-SNAPSHOT.jar:/home/aengelen/.ivy2/cache/org.ensime/sexpress_2.11/jars/sexpress_2.11-0.9.10-SNAPSHOT.jar:/home/aengelen/.ivy2/cache/com.chuusai/shapeless_2.11/bundles/shapeless_2.11-2.0.0.jar:/home/aengelen/.ivy2/cache/org.parboiled/parboiled-scala_2.11/jars/parboiled-scala_2.11-1.1.7.jar:/home/aengelen/.ivy2/cache/org.parboiled/parboiled-core/jars/parboiled-core-1.1.7.jar:/home/aengelen/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.11/jars/akka-slf4j_2.11-2.3.9.jar:/home/aengelen/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.3.9.jar:/home/aengelen/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar:/home/aengelen/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.2.jar:/home/aengelen/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.2.jar:/home/aengelen/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.10.jar:/home/aengelen/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.10.jar:/home/aengelen/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.10.jar:/home/aengelen/.ivy2/cache/com.h2database/h2/jars/h2-1.4.182.jar:/home/aengelen/.ivy2/cache/com.typesafe.slick/slick_2.11/bundles/slick_2.11-2.1.0.jar:/home/aengelen/.ivy2/cache/com.jolbox/bonecp/bundles/bonecp-0.8.0.RELEASE.jar:/home/aengelen/.ivy2/cache/com.google.guava/guava/bundles/guava-15.0.jar:/home/aengelen/.ivy2/cache/org.apache.commons/commons-vfs2/jars/commons-vfs2-2.0.jar:/home/aengelen/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.1.jar:/home/aengelen/.ivy2/cache/org.apache.maven.scm/maven-scm-api/jars/maven-scm-api-1.4.jar:/home/aengelen/.ivy2/cache/org.codehaus.plexus/plexus-utils/jars/plexus-utils-1.5.6.jar:/home/aengelen/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svnexe/jars/maven-scm-provider-svnexe-1.4.jar:/home/aengelen/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svn-commons/jars/maven-scm-provider-svn-commons-1.4.jar:/home/aengelen/.ivy2/cache/regexp/regexp/jars/regexp-1.3.jar:/home/aengelen/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-4.7.2.jar:/home/aengelen/.ivy2/cache/org.apache.lucene/lucene-analyzers-common/jars/lucene-analyzers-common-4.7.2.jar:/home/aengelen/.ivy2/cache/org.ow2.asm/asm-commons/jars/asm-commons-5.0.3.jar:/home/aengelen/.ivy2/cache/org.ow2.asm/asm-tree/jars/asm-tree-5.0.3.jar:/home/aengelen/.ivy2/cache/org.ow2.asm/asm/jars/asm-5.0.3.jar:/home/aengelen/.ivy2/cache/org.ow2.asm/asm-util/jars/asm-util-5.0.3.jar:/home/aengelen/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.11.5.jar:/home/aengelen/.ivy2/cache/org.scala-refactoring/org.scala-refactoring.library_2.11/jars/org.scala-refactoring.library_2.11-0.6.2.jar:/home/aengelen/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.6.jar:/home/aengelen/.ivy2/cache/io.spray/spray-can_2.11/bundles/spray-can_2.11-1.3.2.jar:/home/aengelen/.ivy2/cache/io.spray/spray-io_2.11/bundles/spray-io_2.11-1.3.2.jar:/home/aengelen/.ivy2/cache/io.spray/spray-util_2.11/bundles/spray-util_2.11-1.3.2.jar:/home/aengelen/.ivy2/cache/io.spray/spray-http_2.11/bundles/spray-http_2.11-1.3.2.jar -XX:MaxPermSize=512m -Xmx2048m -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -Densime.config=/home/aengelen/xebia/customername/projectname/.ensime org.ensime.server.Server
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Exception in thread "main" org.parboiled.errors.ParsingException: Invalid :
Invalid input '9', expected Comment, ' ', '\n', '\r', '\t', '\f' or ')' (line 10, pos 67):
 :formatting-prefs (:alignSingleLineCaseStatements.maxArrowIndent 90 :preserveDanglingCloseParenthesis t :alignSingleLineCaseStatements t :alignParameters nil :doubleIndentClassDeclaration t :rewriteArrowSymbols t)
                                                                  ^

	at org.ensime.util.ParboiledParser$$anonfun$parse$1.apply(ParboiledParser.scala:23)
	at org.ensime.util.ParboiledParser$$anonfun$parse$1.apply(ParboiledParser.scala:23)
	at scala.Option.getOrElse(Option.scala:121)
	at org.ensime.util.ParboiledParser$class.parse(ParboiledParser.scala:22)
	at org.ensime.sexp.SexpParser$.parse(SexpParser.scala:11)
	at org.ensime.sexp.PimpedString.parseSexp(package.scala:17)
	at org.ensime.config.EnsimeConfigProtocol$.parse(EnsimeConfigProtocol.scala:24)
	at org.ensime.server.Server$.main(Server.scala:36)
	at org.ensime.server.Server.main(Server.scala)

Process *inferior-ensime-server-projectname*<4> exited abnormally with code 1
```

So it seems it's using ensime 0.9.10:

```
/home/aengelen/.ivy2/cache/org.ensime/ensime_2.11/jars/ensime_2.11-0.9.10-SNAPSHOT.jar:/home/aengelen/.ivy2/cache/org.ensime/server_2.11/jars/server_2.11-0.9.10-SNAPSHOT.jar
```

It's unclear to me though which of these versions is out of date and how to select a newer one.

**Comment by fommil** [comment]
I think the problem is actually your project's custom scalariform settings. It looks like we're not handling `alignSingleLineCaseStatements.maxArrowIndent` which is probably because it has a space in it https://github.com/mdr/scalariform/blob/master/scalariform/src/main/scala/scalariform/formatter/preferences/PreferenceDescriptor.scala#L138

I suspect our SExp parser needs to be updated to handle dots in symbol names https://github.com/ensime/ensime-server/blob/master/server/src/main/scala/org/ensime/util/SExpParser.scala#L48

I'll add this to the 1.0 roadmap, but for now just remove that entry from your `.ensime`

**Comment by fommil** [comment]
Do an ensime-update (in about 30 mins) and this should be fixed :-)

**Comment by raboof** [comment]
Confirmed, thanks!
