### ISSUE TITLE
Exception in DatabaseService on initial boot after generating config for ensime project.

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#906]
23:51:48.332 [main] INFO  o.a.c.v.i.StandardFileSystemManager - Using "/var/folders/4b/gj73872j2vs9wxtkrvg3dzb80000gn/T/vfs_cache" as temporary files store.
23:51:49.619 [main] INFO  org.ensime.indexer.ClassfileWatcher - Setting up new file watchers
23:51:50.129 [main] WARN  com.jolbox.bonecp.BoneCPConfig - JDBC username was not set in config!
23:51:50.129 [main] WARN  com.jolbox.bonecp.BoneCPConfig - JDBC password was not set in config!
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Table "FILECHECKS" not found; SQL statement:
select x2."id", x2."filename", x2."timestamp" from "FILECHECKS" x2 [42102-182]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readTableOrView(Parser.java:5242)
	at org.h2.command.Parser.readTableFilter(Parser.java:1227)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1866)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1975)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1860)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1681)
	at org.h2.command.Parser.parseSelect(Parser.java:1669)
	at org.h2.command.Parser.parsePrepared(Parser.java:433)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:446)
	at org.h2.engine.Session.prepareCommand(Session.java:388)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1190)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:72)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:666)
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1193)
	at scala.slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:152)
	at scala.slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:389)
	at scala.slick.jdbc.StatementInvoker.results(StatementInvoker.scala:32)
	at scala.slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:64)
	at scala.slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at scala.slick.jdbc.Invoker$class.build(Invoker.scala:47)
	at scala.slick.jdbc.StatementInvoker.build(StatementInvoker.scala:16)
	at scala.slick.jdbc.Invoker$class.list(Invoker.scala:39)
	at scala.slick.jdbc.StatementInvoker.list(StatementInvoker.scala:16)
	at org.ensime.indexer.DatabaseService$$anonfun$knownFiles$1.apply(DatabaseService.scala:41)
	at org.ensime.indexer.DatabaseService$$anonfun$knownFiles$1.apply(DatabaseService.scala:40)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
	at org.ensime.indexer.DatabaseService.knownFiles(DatabaseService.scala:40)
	at org.ensime.indexer.SearchService.refresh(SearchService.scala:67)
	at org.ensime.core.Project.<init>(Project.scala:91)
	at org.ensime.server.Server.<init>(Server.scala:76)
	at org.ensime.server.Server$.initialiseServer(Server.scala:48)
	at org.ensime.server.Server$.main(Server.scala:44)
	at org.ensime.server.Server.main(Server.scala)

**Comment by aemoncannon** [comment]
Deleting cache cleared this up. I think I got into a funny state because I tried booting without a config once.

**Comment by fommil** [comment]
Hmm, yeah, probably the H2 schema creation didn't finish

**Comment by aemoncannon** [comment]
Is this something we should catch?  Seems like forgetting to gen a config
would be a not-uncommon failure case.

**Comment by fommil** [comment]
I think you caught it in the few milliseconds between creating the first table, and not the second one. Extremely rare.

**Comment by aemoncannon** [comment]
Yeah I'm quick like that : ) sgtm

**Comment by greenrd** [comment]
I don't think this is as rare as you think. I've just seen this, and there's a dupe as well: https://github.com/ensime/ensime-server/issues/739

**Comment by fommil** [comment]
it's got an easy and well documented fix, so we won't be putting in code to handle this corner case.

**Comment by fommil** [comment]
send in a PR to catch the Exception and point people at the ticket if you think it's worth it, though :smile:

**Comment by aemoncannon** [comment]
Would it be difficult to not create db until we've got a config?

**Comment by aemoncannon** [comment]
Actually I don't see how it could have anything to do with config, as we
check that long before the database is created.

**Comment by fommil** [comment]
we already have a config at the point when the server starts up. The only way this kind of corruption could occur is if the user stops the server when it is in the middle of creating the database schema, and then starts it up again. The best way to recover from that is just to nuke the `.ensime_cache` (as with anything else that is a corruption of the cache).
