### ISSUE TITLE
Requirement failed: FileSourceFileInfo does not exist

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-server#930]
Whenever I visit a new Scala file in emacs, I get an RPC abort and the following exception:

```
16:55:38.893 [default-akka.actor.default-dispatcher-155] ERROR org.ensime.core.Analyzer - Error handling RPC: java.lang.IllegalArgumentException: requirement failed: FileSourceFileInfo(/home/user/foo/Bar.scala) does not exist
java.lang.IllegalArgumentException: requirement failed: FileSourceFileInfo(/home/user/foo/Bar.scala) does not exist
	at scala.Predef$.require(Predef.scala:233) ~[scala-library.jar:na]
	at org.ensime.core.Analyzer$$anonfun$handleReloadFiles$1.apply(Analyzer.scala:257) ~[ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Analyzer$$anonfun$handleReloadFiles$1.apply(Analyzer.scala:256) ~[ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at org.ensime.core.Analyzer.handleReloadFiles(Analyzer.scala:256) ~[ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Analyzer.process(Analyzer.scala:161) ~[ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Analyzer$$anonfun$receive$1.applyOrElse(Analyzer.scala:83) ~[ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[akka-actor_2.10-2.3.8.jar:na]
	at org.ensime.core.Analyzer.aroundReceive(Analyzer.scala:20) ~[ensime_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.10-2.3.8.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.10-2.3.8.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) [akka-actor_2.10-2.3.8.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:221) [akka-actor_2.10-2.3.8.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231) [akka-actor_2.10-2.3.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
```

Thereafter, emacs keeps complaining that the RPC has aborted, so I have to save the file, kill the buffer and then reopen the file, and then it works.

**Comment by rorygraves** [comment]
Hi Robin,

That definately sounds like a bug.  It looks like its killed the actor handling the request (and probably the actor system).  Is your project in a normal sbt project/structure?  (src/main etc) - I know there are some issues with files in unexpected places.  

Either way this is definately a bug and I will create a ticket for it.

Thanks

**Comment by rorygraves** [comment]
Duh, its already an issue - will try and look at it soon.

**Comment by fommil** [comment]
I removed that class in my latest PR.

**Comment by fommil** [comment]
actually the error is that `/home/user/foo/Bar.scala` does not exist, not that the class doesn't exist.

**Comment by greenrd** [comment]
I'm using Qubes OS, which is basically Fedora 20.

**Comment by fommil** [comment]
Can you share your project on github?

**Comment by greenrd** [comment]
No, I can't. But that shouldn't be necessary. The file doesn't exist because I haven't saved it yet, there's no great mystery about that.

**Comment by fommil** [comment]
Aah, you haven't saved it yet. That's kinda useful to know. When you save it, would it be at the location indicated?

**Comment by greenrd** [comment]
Yes, it would.

**Comment by fommil** [comment]
#1062 is probably going to result in server death when it sees this, so @rorygraves is going to handle the exception. We probably shouldn't be checking that the file exists at all.

**Comment by fommil** [comment]
(follow the newer stacktrace for more recent line numbers)

**Comment by rorygraves** [comment]
I'm guessing the typecheck file will include the file contents in this case (as the file does not exist yet) - if it doens't it should fail the request (rather than the server).
Will have a look this evening.

**Comment by fommil** [comment]
@greenrd this should be fixed as of today's release. Can you please check?
