### ISSUE TITLE
ENSIME fails to launch after gen-ensime (Emacs)

### ISSUE THREAD

**Issue by wiegraffolles** [ensime/ensime-server#933]
When running ```ensime``` in Emacs I get the following error:

```
Starting ENSIME server: /usr/lib/jvm/java-8-jdk/bin/java -classpath /usr/lib/jvm/java-8-jdk/lib/tools.jar:/home/wiegraf/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar:/home/wiegraf/.ivy2/cache/org.ensime/ensime_2.11/jars/ensime_2.11-0.9.10-SNAPSHOT.jar:/home/wiegraf/.ivy2/cache/org.ensime/server_2.11/jars/server_2.11-0.9.10-SNAPSHOT.jar:/home/wiegraf/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.6.jar:/home/wiegraf/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.6.jar:/home/wiegraf/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.3.jar:/home/wiegraf/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.3.jar:/home/wiegraf/.ivy2/cache/org.ensime/api_2.11/jars/api_2.11-0.9.10-SNAPSHOT.jar:/home/wiegraf/.ivy2/cache/com.github.stacycurl/pimpathon-core_2.11/jars/pimpathon-core_2.11-1.2.0.jar:/home/wiegraf/.ivy2/cache/com.danieltrinh/scalariform_2.11/jars/scalariform_2.11-0.1.5.jar:/home/wiegraf/.ivy2/cache/org.ensime/swank_2.11/jars/swank_2.11-0.9.10-SNAPSHOT.jar:/home/wiegraf/.ivy2/cache/org.ensime/sexpress_2.11/jars/sexpress_2.11-0.9.10-SNAPSHOT.jar:/home/wiegraf/.ivy2/cache/com.chuusai/shapeless_2.11/bundles/shapeless_2.11-2.0.0.jar:/home/wiegraf/.ivy2/cache/org.parboiled/parboiled-scala_2.11/jars/parboiled-scala_2.11-1.1.7.jar:/home/wiegraf/.ivy2/cache/org.parboiled/parboiled-core/jars/parboiled-core-1.1.7.jar:/home/wiegraf/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.11/jars/akka-slf4j_2.11-2.3.9.jar:/home/wiegraf/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.3.9.jar:/home/wiegraf/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar:/home/wiegraf/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.2.jar:/home/wiegraf/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.2.jar:/home/wiegraf/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.10.jar:/home/wiegraf/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.10.jar:/home/wiegraf/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.10.jar:/home/wiegraf/.ivy2/cache/com.h2database/h2/jars/h2-1.4.182.jar:/home/wiegraf/.ivy2/cache/com.typesafe.slick/slick_2.11/bundles/slick_2.11-2.1.0.jar:/home/wiegraf/.ivy2/cache/com.jolbox/bonecp/bundles/bonecp-0.8.0.RELEASE.jar:/home/wiegraf/.ivy2/cache/com.google.guava/guava/bundles/guava-15.0.jar:/home/wiegraf/.ivy2/cache/org.apache.commons/commons-vfs2/jars/commons-vfs2-2.0.jar:/home/wiegraf/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.1.jar:/home/wiegraf/.ivy2/cache/org.apache.maven.scm/maven-scm-api/jars/maven-scm-api-1.4.jar:/home/wiegraf/.ivy2/cache/org.codehaus.plexus/plexus-utils/jars/plexus-utils-1.5.6.jar:/home/wiegraf/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svnexe/jars/maven-scm-provider-svnexe-1.4.jar:/home/wiegraf/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svn-commons/jars/maven-scm-provider-svn-commons-1.4.jar:/home/wiegraf/.ivy2/cache/regexp/regexp/jars/regexp-1.3.jar:/home/wiegraf/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-4.7.2.jar:/home/wiegraf/.ivy2/cache/org.apache.lucene/lucene-analyzers-common/jars/lucene-analyzers-common-4.7.2.jar:/home/wiegraf/.ivy2/cache/org.ow2.asm/asm-commons/jars/asm-commons-5.0.3.jar:/home/wiegraf/.ivy2/cache/org.ow2.asm/asm-tree/jars/asm-tree-5.0.3.jar:/home/wiegraf/.ivy2/cache/org.ow2.asm/asm/jars/asm-5.0.3.jar:/home/wiegraf/.ivy2/cache/org.ow2.asm/asm-util/jars/asm-util-5.0.3.jar:/home/wiegraf/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.11.6.jar:/home/wiegraf/.ivy2/cache/org.scala-refactoring/org.scala-refactoring.library_2.11/jars/org.scala-refactoring.library_2.11-0.6.2.jar:/home/wiegraf/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.6.jar:/home/wiegraf/.ivy2/cache/io.spray/spray-can_2.11/bundles/spray-can_2.11-1.3.2.jar:/home/wiegraf/.ivy2/cache/io.spray/spray-io_2.11/bundles/spray-io_2.11-1.3.2.jar:/home/wiegraf/.ivy2/cache/io.spray/spray-util_2.11/bundles/spray-util_2.11-1.3.2.jar:/home/wiegraf/.ivy2/cache/io.spray/spray-http_2.11/bundles/spray-http_2.11-1.3.2.jar -Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M -Densime.config=/home/wiegraf/Sync/Scala/FMCalcWeb/.ensime org.ensime.server.Server
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: akka/event/slf4j/SLF4JLogging
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: akka.event.slf4j.SLF4JLogging
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more

Process *inferior-ensime-server-example* exited abnormally with code 1
```
I have tried deleting my .ensime file and ensime cache and running ```gen-ensime``` in sbt. The ```gen-ensime``` runs without any errors, but I cannot get the server to launch.

**Comment by fommil** [comment]
Try running ensime-update and try try again

**Comment by wiegraffolles** [comment]
Thank you! I was missing the answer right in front of my face.

**Comment by fommil** [comment]
yeah, this was a transient failure in sbt/ivy by the looks of things.

**Comment by greenrd** [comment]
I just experienced a similar, but different error, and `ensime-update` (which I recently renamed to `ensime-server-update`) was again the way to fix it. Is there any way we can be more robust against these sort of errors?

**Comment by fommil** [comment]
by scrapping sbt. This is an upstream bug.
