### ISSUE TITLE
Search Indexer ClassNotFound

### ISSUE THREAD

**Issue by parsnips** [ensime/ensime-server#942]
Updated to latest ensime this morning and the search indexer started to freak out over a dependency missing:

```
10:45:07.895 [default-akka.actor.default-dispatcher-3] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:full-typecheck-finished)
Exception in thread "pool-2-thread-8" Exception in thread "pool-2-thread-7" Exception in thread "pool-2-thread-1" java.lang.NoClassDefFoundError: scala/tools/nsc/util/ClassFileLookup
	at scala.tools.scalap.scalax.rules.scalasig.ScalaSigParser$.scalaSigFromAttribute(ScalaSig.scala:38)
	at scala.tools.scalap.scalax.rules.scalasig.ScalaSigParser$.parse(ScalaSig.scala:41)
	at org.ensime.indexer.ClassfileDepickler.depickle(ClassfileDepickler.scala:19)
	at org.ensime.indexer.ClassfileDepickler.<init>(ClassfileDepickler.scala:10)
	at org.ensime.indexer.SearchService.org$ensime$indexer$SearchService$$extractSymbols(SearchService.scala:152)
	at org.ensime.indexer.SearchService$$anonfun$14$$anonfun$apply$6$$anonfun$apply$2.apply$mcV$sp(SearchService.scala:102)
	at org.ensime.indexer.SearchService$$anonfun$14$$anonfun$apply$6$$anonfun$apply$2.apply(SearchService.scala:100)
	at org.ensime.indexer.SearchService$$anonfun$14$$anonfun$apply$6$$anonfun$apply$2.apply(SearchService.scala:100)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.10:45:09.053 [pool-2-thread-21] DEBUG org.ensime.indexer.SearchService - indexing file:///Users/mparsons/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.4.4/jackson-module-jaxb-annotations-2.4.4.jar
run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.util.ClassFileLookup
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
```

For every file it attempted to index.  My environment per ensime logs:

```
10:45:02.799 [main] INFO  org.ensime.server.Server - Environment:
  OS : Mac OS X
  Java : Java HotSpot(TM) 64-Bit Server VM 23.25-b01, Java(TM) SE Runtime Environment 1.7.0_25-b15
  Scala : version 2.11.4
  Ensime : 0.9.10-SNAPSHOT
```

Please let me know what additional information I can provide!

**Comment by fommil** [comment]
Just the usual stuff: version of scala, can you share the project, etc

**Comment by rorygraves** [comment]
@fommil  to be fair - I see most of that info at the bottom :smiley: 

I believe this is a Scala 2.11.4 vs 2.11.6  - the class ```ScalaSigParser``` refers to ```ClassFileLookup``` in ```compiler/scala/tools/nsc/util/ClassFileLookup.scala (which I can't find in 2.11.4

This will be one of the 'no breaking changes in minor versions' type of  breaking changes.

@parsnips - can you try tweaking your scala version to 2.11.6 temporarily?

**Comment by parsnips** [comment]
@rorygraves thanks, that's the ticket.  Thanks ~~Obama~~ Martin.

**Comment by fommil** [comment]
@rorygraves curse you and your large monitor! :stuck_out_tongue:

**Comment by fommil** [comment]
dupe #929 shouldn't spotted that
