### ISSUE TITLE
Ensime server throws `java.lang.NoSuchMethodError` on startup

### ISSUE THREAD

**Issue by isomarcte** [ensime/ensime-server#944]
Starting today, when I launch ensime for any Scala project I get the following error

````
Starting ENSIME server: /usr/lib/jvm/java-8-openjdk/bin/java -classpath /usr/lib/jvm/java-8-openjdk/lib/tools.jar:/home/foo/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar:/home/foo/.ivy2/cache/org.ensime/ensime_2.11/jars/ensime_2.11-0.9.10-SNAPSHOT.jar:/home/foo/.ivy2/cache/org.ensime/server_2.11/jars/server_2.11-0.9.10-SNAPSHOT.jar:/home/foo/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.6.jar:/home/foo/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.6.jar:/home/foo/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.3.jar:/home/foo/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.3.jar:/home/foo/.ivy2/cache/org.ensime/api_2.11/jars/api_2.11-0.9.10-SNAPSHOT.jar:/home/foo/.ivy2/cache/com.github.stacycurl/pimpathon-core_2.11/jars/pimpathon-core_2.11-1.4.0.jar:/home/foo/.ivy2/cache/com.danieltrinh/scalariform_2.11/jars/scalariform_2.11-0.1.5.jar:/home/foo/.ivy2/cache/org.ensime/swank_2.11/jars/swank_2.11-0.9.10-SNAPSHOT.jar:/home/foo/.ivy2/cache/org.ensime/sexpress_2.11/jars/sexpress_2.11-0.9.10-SNAPSHOT.jar:/home/foo/.ivy2/cache/com.chuusai/shapeless_2.11/bundles/shapeless_2.11-2.0.0.jar:/home/foo/.ivy2/cache/org.parboiled/parboiled-scala_2.11/jars/parboiled-scala_2.11-1.1.7.jar:/home/foo/.ivy2/cache/org.parboiled/parboiled-core/jars/parboiled-core-1.1.7.jar:/home/foo/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.11/jars/akka-slf4j_2.11-2.3.9.jar:/home/foo/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.3.9.jar:/home/foo/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar:/home/foo/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.3.jar:/home/foo/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.3.jar:/home/foo/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.12.jar:/home/foo/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.12.jar:/home/foo/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.12.jar:/home/foo/.ivy2/cache/com.h2database/h2/jars/h2-1.4.182.jar:/home/foo/.ivy2/cache/com.typesafe.slick/slick_2.11/bundles/slick_2.11-2.1.0.jar:/home/foo/.ivy2/cache/com.jolbox/bonecp/bundles/bonecp-0.8.0.RELEASE.jar:/home/foo/.ivy2/cache/com.google.guava/guava/bundles/guava-15.0.jar:/home/foo/.ivy2/cache/org.apache.commons/commons-vfs2/jars/commons-vfs2-2.0.jar:/home/foo/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.1.jar:/home/foo/.ivy2/cache/org.apache.maven.scm/maven-scm-api/jars/maven-scm-api-1.4.jar:/home/foo/.ivy2/cache/org.codehaus.plexus/plexus-utils/jars/plexus-utils-1.5.6.jar:/home/foo/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svnexe/jars/maven-scm-provider-svnexe-1.4.jar:/home/foo/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svn-commons/jars/maven-scm-provider-svn-commons-1.4.jar:/home/foo/.ivy2/cache/regexp/regexp/jars/regexp-1.3.jar:/home/foo/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-4.7.2.jar:/home/foo/.ivy2/cache/org.apache.lucene/lucene-analyzers-common/jars/lucene-analyzers-common-4.7.2.jar:/home/foo/.ivy2/cache/org.ow2.asm/asm-commons/jars/asm-commons-5.0.3.jar:/home/foo/.ivy2/cache/org.ow2.asm/asm-tree/jars/asm-tree-5.0.3.jar:/home/foo/.ivy2/cache/org.ow2.asm/asm/jars/asm-5.0.3.jar:/home/foo/.ivy2/cache/org.ow2.asm/asm-util/jars/asm-util-5.0.3.jar:/home/foo/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.11.6.jar:/home/foo/.ivy2/cache/org.scala-refactoring/org.scala-refactoring.library_2.11/jars/org.scala-refactoring.library_2.11-0.6.2.jar:/home/foo/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.6.jar:/home/foo/.ivy2/cache/io.spray/spray-can_2.11/bundles/spray-can_2.11-1.3.3.jar:/home/foo/.ivy2/cache/io.spray/spray-io_2.11/bundles/spray-io_2.11-1.3.3.jar:/home/foo/.ivy2/cache/io.spray/spray-util_2.11/bundles/spray-util_2.11-1.3.3.jar:/home/foo/.ivy2/cache/io.spray/spray-http_2.11/bundles/spray-http_2.11-1.3.3.jar -Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M -Densime.config=/home/foo/git/helloWorld/.ensime org.ensime.server.Server
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
10:57:32.960 [default-akka.actor.default-dispatcher-4] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
10:57:32.967 [main] INFO  org.ensime.server.Server - ENSIME Server on 127.0.0.1:51206
10:57:32.968 [main] INFO  org.ensime.server.Server - Environment:
  OS : Linux
  Java : OpenJDK 64-Bit Server VM 25.45-b02, OpenJDK Runtime Environment 1.8.0_45-b14
  Scala : version 2.11.6
  Ensime : 0.9.10-SNAPSHOT
10:57:32.969 [main] INFO  org.ensime.server.Server - creating portfile /home/foo/git/helloWorld/.ensime_cache/port
10:57:32.974 [default-akka.actor.default-dispatcher-2] DEBUG org.ensime.core.Project$ProjectActor - started (org.ensime.core.Project$ProjectActor@79e3cc18)
10:57:32.984 [main] INFO  o.a.c.v.i.StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
Exception in thread "main" java.lang.NoSuchMethodError: pimpathon.list$.filterMonadicTuple2Ops(Lscala/collection/generic/FilterMonadic;)Lpimpathon/filterMonadic$FilterMonadicTuple2Ops;
	at org.ensime.indexer.SourceResolver.<init>(SourceResolver.scala:41)
	at org.ensime.core.Project.<init>(Project.scala:32)
	at org.ensime.server.Server.<init>(Server.scala:77)
	at org.ensime.server.Server$.initialiseServer(Server.scala:48)
	at org.ensime.server.Server$.main(Server.scala:44)
	at org.ensime.server.Server.main(Server.scala)
````
Most ensime features do not work, including completion.

## System Info ##
* Linux: Linux foobar 3.19.3-3-ARCH #1 SMP PREEMPT Wed Apr 8 14:10:00 CEST 2015 x86_64 GNU/Linux
* Emacs: 
  GNU Emacs 24.5.1
  Copyright (C) 2015 Free Software Foundation, Inc.
  GNU Emacs comes with ABSOLUTELY NO WARRANTY.
  You may redistribute copies of Emacs
  under the terms of the GNU General Public License.
  For more information about these matters, see the file named COPYING.
* Ensime Plugin: addSbtPlugin("org.ensime" % "ensime-sbt" % "0.1.5")

**Comment by fommil** [comment]
looks like sbt messed up the install. Try an `ensime-reload` and try again.

**Comment by isomarcte** [comment]
@fommil  Running `M-x ensime-reload` does not fix the issue. Same result in the ensime buffer. Ensime features still do not work.

**Comment by isomarcte** [comment]
@fommil Running `M-x ensime-reload` did not solve the issue, however I just blew away all the sbt cache folders as well as `.emacs.d/ensime` and now it is resolved.

Thanks

**Comment by fommil** [comment]
yeah, I wish sbt would fail reliably so that we could, at least, assign a common failure message to an FAQ.

**Comment by fommil** [comment]
I've updated the CONTRIBUTING file to try and reflect this https://github.com/ensime/ensime-server/blob/master/CONTRIBUTING.md
