### ISSUE TITLE
Emacs hangs while trying to inspect variable value in debugger

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-server#963]
I think the relevant section of the log is:

```
13:37:46.222 [Thread-10] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:debug-locate-name "57" "i") 539)

13:37:46.227 [default-akka.actor.default-dispatcher-105] ERROR org.ensime.core.DebugManager - Exception thrown whilst handling vm action
com.sun.jdi.AbsentInformationException: null
	at com.sun.tools.jdi.NonConcreteMethodImpl.variables(NonConcreteMethodImpl.java:94) ~[tools.jar:na]
	at com.sun.tools.jdi.StackFrameImpl.createVisibleVariables(StackFrameImpl.java:159) ~[tools.jar:na]
	at com.sun.tools.jdi.StackFrameImpl.visibleVariables(StackFrameImpl.java:182) ~[tools.jar:na]
	at org.ensime.core.DebugManager$VM.stackSlotForName(DebugManager.scala:840) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$VM.locationForName(DebugManager.scala:733) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$processMsg$20.apply(DebugManager.scala:352) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$processMsg$20.apply(DebugManager.scala:351) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$handleRPCWithVMAndThread$2$$anonfun$apply$5.apply(DebugManager.scala:164) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$handleRPCWithVMAndThread$2$$anonfun$apply$5.apply(DebugManager.scala:163) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
	at org.ensime.core.DebugManager$$anonfun$handleRPCWithVMAndThread$2.apply(DebugManager.scala:163) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$handleRPCWithVMAndThread$2.apply(DebugManager.scala:162) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$liftedTree1$1$1.apply(DebugManager.scala:138) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$liftedTree1$1$1.apply(DebugManager.scala:137) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
	at org.ensime.core.DebugManager.liftedTree1$1(DebugManager.scala:137) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager.withVM(DebugManager.scala:136) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager.handleRPCWithVMAndThread(DebugManager.scala:162) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager.processMsg(DebugManager.scala:350) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$receive$1.applyOrElse(DebugManager.scala:182) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[akka-actor_2.11-2.3.9.jar:na]
	at org.ensime.core.DebugManager.aroundReceive(DebugManager.scala:19) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[akka-actor_2.11-2.3.9.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[akka-actor_2.11-2.3.9.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) ~[akka-actor_2.11-2.3.9.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:221) ~[akka-actor_2.11-2.3.9.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231) ~[akka-actor_2.11-2.3.9.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
13:37:46.228 [default-akka.actor.default-dispatcher-110] ERROR org.ensime.core.Project - Error, incorrect type found in RPC call, expected: shapeless.Typeable$$anon$4@6bea000c got class java.lang.Boolean
org.ensime.core.RPCError: 201: Error, incorrect type found in RPC call, expected: shapeless.Typeable$$anon$4@6bea000c got class java.lang.Boolean
	at org.ensime.core.ProjectEnsimeApiImpl$class.callRPC(ProjectEnsimeApiImpl.scala:38) [server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Project.callRPC(Project.scala:19) [server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.ProjectEnsimeApiImpl$class.rpcDebugLocateName(ProjectEnsimeApiImpl.scala:123) [server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Project.rpcDebugLocateName(Project.scala:19) [server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocol.handleRpcReq(SwankProtocol.scala:336) [swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocol.handleIncomingMessage(SwankProtocol.scala:55) [swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocol.handleIncomingMessage(SwankProtocol.scala:34) [swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.SocketHandler$$anonfun$receive$1.applyOrElse(Server.scala:212) [server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) [akka-actor_2.11-2.3.9.jar:na]
	at org.ensime.server.SocketHandler.aroundReceive(Server.scala:186) [server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.9.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.9.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) [akka-actor_2.11-2.3.9.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:221) [akka-actor_2.11-2.3.9.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231) [akka-actor_2.11-2.3.9.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
13:37:46.228 [default-akka.actor.default-dispatcher-105] WARN  org.ensime.core.DebugManager - Could not access debug VM
13:37:46.229 [default-akka.actor.default-dispatcher-110] WARN  o.e.s.protocol.swank.SwankProtocol - handling SexpCons(SexpSymbol(:swank-rpc),SexpCons(SexpCons(SexpSymbol(swank:debug-locate-name),SexpCons(SexpString(57),SexpCons(SexpString(i),SexpNil))),SexpCons(SexpNumber(539),SexpNil))) gave Error, incorrect type found in RPC call, expected: shapeless.Typeable$$anon$4@6bea000c got class java.lang.Boolean
13:37:46.229 [default-akka.actor.default-dispatcher-110] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:abort 201 "Error, incorrect type found in RPC call, expected: shapeless.Typeable$$anon$4@6bea000c got class java.lang.Boolean") 539)
13:37:46.230 [Thread-10] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:debug-value nil) 540)

13:37:46.234 [default-akka.actor.default-dispatcher-110] ERROR o.e.s.protocol.swank.SwankProtocol - unrecognised input (:swank-rpc (swank:debug-value nil) 540)
org.ensime.sexp.DeserializationException: Didn't expect a SexpNil
	at org.ensime.sexp.formats.package$.deserializationError(package.scala:5) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolCommon$TraitFormatAlt.read(SwankProtocolConversions.scala:62) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.LowPriorityProductFormats$HListFormat$$anon$4.read(ProductFormats.scala:37) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.LowPriorityProductFormats$HListFormat$$anon$4.read(ProductFormats.scala:31) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$$anon$1.read(SwankProtocolConversions.scala:565) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$$anon$1.read(SwankProtocolConversions.scala:559) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestFormat$.read(SwankProtocolConversions.scala:761) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestFormat$.read(SwankProtocolConversions.scala:705) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankProtocolConversions.scala:778) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankProtocolConversions.scala:774) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocol$$anonfun$1.apply(SwankProtocol.scala:53) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocol$$anonfun$1.apply(SwankProtocol.scala:53) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.util.Try$.apply(Try.scala:191) ~[scala-library-2.11.6.jar:na]
	at org.ensime.server.protocol.swank.SwankProtocol.handleIncomingMessage(SwankProtocol.scala:53) [swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocol.handleIncomingMessage(SwankProtocol.scala:34) [swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.SocketHandler$$anonfun$receive$1.applyOrElse(Server.scala:212) [server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) [akka-actor_2.11-2.3.9.jar:na]
	at org.ensime.server.SocketHandler.aroundReceive(Server.scala:186) [server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.9.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.9.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) [akka-actor_2.11-2.3.9.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:221) [akka-actor_2.11-2.3.9.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231) [akka-actor_2.11-2.3.9.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
13:37:46.234 [default-akka.actor.default-dispatcher-110] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:reader-error 203 "(:swank-rpc (swank:debug-value nil) 540)")
```

**Comment by rorygraves** [comment]
Hi @greenrd - that is definitely a bug.  Actually its more than one.
1) Failure to locate the name - were you looking up a variable that didn't actually exist (some of the names get mangled).
2) A break that I'm aware of in the ensime debugger message processing - a lot of failre code returns boolean false where in this case it should return a None.
```13:37:46.228 [default-akka.actor.default-dispatcher-110] ERROR org.ensime.core.Project - Error, incorrect type found in RPC call, expected: shapeless.Typeable$$anon$4@6bea000c got class java.lang.Boolean
org.ensime.core.RPCError: 201: Error, incorrect type found in RPC call, expected: shapeless.Typeable$$anon$4@6bea000c got class java.lang.Boolean
```

This is a type cast - its expecting Option[String] and it got a boolean back, the toString on the Typeable will be fixed in the next version of shapeless.

3) This ```
13:37:46.234 [default-akka.actor.default-dispatcher-110] ERROR o.e.s.protocol.swank.SwankProtocol - unrecognised input (:swank-rpc (swank:debug-value nil) 540)
org.ensime.sexp.DeserializationException: Didn't expect a SexpNil
    at org.ensime.sexp.formats.package$.deserializationError(package.scala:5) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
    at org.ensime.server.protocol.swank.SwankProtocolCommon$TraitFormatAlt.read(SwankProtocolConversions.scala:62) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
 ```
looks odd and should be looked at by @fommil 

The debugging support is in major need of some TLC - (3) looks like a new bug - emacs is blocking waiting for a reply and it should always get one.

**Comment by fommil** [comment]
your server is a couple of commits old. I don't think upgrading will fix it, but it would help isolate the LOC if you updated https://github.com/ensime/ensime-server/blob/master/swank/src/main/scala/org/ensime/server/protocol/swank/SwankProtocolConversions.scala#L565

or if you can let us know which snapshot of ensime you're running (then we can work out which commit it likely is)

**Comment by rorygraves** [comment]
looks like emacs side sent the server a junk message
```Received msg: (:swank-rpc (swank:debug-value nil) 540)```
You can't have nil here (hence the de-serialisation exception)

I'm guess emacs doesn't actually handle the reader error (its expecting an rpc response) thus we have a hang.

I wonder if when we fail to parse a message whether we should parse as ``` (:swank-rpc ?any? 540)```  so we can respond to the rpc request with an rpc-error rather than a parse fail. - what do you think @fommil?

**Comment by fommil** [comment]
we should probably catch deserialisation exceptions and respond with an rpc error at that point. When we move to WebSockets, this will almost happen by magic.

**Comment by rorygraves** [comment]
Will put a layer of defence in here as the next thing after my current WIP

**Comment by greenrd** [comment]
The variable does exist, but it's a method parameter and I was inspecting it with point at where it was declared, so maybe that's why it didn't find it.

**Comment by rorygraves** [comment]
@greenrd  Can you share a code fragment - the exception 
```
com.sun.jdi.AbsentInformationException: null
    at com.sun.tools.jdi.NonConcreteMethodImpl.variables(NonConcreteMethodImpl.java:94) ~[tools.jar:na]
    at com.sun.tools.jdi.StackFrameImpl.createVisibleVariables(StackFrameImpl.java:159) ~[tools.jar:na]
    at com.sun.tools.jdi.StackFrameImpl.visibleVariables(StackFrameImpl.java:182) ~[tools.jar:na]
    at org.ensime.core.DebugManager$VM.stackSlotForName(DebugManager.scala:840) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
    at org.ensime.core.DebugManager$VM.locationForName(DebugManager.scala:733) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
 ``` 
implies its trying to find a variable on a abstract method (and that one of the method refs on the stack is abstract.  Realistically this is probably a bug in our handling. I would love to add a test for this.

**Comment by fommil** [comment]
tracking under #1047
