### ISSUE TITLE
"Invalid descendent file name" thrown on ensime server startup

### ISSUE THREAD

**Issue by markschaake** [ensime/ensime-server#964]
This started happening to me recently. Here is the actual stacktrace:

```
14:55:58.907 [main] INFO  org.ensime.indexer.ClassfileWatcher - Setting up new file watchers
Exception in thread "main" java.lang.NullPointerException
	at org.apache.commons.vfs2.provider.AbstractFileSystem.resolveFile(AbstractFileSystem.java:322)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.resolveFile(AbstractFileSystem.java:317)
	at org.apache.commons.vfs2.provider.AbstractFileObject.resolveFile(AbstractFileObject.java:752)
	at org.apache.commons.vfs2.provider.AbstractFileObject.resolveFiles(AbstractFileObject.java:744)
	at org.apache.commons.vfs2.provider.AbstractFileObject.getChildren(AbstractFileObject.java:647)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor.addFile(DefaultFileMonitor.java:181)
	at org.ensime.indexer.ClassfileWatcher$$anonfun$org$ensime$indexer$ClassfileWatcher$$reset$2$$anonfun$apply$5.apply(FileWatchers.scala:97)
	at org.ensime.indexer.ClassfileWatcher$$anonfun$org$ensime$indexer$ClassfileWatcher$$reset$2$$anonfun$apply$5.apply(FileWatchers.scala:94)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at org.ensime.indexer.ClassfileWatcher$$anonfun$org$ensime$indexer$ClassfileWatcher$$reset$2.apply(FileWatchers.scala:94)
	at org.ensime.indexer.ClassfileWatcher$$anonfun$org$ensime$indexer$ClassfileWatcher$$reset$2.apply(FileWatchers.scala:91)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at org.ensime.indexer.ClassfileWatcher.org$ensime$indexer$ClassfileWatcher$$reset(FileWatchers.scala:91)
	at org.ensime.indexer.ClassfileWatcher.<init>(FileWatchers.scala:103)
	at org.ensime.core.Project.<init>(Project.scala:40)
	at org.ensime.server.Server.<init>(Server.scala:85)
	at org.ensime.server.Server$.initialiseServer(Server.scala:56)
	at org.ensime.server.Server$.main(Server.scala:47)
	at org.ensime.server.Server.main(Server.scala)
14:56:00.929 [Thread-8] ERROR o.a.c.vfs2.impl.DefaultFileMonitor - Invalid descendent file name "s2:".
org.apache.commons.vfs2.FileSystemException: Invalid descendent file name "s2:".
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveName(DefaultFileSystemManager.java:791) ~[commons-vfs2-2.0.jar:2.0]
```

The only files named "s2" in our project are parts of our package path for scala sources:

```
$ find . -name s2
./data/core/src/main/scala/org/allenai/s2
./data/core/src/test/scala/org/allenai/s2
./data/crawler/src/main/scala/org/allenai/s2
/data/crawler/src/test/scala/org/allenai/s2
...
```

Wondering if this could have been caused by https://github.com/ensime/ensime-server/commit/b75b88a9434684d47c8db5acec302514d3f70b65 ? (shot in the dark based on `git blame` for the `FileWatchers.scala` file).

**Comment by markschaake** [comment]
How embarrassing... I missed the ":" in "s2:" and so my find did not pick up the actual culprit, which was in `target/scala-2.11/s2:`

Problem solved, sorry for the noise!
