### ISSUE TITLE
Getting "object scala in compiler mirror not found" when starting

### ISSUE THREAD

**Issue by avernet** [ensime/ensime-server#978]
I'm new ENSIME. After having created a `.ensime` manually, I start ENSIME from Emacs (`M-x ensime`), and get the error below. I suspected that ENSIME might not have been able to find the Scala compiler, but at the very beginning of the log, after "Starting ENSIME server", I see the correct path for the Scala compiler jar (`/Users/avernet/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.6.jar`). Quid?

```
23:00:04.566 [EnsimeServer-akka.actor.default-dispatcher-9] ERROR akka.actor.OneForOneStrategy - object scala in compiler mirror not found.
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:164) ~[akka-actor_2.11-2.3.9.jar:na]
        at akka.actor.ActorCell.create(ActorCell.scala:596) ~[akka-actor_2.11-2.3.9.jar:na]
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456) ~[akka-actor_2.11-2.3.9.jar:na]
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478) ~[akka-actor_2.11-2.3.9.jar:na]
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279) [akka-actor_2.11-2.3.9.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.9.jar:na]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231) [akka-actor_2.11-2.3.9.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
Caused by: scala.reflect.internal.MissingRequirementError: object scala in compiler mirror not found.
        at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17) ~[scala-reflect-2.11.6.jar:na]
        at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18) ~[scala-reflect-2.11.6.jar:na]
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53) ~[scala-reflect-2.11.6.jar:na]
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66) ~[scala-reflect-2.11.6.jar:na]
        at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:173) ~[scala-reflect-2.11.6.jar:na]
        at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackage$lzycompute(Definitions.scala:161) ~[scala-reflect-2.11.6.jar:na]
        at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackage(Definitions.scala:161) ~[scala-reflect-2.11.6.jar:na]
        at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackageClass$lzycompute(Definitions.scala:162) ~[scala-reflect-2.11.6.jar:na]
        at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackageClass(Definitions.scala:162) ~[scala-reflect-2.11.6.jar:na]
        at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1392) ~[scala-reflect-2.11.6.jar:na]
        at scala.tools.nsc.Global$Run.<init>(Global.scala:1216) ~[scala-compiler-2.11.6.jar:na]
        at scala.tools.nsc.interactive.Global$TyperRun.<init>(Global.scala:1207) ~[scala-compiler-2.11.6.jar:na]
        at scala.tools.nsc.interactive.Global.newTyperRun(Global.scala:1230) ~[scala-compiler-2.11.6.jar:na]
        at scala.tools.nsc.interactive.Global.<init>(Global.scala:297) ~[scala-compiler-2.11.6.jar:na]
        at org.ensime.core.RichPresentationCompiler.<init>(RichPresentationCompiler.scala:195) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.Analyzer.makeScalaCompiler(Analyzer.scala:98) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.Analyzer.<init>(Analyzer.scala:66) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.Project$$anonfun$7.apply(Project.scala:177) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.Project$$anonfun$7.apply(Project.scala:177) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at akka.actor.TypedCreatorFunctionConsumer.produce(Props.scala:343) ~[akka-actor_2.11-2.3.9.jar:na]
        at akka.actor.Props.newActor(Props.scala:252) ~[akka-actor_2.11-2.3.9.jar:na]
        at akka.actor.ActorCell.newActor(ActorCell.scala:552) ~[akka-actor_2.11-2.3.9.jar:na]
        at akka.actor.ActorCell.create(ActorCell.scala:578) ~[akka-actor_2.11-2.3.9.jar:na]
        ... 9 common frames omitted
23:00:04.675 [EnsimeServer-akka.actor.default-dispatcher-9] DEBUG akka.actor.ActorCell - stopped
```

**Comment by fommil** [comment]
Check that it works with an SBT project first.

**Comment by fommil** [comment]
You're missing the Scala library in your project by the looks of things

**Comment by avernet** [comment]
I'm also convinced this is not an ENSIME bug, and really appreciate your help. Here is the full log: https://gist.githubusercontent.com/avernet/c14c3338fa4b38c8c24c/raw/gistfile1.txt (sorry, I should have posted this right away).

You're saying I'm missing "the Scala library" in my project, and indeed, in the ENSIME log, I see `WARN  org.ensime.core.Analyzer - scala-library.jar was not present`. But when ENSIME is started, `/Users/avernet/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar` is used, as mentioned at the beginning of the log. Also, if that matters, in `.ensime`, `compile-deps` and `runtime-deps` point to a directory that contains `scala-library-2.11.6.jar`.

Are you referring to a different Scala library?

**Comment by avernet** [comment]
Ah! Adding `scala-library-2.11.6.jar` to `compile-deps` solved the problem. Apparently `compile-deps` doesn't support pointing to a directory that contains the jar files, it must list each `jar` file explicitly.

Now, I've got to include 138 jars there (!), that are all in the same directory. Is there a way not to list them all explicitly in the `.ensime`? This, other than switching to SBT ;).

**Comment by fommil** [comment]
Write a plugin for your build tool to generate the config. What are you using?

**Comment by avernet** [comment]
`<ashamed>`We're still using Ant`</ashamed>`. But we'll move to SBT soon, hopefully. So no worries, for now, I'll just generate the list. Thank you for your help, and I'm looking forward to using ENSIME!

**Comment by fommil** [comment]
An ant plugin would be really easy to write (assuming you can get access to the project model), we'd love to see a project to do that. I know several large corporates that still use ant/ivy.

**Comment by rorygraves** [comment]
@avernet I don't think you should feel ashamed - I know we can all share ware stories about using 'unusual' builds (@fommil - I'm looking at you).  And ofc the scala compiler users ant as well ;)

**Comment by vpatryshev** [comment]
Had the same in IntelliJ. Full rebuild saved me.

**Comment by smac89** [comment]
Almost the same solution as above, but I had to close the project and reimport it for this stupid error to go away

**Comment by fommil** [comment]
locking this because IntelliJ users are showing up and commenting about something that is completely unrelated to ensime.
