### ISSUE TITLE
Missing deps in latest release?

### ISSUE THREAD

**Issue by parsnips** [ensime/ensime-server#984]
version 20150607.437

```
[info] Loading global plugins from /Users/mparsons/.sbt/0.13/plugins
[info] Loading project definition from /private/var/folders/ts/fll94gzx5bg3k22wks1pg2tw0000gn/T/ensime_update_6661pyp/project
[info] Updating {file:/private/var/folders/ts/fll94gzx5bg3k22wks1pg2tw0000gn/T/ensime_update_6661pyp/project/}ensime_update_6661pyp-build...
[info] Resolving org.scala-sbt#global-plugins;0.0 ...
[info] Resolving org.ensime#ensime-sbt;0.1.5-SNAPSHOT ...
[info] Resolving org.ensime#ensime-sbt;0.1.5-SNAPSHOT ...
[info] Resolving com.typesafe.sbt#sbt-scalariform;1.3.0 ...
[info] Resolving org.scalariform#scalariform_2.10;0.1.4 ...
[info] Resolving org.scala-lang#scala-library;2.10.4 ...
[info] Resolving org.scala-sbt#sbt;0.13.8 ...
[info] Resolving org.scala-sbt#main;0.13.8 ...
[info] Resolving org.scala-sbt#actions;0.13.8 ...
[info] Resolving org.scala-sbt#classpath;0.13.8 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.4 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.4 ...
[info] Resolving org.scala-sbt#launcher-interface;0.13.8 ...
[info] Resolving org.scala-sbt#interface;0.13.8 ...
[info] Resolving org.scala-sbt#io;0.13.8 ...
[info] Resolving org.scala-sbt#control;0.13.8 ...
[info] Resolving org.scala-sbt#completion;0.13.8 ...
[info] Resolving org.scala-sbt#collections;0.13.8 ...
[info] Resolving jline#jline;2.11 ...
[info] Resolving org.scala-sbt#api;0.13.8 ...
[info] Resolving org.scala-sbt#compiler-integration;0.13.8 ...
[info] Resolving org.scala-sbt#incremental-compiler;0.13.8 ...
[info] Resolving org.scala-sbt#logging;0.13.8 ...
[info] Resolving org.scala-sbt#process;0.13.8 ...
[info] Resolving org.scala-sbt#relation;0.13.8 ...
[info] Resolving org.scala-sbt#compile;0.13.8 ...
[info] Resolving org.scala-sbt#classfile;0.13.8 ...
[info] Resolving org.scala-sbt#persist;0.13.8 ...
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.8 ...
[info] Resolving org.scala-sbt#ivy;0.13.8 ...
[info] Resolving org.scala-sbt#cross;0.13.8 ...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-fccfbd44c9f64523b61398a0155784dcbaeae28f ...
[info] Resolving com.jcraft#jsch;0.1.46 ...
[info] Resolving org.scala-sbt#serialization_2.10;0.1.1 ...
[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.0 ...
[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving org.scala-sbt#run;0.13.8 ...
[info] Resolving org.scala-sbt#task-system;0.13.8 ...
[info] Resolving org.scala-sbt#tasks;0.13.8 ...
[info] Resolving org.scala-sbt#tracking;0.13.8 ...
[info] Resolving org.scala-sbt#cache;0.13.8 ...
[info] Resolving org.scala-sbt#testing;0.13.8 ...
[info] Resolving org.scala-sbt#test-agent;0.13.8 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving org.scala-sbt#main-settings;0.13.8 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.8 ...
[info] Resolving org.scala-sbt#command;0.13.8 ...
[info] Resolving org.scala-sbt#logic;0.13.8 ...
[info] Resolving org.scala-sbt#compiler-interface;0.13.8 ...
[info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.8 ...
[info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.8 ...
[info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.8 ...
[info] Resolving org.scala-lang#jline;2.10.4 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to ensime_update_6661pyp (in build file:/private/var/folders/ts/fll94gzx5bg3k22wks1pg2tw0000gn/T/ensime_update_6661pyp/)
[info] Updating {file:/private/var/folders/ts/fll94gzx5bg3k22wks1pg2tw0000gn/T/ensime_update_6661pyp/}ensime_update_6661pyp...
[info] Resolving org.scala-lang#scala-compiler;2.11.6 ...
[info] Resolving org.scala-lang#scala-library;2.11.6 ...
[info] Resolving org.scala-lang#scala-reflect;2.11.6 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.3 ...
[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.11;1.0.3 ...
[info] Resolving org.ensime#ensime_2.11;0.9.10-SNAPSHOT ...
[info] Resolving org.ensime#ensime_2.11;0.9.10-SNAPSHOT ...
[warn] problem while downloading module descriptor: https://oss.sonatype.org/content/repositories/snapshots/org/ensime/ensime_2.11/0.9.10-SNAPSHOT/ensime_2.11-0.9.10-SNAPSHOT.pom: invalid sha1: expected=80f1fa92215c8645fc528cd5b988929eb061d31f computed=07dcda0d39c369b2d29b8ef75daa7a45275059da (511ms)
[warn] 	module not found: org.ensime#ensime_2.11;0.9.10-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/mparsons/.ivy2/local/org.ensime/ensime_2.11/0.9.10-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/ensime/ensime_2.11/0.9.10-SNAPSHOT/ensime_2.11-0.9.10-SNAPSHOT.pom
[warn] ==== Maven2 Local: tried
[warn]   file:/Users/mparsons/.m2/repository/org/ensime/ensime_2.11/0.9.10-SNAPSHOT/ensime_2.11-0.9.10-SNAPSHOT.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/org/ensime/ensime_2.11/0.9.10-SNAPSHOT/ensime_2.11-0.9.10-SNAPSHOT.pom
[warn] ==== Typesafe repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/org/ensime/ensime_2.11/0.9.10-SNAPSHOT/ensime_2.11-0.9.10-SNAPSHOT.pom
[warn] ==== Akka Repo: tried
[warn]   http://repo.akka.io/repository/org/ensime/ensime_2.11/0.9.10-SNAPSHOT/ensime_2.11-0.9.10-SNAPSHOT.pom
[info] Resolving org.scala-lang#scalap;2.11.6 ...
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.ensime#ensime_2.11;0.9.10-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.ensime:ensime_2.11:0.9.10-SNAPSHOT (/private/var/folders/ts/fll94gzx5bg3k22wks1pg2tw0000gn/T/ensime_update_6661pyp/build.sbt#L19-25)
[warn] 		  +- default:ensime_update_6661pyp_2.11:0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: org.ensime#ensime_2.11;0.9.10-SNAPSHOT: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
	at xsbt.boot.Using$.withResource(Using.scala:11)
	at xsbt.boot.Using$.apply(Using.scala:10)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.updateEither(IvyActions.scala:165)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.ensime#ensime_2.11;0.9.10-SNAPSHOT: not found
[error] Total time: 3 s, completed Jun 9, 2015 6:29:43 PM
```

**Comment by fommil** [comment]
sounds like you've got a dodgy ivy cache, they're definitely there.

**Comment by fommil** [comment]
actually, you're resolving `ensime` not `server`... your emacs client is **really** old. Upgrade via MELPA.

**Comment by fommil** [comment]
hmm, actually this might be a transient problem with sonatype. I get gateway errors here http://oss.sonatype.org/content/repositories/snapshots/org/ensime/

**Comment by fommil** [comment]
try again, sonatype just came back up for me.

**Comment by parsnips** [comment]
Yeah it did for me too:

```
[warn] problem while downloading module descriptor: https://oss.sonatype.org/content/repositories/snapshots/org/ensime/ensime_2.11/0.9.10-SNAPSHOT/ensime_2.11-0.9.10-SNAPSHOT.pom: invalid sha1: expected=80f1fa92215c8645fc528cd5b988929eb061d31f computed=07dcda0d39c369b2d29b8ef75daa7a45275059da (639ms)
[warn] 	module not found: org.ensime#ensime_2.11;0.9.10-SNAPSHOT
```

**Comment by parsnips** [comment]
Ugh... scrolling:

```
/ensime_2.11-0.9.10-SNAPSHOT.pom: invalid sha1: expected=80f1fa92215c8645fc528cd5b988929eb061d31f computed=07dcda0d39c369b2d29b8ef75daa7a45275059da (639ms)
```

**Comment by theshortcut** [comment]
Getting the same invalid sha1:

```
[warn] problem while downloading module descriptor: https://oss.sonatype.org/content/repositories/snapshots/org/ensime/ensime_2.11/0.9.10-SNAPSHOT/ensime_2.11-0.9.10-SNAPSHOT.pom: invalid sha1: expected=80f1fa92215c8645fc528cd5b988929eb061d31f computed=07dcda0d39c369b2d29b8ef75daa7a45275059da (522ms)
```

**Comment by fommil** [comment]
Just wipe out the org.ensime artefacts in your ivy folder. If it still happens after that I can force another release, they might have lost data or something.

**Comment by gaydenko** [comment]
The expected sum on the site is really incorrect, I have got the same sum as @theshortcut :

```
tmp $ wget https://oss.sonatype.org/content/repositories/snapshots/org/ensime/ensime_2.11/0.9.10-SNAPSHOT/ensime_2.11-0.9.10-SNAPSHOT.pom
--2015-06-10 01:41:21--  https://oss.sonatype.org/content/repositories/snapshots/org/ensime/ensime_2.11/0.9.10-SNAPSHOT/ensime_2.11-0.9.10-SNAPSHOT.pom
Resolving oss.sonatype.org (oss.sonatype.org)... 52.1.220.206, 52.5.199.33
Connecting to oss.sonatype.org (oss.sonatype.org)|52.1.220.206|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1300 (1.3K) [application/xml]
Saving to: ‘ensime_2.11-0.9.10-SNAPSHOT.pom’

ensime_2.11-0.9.10-SNAPSHOT.pom    100%[==================================================================>]   1.27K  --.-KB/s   in 0s     

2015-06-10 01:41:22 (179 MB/s) - ‘ensime_2.11-0.9.10-SNAPSHOT.pom’ saved [1300/1300]

tmp $ sha1sum ensime_2.11-0.9.10-SNAPSHOT.pom
07dcda0d39c369b2d29b8ef75daa7a45275059da  ensime_2.11-0.9.10-SNAPSHOT.pom
tmp $ 
```

**Comment by fommil** [comment]
ok, I've redisted. Try now. You can always force an update of the server with `M-x ensime-update`

**Comment by gaydenko** [comment]
@fommil , just have updated without problems.

**Comment by fommil** [comment]
:smile:

**Comment by parsnips** [comment]
beautiful thank you @fommil !
